# This is the configuration used to check the rubocop source code.

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  Include:
    - '**/*.lic'
    - '**/*.rb'

Naming/FileName:
  Enabled: false

Style:
  Enabled: false
  
Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false
  
Layout/HashAlignment:
  Enabled: false
  
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
  
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
  
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
    
Layout/EmptyLines:
  Enabled: false
    
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
