name: 🙋 Game Obj issue
description: Discussion about existing gameobj-data.xml, including additions, changes, or issues.
labels: ["game-obj-data"]
title: "[gameobj] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing an issue 😄 !
        Before you submit, please search open/closed issues before submitting since someone might have asked the same thing before!
  - type: textarea
    id: brief_description
    attributes:
      label: Brief Description
      description: |
        Provide a brief description of issue, context of how this affecting you, and/or what were you trying to accomplish. 
        Giving this information helps us to come up with an appropriate solution.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: behavior_expected
    attributes:
      label: Expected Behavior 
      description: |
        Tell us how it is expected to work.
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: behavior_current
    attributes:
      label: Current Behavior
      description: |
        Tell us how it is currently working.
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Give any ideas on how to implement this feature or a similar solution/workaround that already exists.
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: |
        Give real examples of issue, changes, or request.
      placeholder: 
    validations:
      required: false