name: 💬 Request For Comment (RFC)2
description: Discussion about feature, enhancements, or script takeovers
title: "[RFC]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing an issue 😄 ! Before you submit, please read the following: |
        Search open/closed issues before submitting since someone might have asked the same thing before!
  - type: input
    id: scriptname
    attributes:
      label: Script Name
      description: Name of the script seeking RFC about?
      placeholder: ex. bigshot.lic
    validations:
      required: false
  - type: textarea
    id: rfc
    attributes:
      label: RFC
      description: Provide a detailed summary of the issue here
      placeholder: I want xyz feature added!
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        How has this issue affected you? What are you trying to accomplish? |
        Providing context helps us come up with a solution that is most useful in the real world
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: |
        Examples help us understand the requested feature better
      placeholder: 
    validations:
      required: false
