name: 🐛 Script Bug Report
description: Discussion about issues for a specific lich script
labels: []
title: "[script] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing an issue 😄 !
        Before you submit, please search open/closed issues before submitting since someone might have asked the same thing before!
  - type: input
    id: scriptname
    attributes:
      label: Script Name
      description: Name of the script in question?
      placeholder: ex. bigshot.lic
    validations:
      required: true
  - type: textarea
    id: bug_summary
    attributes:
      label: Bug Report
      description: |
        Provide a detailed summary of the issue here.
        How has this issue affected you? What are you trying to accomplish?
      placeholder:
    validations:
      required: true
  - type: textarea
    id: behavior_expected
    attributes:
      label: Expected Behavior
      description: |
        Tell us what should happen.
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: behavior_current
    attributes:
      label: Current Behavior
      description: |
        Tell us what happens instead of the expected behavior.
        If you are seeing an error, please include the full error message and stack trace.
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Not obligatory, but suggest a fix/reason for the bug
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: c
    attributes:
      label: Possible Solution
      description: |
        Not obligatory, but suggest a fix/reason for the bug
      placeholder: 
    validations:
      required: false
