create_table "event:duskruin", keys: [:name]

migrate "gem", "event:duskruin" do
  insert(:name, %{flame-banded gold chameleon agate})
  insert(:name, %{thin shard of iridescent fire agate})
  insert(:name, %{gently sloped green moss agate})
  insert(:name, %{round of gnat-filled amber})
  insert(:name, %{slice of gold-blended ametrine})
  insert(:name, %{fragment of lilac-toned amethyst})
  insert(:name, %{brilliant teal-laced azurite})
  insert(:name, %{scintillating scarlet red blazestar})
  insert(:name, %{inky-cored vivid carmine bloodjewel})
  insert(:name, %{cluster of gingery golden chrysoberyl})
  insert(:name, %{clouded maize-colored citrine})
  insert(:name, %{pale metallic silver mistvein diamond})
  insert(:name, %{square-cut deep pink diamond})
  insert(:name, %{sharply cut salorisa pink diamond})
  insert(:name, %{large blood red diamond})
  insert(:name, %{flawless argent-white diamond})
  insert(:name, %{pale-edged powder blue dreamstone})
  insert(:name, %{smooth black umber-suffused dreamstone})
  insert(:name, %{heart-shaped aqua green emerald})
  insert(:name, %{black-rayed celadon star emerald})
  insert(:name, %{multi-faceted sky blue feystone})
  insert(:name, %{six-pointed rich sanguine garnet})
  insert(:name, %{beryl green crystal-filled geode})
  insert(:name, %{pristine smoky violet glimaerstone})
  insert(:name, %{teardrop of mauve petrified haon})
  insert(:name, %{dainty orb of primrose yellow heliodor})
  insert(:name, %{cushion-cut ember orange hyacinth})
  insert(:name, %{bronze-tinged lambent yellow jacinth})
  insert(:name, %{slim bar of woodland green jade})
  insert(:name, %{pyrite-capped vibrant blue lapis lazuli})
  insert(:name, %{small disk of velvety green malachite})
  insert(:name, %{silver-washed celestial blue moonstone})
  insert(:name, %{cyan-haloed creamy ivory moonstone})
  insert(:name, %{pearlescent raven black opal})
  insert(:name, %{pellucid blue-green ora-bloom})
  insert(:name, %{oversized shadowy purple pearl})
  insert(:name, %{glimmering magnolia white pearl})
  insert(:name, %{tiny prism of wintry blue peridot})
  insert(:name, %{trilliant-cut yellow-green peridot})
  insert(:name, %{triangular pastel rainbow quartz})
  insert(:name, %{hazy shard of faint pink rose quartz})
  insert(:name, %{cube of sheer blossom pink rosespar})
  insert(:name, %{wheel-incised incarnadine ruby})
  insert(:name, %{coin-sized seafoam white sandsilver})
  insert(:name, %{silver-swept blue mistvein sapphire})
  insert(:name, %{honey-tinted indigo water sapphire})
  insert(:name, %{dark-veined apple green turquoise})
end

migrate "quest", "event:duskruin" do
  insert(:name, %{jagged white sunstone shard})
  insert(:name, %{broken white opal sphere})
  insert(:name, %{white dreamstone sliver})
  insert(:name, %{thin platinum strip})
  insert(:name, %{black opal fragment})
  insert(:name, %{blood red garnet chunk})
  insert(:name, %{coarse grey moonstone shard})
  insert(:name, %{thin iron strip})
  insert(:name, %{cracked ur-barath stone})
  insert(:name, %{broken fire opal chunk})
  insert(:name, %{splintered fire agate shard})
  insert(:name, %{thin kakore strip})
  insert(:name, %{lopsided golden moonstone sphere})
  insert(:name, %{sharp golden topaz shard})
  insert(:name, %{golden glimaerstone nugget})
  insert(:name, %{reticulated crystal-edged golvern segment})
end
