migrate :weapon, :pawnshop do
  insert(:noun, %{ahlspiess})
  insert(:noun, %{alfange})
  insert(:noun, %{angon})
  insert(:noun, %{arbalest})
  insert(:noun, %{backslasher})
  insert(:noun, %{baculus})
  insert(:noun, %{badelaire})
  insert(:noun, %{balestarius})
  insert(:noun, %{balta})
  insert(:noun, %{baselard})
  insert(:noun, %{basilard})
  insert(:noun, %{battle-axe})
  insert(:noun, %{battle-quoit})
  insert(:noun, %{bidenhander})
  insert(:noun, %{bilbo})
  insert(:noun, %{bill})
  insert(:noun, %{binnol})
  insert(:noun, %{bisacuta})
  insert(:noun, %{bladed-disc})
  insert(:noun, %{bladed-ring})
  insert(:noun, %{bladestaff})
  insert(:noun, %{bodkin})
  insert(:noun, %{bolas})
  insert(:noun, %{boleadoras})
  insert(:noun, %{brandestoc})
  insert(:noun, %{braquemar})
  insert(:noun, %{bullwhip})
  insert(:noun, %{carp's-tongue})
  insert(:noun, %{cateia})
  insert(:noun, %{chakram})
  insert(:noun, %{Charl's-tail})
  insert(:noun, %{chereb})
  insert(:noun, %{chest-ripper})
  insert(:noun, %{cinquedea})
  insert(:noun, %{colichemarde})
  insert(:noun, %{contus})
  insert(:noun, %{coustille})
  insert(:noun, %{craquemarte})
  insert(:noun, %{croc})
  insert(:noun, %{crosier})
  insert(:noun, %{cutlass})
  insert(:noun, %{dhara})
  insert(:noun, %{dirk})
  insert(:noun, %{doloire})
  insert(:noun, %{dory})
  insert(:noun, %{falarica})
  insert(:noun, %{falcastra})
  insert(:noun, %{falcata})
  insert(:noun, %{falx})
  insert(:noun, %{fang})
  insert(:noun, %{fauchard})
  insert(:noun, %{fleuret})
  insert(:noun, %{flyssa})
  insert(:noun, %{framea})
  insert(:noun, %{francisca})
  insert(:noun, %{fuscina})
  insert(:noun, %{gaesum})
  insert(:noun, %{gauntlet-sword})
  insert(:noun, %{gladius})
  insert(:noun, %{godendag})
  insert(:noun, %{goliah})
  insert(:noun, %{goupillon})
  insert(:noun, %{grab-stabber})
  insert(:noun, %{guisarme})
  insert(:noun, %{hammerbeak})
  insert(:noun, %{hand-hook})
  insert(:noun, %{hippe})
  insert(:noun, %{hook})
  insert(:noun, %{hook-claw})
  insert(:noun, %{hoolurge})
  insert(:noun, %{jaculum})
  insert(:noun, %{jitte})
  insert(:noun, %{kama})
  insert(:noun, %{katzbalger})
  insert(:noun, %{kheten})
  insert(:noun, %{kilij})
  insert(:noun, %{kiss-of-Ivas})
  insert(:noun, %{knee-breaker})
  insert(:noun, %{knuckle-guard})
  insert(:noun, %{koncerz})
  insert(:noun, %{korseke})
  insert(:noun, %{kozuka})
  insert(:noun, %{kukri})
  insert(:noun, %{kunai})
  insert(:noun, %{langseax})
  insert(:noun, %{lisan})
  insert(:noun, %{longhammer})
  insert(:noun, %{machera})
  insert(:noun, %{magari-yari})
  insert(:noun, %{manople})
  insert(:noun, %{massuelle})
  insert(:noun, %{mattina})
  insert(:noun, %{misericord})
  insert(:noun, %{nage-yari})
  insert(:noun, %{nagimaki})
  insert(:noun, %{Niima's-embrace})
  insert(:noun, %{no-dachi})
  insert(:noun, %{oncin})
  insert(:noun, %{ono})
  insert(:noun, %{paiscush})
  insert(:noun, %{palache})
  insert(:noun, %{parazonium})
  insert(:noun, %{partisan})
  insert(:noun, %{partizan})
  insert(:noun, %{pata})
  insert(:noun, %{pavade})
  insert(:noun, %{pelta})
  insert(:noun, %{periperiu})
  insert(:noun, %{pernat})
  insert(:noun, %{pickaxe})
  insert(:noun, %{pike})
  insert(:noun, %{pill})
  insert(:noun, %{pit-knife})
  insert(:noun, %{poleaxe})
  insert(:noun, %{polehammer})
  insert(:noun, %{pugio})
  insert(:noun, %{quadrelle})
  insert(:noun, %{ranseur})
  insert(:noun, %{ridgemace})
  insert(:noun, %{runka})
  insert(:noun, %{sabar})
  insert(:noun, %{sabiet})
  insert(:noun, %{sap})
  insert(:noun, %{sarissa})
  insert(:noun, %{schiavona})
  insert(:noun, %{schlager})
  insert(:noun, %{scorpion})
  insert(:noun, %{seax})
  insert(:noun, %{shail})
  insert(:noun, %{shield-breaker})
  insert(:noun, %{shield-sunderer})
  insert(:noun, %{shield-sword})
  insert(:noun, %{shillelagh})
  insert(:noun, %{short-sword})
  insert(:noun, %{sica})
  insert(:noun, %{sidearm-of-Onar})
  insert(:noun, %{sidesword})
  insert(:noun, %{skull-crusher})
  insert(:noun, %{skull-piercer})
  insert(:noun, %{slap-slasher})
  insert(:noun, %{slasher})
  insert(:noun, %{slash-fist})
  insert(:noun, %{slash-jack})
  insert(:noun, %{spadroon})
  insert(:noun, %{sparte})
  insert(:noun, %{spatha})
  insert(:noun, %{spetum})
  insert(:noun, %{spiculum})
  insert(:noun, %{spike})
  insert(:noun, %{spiked-hammer})
  insert(:noun, %{spiked-staff})
  insert(:noun, %{spike-fist})
  insert(:noun, %{spontoon})
  insert(:noun, %{staff-of-Lumnis})
  insert(:noun, %{stiletto})
  insert(:noun, %{sudis})
  insert(:noun, %{sword-breaker})
  insert(:noun, %{sword-of-Phoen})
  insert(:noun, %{swordstaff})
  insert(:noun, %{taavish})
  insert(:noun, %{tabar})
  insert(:noun, %{tachi})
  insert(:noun, %{takouba})
  insert(:noun, %{tambara})
  insert(:noun, %{tanto})
  insert(:noun, %{taper})
  insert(:noun, %{tetsubo})
  insert(:noun, %{thrak-bite})
  insert(:noun, %{tizona})
  insert(:noun, %{tock})
  insert(:noun, %{tocke})
  insert(:noun, %{tomahawk})
  insert(:noun, %{toporok})
  insert(:noun, %{trailknife})
  insert(:noun, %{truncheon})
  insert(:noun, %{tuck})
  insert(:noun, %{verdun})
  insert(:noun, %{war-quoit})
  insert(:noun, %{warstaff})
  insert(:noun, %{warsword})
  insert(:noun, %{weighted-cord})
  insert(:noun, %{wight-claw})
  insert(:noun, %{xiphos})
  insert(:noun, %{yari})
  insert(:noun, %{yoribo})
  insert(:noun, %{zinnor})
  insert(:noun, %{zweihander})

  insert(:name, %{barbed claw$})
  insert(:name, %{bladed claw$})
  insert(:name, %{bladed wheel$})
  insert(:name, %{bo stick$})
  insert(:name, %{carp's tongue$})
  insert(:name, %{cat o' nine tails$})
  insert(:name, %{half moon$})
  insert(:name, %{jo stick$})
  insert(:name, %{mace and chain$})
  insert(:name, %{mining pick$})
  insert(:name, %{sgian achlais$})
  insert(:name, %{sgian dubh$})
  insert(:name, %{throwing disc$})
  insert(:name, %{walking stick$})
end

migrate :pawnshop do
  insert(:noun, %{warlance})
end
