migrate :herb do
  insert(:name, "bunch of acantha leaf")
  insert(:name, "bunch of wolifrew lichen")
  insert(:name, "bunch of torban leaf")
  insert(:name, "bunch of woth flower")
  insert(:name, "bunch of ambrominas leaf")
  insert(:name, "bunch of ephlox moss")
  insert(:name, "bunch of cactacae spine")
  insert(:name, "bunch of calamia fruit")
  insert(:name, "bunch of aloeas stem")
  insert(:name, "bunch of haphip root")
  insert(:name, "bunch of basal moss")
  insert(:name, "bunch of pothinir grass")
  insert(:name, "bunch of sovyn clove")
  insert(:name, "large bolmara potion")
  insert(:name, "large rose-marrow potion")
  insert(:name, "large brostheras potion")
  insert(:name, "large talneo potion")
  insert(:name, "large wingstem potion")
  insert(:name, "large bur-clover potion")
end
