create_table "boon", keys: [:prefix_required, :name, :exclude]

migrate :boon do
  insert(:prefix_required, %{adroit})
  insert(:prefix_required, %{afflicted})
  insert(:prefix_required, %{apt})
  insert(:prefix_required, %{barbed})
  insert(:prefix_required, %{belligerent})
  insert(:prefix_required, %{blurry})
  insert(:prefix_required, %{canny})
  insert(:prefix_required, %{combative})
  insert(:prefix_required, %{dazzling})
  insert(:prefix_required, %{deft})
  insert(:prefix_required, %{drab})
  insert(:prefix_required, %{dreary})
  insert(:prefix_required, %{enraged})
  insert(:prefix_required, %{ethereal})
  insert(:prefix_required, %{flashy})
  insert(:prefix_required, %{flickering})
  insert(:prefix_required, %{flexile})
  insert(:prefix_required, %{flinty})
  insert(:prefix_required, %{frenzied})
  insert(:prefix_required, %{ghastly})
  insert(:prefix_required, %{ghostly})
  insert(:prefix_required, %{gleaming})
  insert(:prefix_required, %{glittering})
  insert(:prefix_required, %{glorious})
  insert(:prefix_required, %{glowing})
  insert(:prefix_required, %{gory})
  insert(:prefix_required, %{grotesque})
  insert(:prefix_required, %{hardy})
  insert(:prefix_required, %{illustrious})
  insert(:prefix_required, %{indistinct})
  insert(:prefix_required, %{keen})
  insert(:prefix_required, %{lanky})
  insert(:prefix_required, %{lustrous})
  insert(:prefix_required, %{muculent})
  insert(:prefix_required, %{nebulous})
  insert(:prefix_required, %{oozing})
  insert(:prefix_required, %{pestilent})
  insert(:prefix_required, %{putrid})
  insert(:prefix_required, %{radiant})
  insert(:prefix_required, %{raging})
  insert(:prefix_required, %{ready})
  insert(:prefix_required, %{resolute})
  insert(:prefix_required, %{rune-covered})
  insert(:prefix_required, %{robust})
  insert(:prefix_required, %{scintillating})
  insert(:prefix_required, %{shadowy})
  insert(:prefix_required, %{shielded})
  insert(:prefix_required, %{shifting})
  insert(:prefix_required, %{shimmering})
  insert(:prefix_required, %{shining})
  insert(:prefix_required, %{sickly green})
  insert(:prefix_required, %{sinuous})
  insert(:prefix_required, %{slime covered})
  insert(:prefix_required, %{slimy})
  insert(:prefix_required, %{sparkling})
  insert(:prefix_required, %{spindly})
  insert(:prefix_required, %{spiny})
  insert(:prefix_required, %{stalwart})
  insert(:prefix_required, %{stately})
  insert(:prefix_required, %{steadfast})
  insert(:prefix_required, %{stout})
  insert(:prefix_required, %{tattooed})
  insert(:prefix_required, %{tenebrous})
  insert(:prefix_required, %{tough})
  insert(:prefix_required, %{twinkling})
  insert(:prefix_required, %{unflinching})
  insert(:prefix_required, %{unyielding})
  insert(:prefix_required, %{wavering})
  insert(:prefix_required, %{wispy})
  insert(:name, %{aivren})
  insert(:name, %{arachne priest})
  insert(:name, %{Arachne priest})
  insert(:name, %{arachne priestess})
  insert(:name, %{Arachne priestess})
  insert(:name, %{ash hag})
  insert(:name, %{black forest ogre})
  insert(:name, %{bog wight})
  insert(:name, %{centaur})
  insert(:name, %{cougar})
  insert(:name, %{crazed zombie})
  insert(:name, %{crested basilisk})
  insert(:name, %{dark vortece})
  insert(:name, %{dhu goleras})
  insert(:name, %{dobrem})
  insert(:name, %{dreadnought raptor})
  insert(:name, %{dybbuk})
  insert(:name, %{ethereal triton sentry})
  insert(:name, %{fenghai})
  insert(:name, %{fire mage})
  insert(:name, %{flesh golem})
  insert(:name, %{frenzied monk})
  insert(:name, %{frozen corpse})
  insert(:name, %{ghostly pooka})
  insert(:name, %{giant albino scorpion})
  insert(:name, %{giant fog beetle})
  insert(:name, %{greater bog troll})
  insert(:name, %{greater construct})
  insert(:name, %{greater faeroth})
  insert(:name, %{hisskra chieftain})
  insert(:name, %{hisskra shaman})
  insert(:name, %{hunch-backed dogmatist})
  insert(:name, %{ice troll})
  insert(:name, %{Illoke elder})
  insert(:name, %{kiramon defender})
  insert(:name, %{kiramon worker})
  insert(:name, %{krolvin corsair})
  insert(:name, %{krolvin warfarer})
  insert(:name, %{krolvin warrior})
  insert(:name, %{lava troll})
  insert(:name, %{lesser faeroth})
  insert(:name, %{lesser griffin})
  insert(:name, %{lesser moor wight})
  insert(:name, %{massive grahnk})
  insert(:name, %{massive pyrothag})
  insert(:name, %{mastodonic leopard})
  insert(:name, %{moor hound})
  insert(:name, %{moor witch})
  insert(:name, %{moulis})
  insert(:name, %{muscular supplicant})
  insert(:name, %{night mare})
  insert(:name, %{raving lunatic})
  insert(:name, %{red tsark})
  insert(:name, %{roa'ter})
  insert(:name, %{rock troll zombie})
  insert(:name, %{rotting woodsman})
  insert(:name, %{sabre-tooth tiger})
  insert(:name, %{siren})
  insert(:name, %{skayl})
  insert(:name, %{skeletal lord})
  insert(:name, %{skeletal warhorse})
  insert(:name, %{spectral miner})
  insert(:name, %{spectral triton defender})
  insert(:name, %{spiked cavern urchin})
  insert(:name, %{stone troll})
  insert(:name, %{tomb troll})
  insert(:name, %{trali shaman})
  insert(:name, %{troll wraith})
  insert(:name, %{vesperti})
  insert(:name, %{Vvrael warlock})
  insert(:name, %{vvrael warlock})
  insert(:name, %{Vvrael witch})
  insert(:name, %{waern})
  insert(:name, %{warrior shade})
  insert(:name, %{wind wraith})
  insert(:name, %{yeti})
  insert(:name, %{zombie})

  insert(:exclude, %{ethereal triton sentry})
  insert(:exclude, %{shadowy spectre})
end

migrate :aggressive_npc do
  insert(:name, %{trali shaman})
end

migrate :aggressive_npc, :undead do
  insert(:prefix, %{adroit})
  insert(:prefix, %{afflicted})
  insert(:prefix, %{apt})
  insert(:prefix, %{barbed})
  insert(:prefix, %{belligerent})
  insert(:prefix, %{blurry})
  insert(:prefix, %{canny})
  insert(:prefix, %{combative})
  insert(:prefix, %{dazzling})
  insert(:prefix, %{deft})
  insert(:prefix, %{drab})
  insert(:prefix, %{dreary})
  insert(:prefix, %{enraged})
  insert(:prefix, %{ethereal})
  insert(:prefix, %{flashy})
  insert(:prefix, %{flickering})
  insert(:prefix, %{flexile})
  insert(:prefix, %{flinty})
  insert(:prefix, %{frenzied})
  insert(:prefix, %{ghastly})
  insert(:prefix, %{ghostly})
  insert(:prefix, %{gleaming})
  insert(:prefix, %{glittering})
  insert(:prefix, %{glorious})
  insert(:prefix, %{glowing})
  insert(:prefix, %{gory})
  insert(:prefix, %{grotesque})
  insert(:prefix, %{hardy})
  insert(:prefix, %{illustrious})
  insert(:prefix, %{indistinct})
  insert(:prefix, %{keen})
  insert(:prefix, %{lanky})
  insert(:prefix, %{lustrous})
  insert(:prefix, %{muculent})
  insert(:prefix, %{nebulous})
  insert(:prefix, %{oozing})
  insert(:prefix, %{pestilent})
  insert(:prefix, %{putrid})
  insert(:prefix, %{radiant})
  insert(:prefix, %{raging})
  insert(:prefix, %{ready})
  insert(:prefix, %{resolute})
  insert(:prefix, %{rune-covered})
  insert(:prefix, %{robust})
  insert(:prefix, %{scintillating})
  insert(:prefix, %{shadowy})
  insert(:prefix, %{shielded})
  insert(:prefix, %{shifting})
  insert(:prefix, %{shimmering})
  insert(:prefix, %{shining})
  insert(:prefix, %{sickly green})
  insert(:prefix, %{sinuous})
  insert(:prefix, %{slime covered})
  insert(:prefix, %{slimy})
  insert(:prefix, %{sparkling})
  insert(:prefix, %{spindly})
  insert(:prefix, %{spiny})
  insert(:prefix, %{stalwart})
  insert(:prefix, %{stately})
  insert(:prefix, %{steadfast})
  insert(:prefix, %{stout})
  insert(:prefix, %{tattooed})
  insert(:prefix, %{tenebrous})
  insert(:prefix, %{tough})
  insert(:prefix, %{twinkling})
  insert(:prefix, %{unflinching})
  insert(:prefix, %{unyielding})
  insert(:prefix, %{wavering})
  insert(:prefix, %{wispy})
end
