create_table "boon", keys: [:prefix_required, :name, :exclude]

migrate :boon do
  insert(:prefix_required, %{adroit})
  insert(:prefix_required, %{afflicted})
  insert(:prefix_required, %{apt})
  insert(:prefix_required, %{barbed})
  insert(:prefix_required, %{belligerent})
  insert(:prefix_required, %{blurry})
  insert(:prefix_required, %{canny})
  insert(:prefix_required, %{dazzling})
  insert(:prefix_required, %{deft})
  insert(:prefix_required, %{dreary})
  insert(:prefix_required, %{ethereal})
  insert(:prefix_required, %{flashy})
  insert(:prefix_required, %{flickering})
  insert(:prefix_required, %{flexile})
  insert(:prefix_required, %{flinty})
  insert(:prefix_required, %{frenzied})
  insert(:prefix_required, %{ghastly})
  insert(:prefix_required, %{ghostly})
  insert(:prefix_required, %{gleaming})
  insert(:prefix_required, %{glittering})
  insert(:prefix_required, %{glorious})
  insert(:prefix_required, %{glowing})
  insert(:prefix_required, %{gory})
  insert(:prefix_required, %{grotesque})
  insert(:prefix_required, %{hardy})
  insert(:prefix_required, %{illustrious})
  insert(:prefix_required, %{indistinct})
  insert(:prefix_required, %{keen})
  insert(:prefix_required, %{lanky})
  insert(:prefix_required, %{lustrous})
  insert(:prefix_required, %{muculent})
  insert(:prefix_required, %{nebulous})
  insert(:prefix_required, %{oozing})
  insert(:prefix_required, %{pestilent})
  insert(:prefix_required, %{putrid})
  insert(:prefix_required, %{radiant})
  insert(:prefix_required, %{raging})
  insert(:prefix_required, %{ready})
  insert(:prefix_required, %{rune-covered})
  insert(:prefix_required, %{robust})
  insert(:prefix_required, %{scintillating})
  insert(:prefix_required, %{shadowy})
  insert(:prefix_required, %{shielded})
  insert(:prefix_required, %{shifting})
  insert(:prefix_required, %{shimmering})
  insert(:prefix_required, %{shining})
  insert(:prefix_required, %{sickly green})
  insert(:prefix_required, %{slime covered})
  insert(:prefix_required, %{slimy})
  insert(:prefix_required, %{sparkling})
  insert(:prefix_required, %{spindly})
  insert(:prefix_required, %{spiny})
  insert(:prefix_required, %{stalwart})
  insert(:prefix_required, %{stately})
  insert(:prefix_required, %{steadfast})
  insert(:prefix_required, %{stout})
  insert(:prefix_required, %{tattooed})
  insert(:prefix_required, %{tenebrous})
  insert(:prefix_required, %{tough})
  insert(:prefix_required, %{twinkling})
  insert(:prefix_required, %{wavering})
  insert(:prefix_required, %{wispy})
  insert(:name, %{black rolton})
  insert(:name, %{black-winged daggerbeak})
  insert(:name, %{carrion worm})
  insert(:name, %{fanged rodent})
  insert(:name, %{fire ant})
  insert(:name, %{giant ant})
  insert(:name, %{giant rat})
  insert(:name, %{kobold})
  insert(:name, %{lesser ghoul})
  insert(:name, %{mountain rolton})
  insert(:name, %{rolton})
  insert(:name, %{skeleton})
  insert(:name, %{slimy little grub})
  insert(:name, %{spotted gnarp})
  insert(:name, %{young grass snake})
  insert(:name, %{zombie rolton})
  insert(:name, %{Mistydeep siren})
  insert(:name, %{big ugly kobold})
  insert(:name, %{brown gak})
  insert(:name, %{cave gnome})
  insert(:name, %{fanged goblin})
  insert(:name, %{ghost})
  insert(:name, %{goblin})
  insert(:name, %{lesser frost shade})
  insert(:name, %{lesser shade})
  insert(:name, %{moaning phantom})
  insert(:name, %{pale crab})
  insert(:name, %{phantom})
  insert(:name, %{rabid squirrel})
  insert(:name, %{sea nymph})
  insert(:name, %{spotted gak})
  insert(:name, %{thyril})
  insert(:name, %{Bresnahanini rolton})
  insert(:name, %{cave gnoll})
  insert(:name, %{cave nipper})
  insert(:name, %{dark vysan})
  insert(:name, %{fire salamander})
  insert(:name, %{greater ghoul})
  insert(:name, %{greater ice spider})
  insert(:name, %{hobgoblin})
  insert(:name, %{ice skeleton})
  insert(:name, %{kobold shepherd})
  insert(:name, %{mountain snowcat})
  insert(:name, %{relnak})
  insert(:name, %{spotted velnalin})
  insert(:name, %{striped gak})
  insert(:name, %{striped relnak})
  insert(:name, %{troglodyte})
  insert(:name, %{velnalin})
  insert(:name, %{white vysan})
  insert(:name, %{black urgh})
  insert(:name, %{cobra})
  insert(:name, %{fanged viper})
  insert(:name, %{mongrel kobold})
  insert(:name, %{revenant})
  insert(:name, %{ridge orc})
  insert(:name, %{spotted leaper})
  insert(:name, %{urgh})
  insert(:name, %{water moccasin})
  insert(:name, %{whiptail})
  insert(:name, %{bobcat})
  insert(:name, %{coyote})
  insert(:name, %{dark apparition})
  insert(:name, %{mist wraith})
  insert(:name, %{mongrel hobgoblin})
  insert(:name, %{night golem})
  insert(:name, %{water witch})
  insert(:name, %{cockatrice})
  insert(:name, %{firephantom})
  insert(:name, %{leaper})
  insert(:name, %{lesser mummy})
  insert(:name, %{lesser orc})
  insert(:name, %{monkey})
  insert(:name, %{snowy cockatrice})
  insert(:name, %{spectral fisherman})
  insert(:name, %{spotted lynx})
  insert(:name, %{blood eagle})
  insert(:name, %{greater kappa})
  insert(:name, %{hobgoblin shaman})
  insert(:name, %{lesser burrow orc})
  insert(:name, %{lesser red orc})
  insert(:name, %{shelfae soldier})
  insert(:name, %{albino tomb spider})
  insert(:name, %{bone golem})
  insert(:name, %{crystal crab})
  insert(:name, %{greater burrow orc})
  insert(:name, %{greater orc})
  insert(:name, %{greater spider})
  insert(:name, %{mottled thrak})
  insert(:name, %{thrak})
  insert(:name, %{brown spinner})
  insert(:name, %{crocodile})
  insert(:name, %{death dirge})
  insert(:name, %{manticore})
  insert(:name, %{snow spectre})
  insert(:name, %{cave worm})
  insert(:name, %{giant marmot})
  insert(:name, %{gnoll worker})
  insert(:name, %{great boar})
  insert(:name, %{rabid guard dog})
  insert(:name, %{raider orc})
  insert(:name, %{werebear})
  insert(:name, %{Neartofar orc})
  insert(:name, %{shelfae chieftain})
  insert(:name, %{wall guardian})
  insert(:name, %{crystal golem})
  insert(:name, %{dark orc})
  insert(:name, %{darkwoode})
  insert(:name, %{deranged sentry})
  insert(:name, %{gnoll thief})
  insert(:name, %{great stag})
  insert(:name, %{plumed cockatrice})
  insert(:name, %{tawny brindlecat})
  insert(:name, %{agresh troll scout})
  insert(:name, %{black boar})
  insert(:name, %{brown boar})
  insert(:name, %{forest troll})
  insert(:name, %{giant weasel})
  insert(:name, %{great brown bear})
  insert(:name, %{grey orc})
  insert(:name, %{silverback orc})
  insert(:name, %{shadowy spectre})
  insert(:name, %{specter})
  insert(:name, %{swamp troll})
  insert(:name, %{arctic puma})
  insert(:name, %{black leopard})
  insert(:name, %{gnoll ranger})
  insert(:name, %{humpbacked puma})
  insert(:name, %{large ogre})
  insert(:name, %{luminous arachnid})
  insert(:name, %{neartofar troll})
  insert(:name, %{panther})
  insert(:name, %{puma})
  insert(:name, %{ridgeback boar})
  insert(:name, %{tomb wight})
  insert(:name, %{wolfshade})
  insert(:name, %{wraith})
  insert(:name, %{agresh bear})
  insert(:name, %{agresh troll warrior})
  insert(:name, %{banded rattlesnake})
  insert(:name, %{black bear})
  insert(:name, %{cave troll})
  insert(:name, %{fire guardian})
  insert(:name, %{fire rat})
  insert(:name, %{ghost wolf})
  insert(:name, %{ghoul master})
  insert(:name, %{hill troll})
  insert(:name, %{mongrel troll})
  insert(:name, %{mongrel wolfhound})
  insert(:name, %{mountain ogre})
  insert(:name, %{phosphorescent worm})
  insert(:name, %{plains orc warrior})
  insert(:name, %{red bear})
  insert(:name, %{wind witch})
  insert(:name, %{black panther})
  insert(:name, %{dark shambler})
  insert(:name, %{forest ogre})
  insert(:name, %{giant veaba})
  insert(:name, %{gnoll guard})
  insert(:name, %{krolvin mercenary})
  insert(:name, %{mountain goat})
  insert(:name, %{mountain troll})
  insert(:name, %{plains ogre})
  insert(:name, %{plains orc scout})
  insert(:name, %{spiked cavern urchin})
  insert(:name, %{bighorn sheep})
  insert(:name, %{cave lizard})
  insert(:name, %{elder ghoul master})
  insert(:name, %{fire cat})
  insert(:name, %{ghostly warrior})
  insert(:name, %{greenwing hornet})
  insert(:name, %{mountain lion})
  insert(:name, %{nedum vereri})
  insert(:name, %{plains lion})
  insert(:name, %{plains orc shaman})
  insert(:name, %{rotting krolvin pirate})
  insert(:name, %{shelfae warlord})
  insert(:name, %{thunder troll})
  insert(:name, %{war troll})
  insert(:name, %{krolvin warrior})
  insert(:name, %{agresh troll chieftain})
  insert(:name, %{arch wight})
  insert(:name, %{gnoll priest})
  insert(:name, %{major spider})
  insert(:name, %{massive grahnk})
  insert(:name, %{ogre warrior})
  insert(:name, %{steel golem})
  insert(:name, %{striped warcat})
  insert(:name, %{wood wight})
  insert(:name, %{ancient ghoul master})
  insert(:name, %{arachne servant})
  insert(:name, %{cave bear})
  insert(:name, %{plains orc chieftain})
  insert(:name, %{cougar})
  insert(:name, %{crested basilisk})
  insert(:name, %{dark panther})
  insert(:name, %{warthog})
  insert(:name, %{arachne acolyte})
  insert(:name, %{centaur ranger})
  insert(:name, %{crazed zombie})
  insert(:name, %{fenghai})
  insert(:name, %{niirsha})
  insert(:name, %{nonomino})
  insert(:name, %{rotting woodsman})
  insert(:name, %{zombie})
  insert(:name, %{arctic wolverine})
  insert(:name, %{burly reiver})
  insert(:name, %{giant albino scorpion})
  insert(:name, %{ice hound})
  insert(:name, %{night hound})
  insert(:name, %{reiver})
  insert(:name, %{roa'ter wormling})
  insert(:name, %{tree viper})
  insert(:name, %{veteran reiver})
  insert(:name, %{wolverine})
  insert(:name, %{carceris})
  insert(:name, %{gnoll jarl})
  insert(:name, %{krolvin warfarer})
  insert(:name, %{sacristan spirit})
  insert(:name, %{spectral monk})
  insert(:name, %{arachne priest})
  insert(:name, %{arachne priestess})
  insert(:name, %{jungle troll})
  insert(:name, %{tree spirit})
  insert(:name, %{grutik savage})
  insert(:name, %{cyclops})
  insert(:name, %{frenzied monk})
  insert(:name, %{lesser stone gargoyle})
  insert(:name, %{monastic lich})
  insert(:name, %{snow leopard})
  insert(:name, %{troll chieftain})
  insert(:name, %{darken})
  insert(:name, %{dobrem})
  insert(:name, %{fire ogre})
  insert(:name, %{giant hawk-owl})
  insert(:name, %{ki-lin})
  insert(:name, %{martial eagle})
  insert(:name, %{moaning spirit})
  insert(:name, %{grutik shaman})
  insert(:name, %{arctic manticore})
  insert(:name, %{ice troll})
  insert(:name, %{pra'eda})
  insert(:name, %{scaly burgee})
  insert(:name, %{elder tree spirit})
  insert(:name, %{giant albino tomb spider})
  insert(:name, %{hisskra warrior})
  insert(:name, %{hooded figure})
  insert(:name, %{hunter troll})
  insert(:name, %{jungle troll chieftain})
  insert(:name, %{lesser wood sprite})
  insert(:name, %{mammoth arachnid})
  insert(:name, %{tegursh sentry})
  insert(:name, %{ash hag})
  insert(:name, %{krynch})
  insert(:name, %{skeletal ice troll})
  insert(:name, %{wild hound})
  insert(:name, %{caribou})
  insert(:name, %{ghostly mara})
  insert(:name, %{giant fog beetle})
  insert(:name, %{rotting corpse})
  insert(:name, %{rotting farmhand})
  insert(:name, %{ghostly pooka})
  insert(:name, %{hisskra shaman})
  insert(:name, %{maw spore})
  insert(:name, %{mezic})
  insert(:name, %{moor hound})
  insert(:name, %{sand beetle})
  insert(:name, %{skeletal giant})
  insert(:name, %{three-toed tegu})
  insert(:name, %{cold guardian})
  insert(:name, %{colossus vulture})
  insert(:name, %{hisskra chieftain})
  insert(:name, %{lava troll})
  insert(:name, %{moor witch})
  insert(:name, %{rock troll zombie})
  insert(:name, %{skeletal soldier})
  insert(:name, %{spectral warrior})
  insert(:name, %{tundra giant})
  insert(:name, %{barghest})
  insert(:name, %{bog troll})
  insert(:name, %{moor eagle})
  insert(:name, %{shimmering fungus})
  insert(:name, %{spectral shade})
  insert(:name, %{spectral woodsman})
  insert(:name, %{troll wraith})
  insert(:name, %{water wyrd})
  insert(:name, %{arctic titan})
  insert(:name, %{dust beetle})
  insert(:name, %{fire giant})
  insert(:name, %{krolvin slaver})
  insert(:name, %{snow crone})
  insert(:name, %{spectral lord})
  insert(:name, %{undertaker bat})
  insert(:name, %{Sheruvian initiate})
  insert(:name, %{huge mein golem})
  insert(:name, %{lesser moor wight})
  insert(:name, %{magru})
  insert(:name, %{shadow mare})
  insert(:name, %{skeletal warhorse})
  insert(:name, %{tusked ursian})
  insert(:name, %{frost giant})
  insert(:name, %{grizzly bear})
  insert(:name, %{krolvin corsair})
  insert(:name, %{mud wasp})
  insert(:name, %{shadow steed})
  insert(:name, %{vesperti})
  insert(:name, %{wood sprite})
  insert(:name, %{greater bog troll})
  insert(:name, %{greater moor wight})
  insert(:name, %{stone gargoyle})
  insert(:name, %{storm giant})
  insert(:name, %{vourkha})
  insert(:name, %{forest bendith})
  insert(:name, %{kiramon worker})
  insert(:name, %{red myklian})
  insert(:name, %{yellow myklian})
  insert(:name, %{green myklian})
  insert(:name, %{blue myklian})
  insert(:name, %{orange myklian})
  insert(:name, %{purple myklian})
  insert(:name, %{young myklian})
  insert(:name, %{spectral miner})
  insert(:name, %{Sheruvian monk})
  insert(:name, %{bog wraith})
  insert(:name, %{lesser ice giant})
  insert(:name, %{roa'ter})
  insert(:name, %{skeletal lord})
  insert(:name, %{baesrukha})
  insert(:name, %{dark vortece})
  insert(:name, %{frozen corpse})
  insert(:name, %{minor glacei})
  insert(:name, %{phantasma})
  insert(:name, %{shan cleric})
  insert(:name, %{shan ranger})
  insert(:name, %{shan warrior})
  insert(:name, %{shan wizard})
  insert(:name, %{siren lizard})
  insert(:name, %{swamp hag})
  insert(:name, %{dreadnought raptor})
  insert(:name, %{night mare})
  insert(:name, %{wasp nest})
  insert(:name, %{bog wight})
  insert(:name, %{firethorn shoot})
  insert(:name, %{forest trali shaman})
  insert(:name, %{gaunt spectral servant})
  insert(:name, %{mastodonic leopard})
  insert(:name, %{polar bear})
  insert(:name, %{ice wraith})
  insert(:name, %{lesser vruul})
  insert(:name, %{cinder wasp})
  insert(:name, %{forest trali})
  insert(:name, %{greater ice giant})
  insert(:name, %{kiramon defender})
  insert(:name, %{lesser faeroth})
  insert(:name, %{rotting chimera})
  insert(:name, %{bog spectre})
  insert(:name, %{major glacei})
  insert(:name, %{dybbuk})
  insert(:name, %{horned vor'taz})
  insert(:name, %{red-scaled thrak})
  insert(:name, %{sand devil})
  insert(:name, %{warrior shade})
  insert(:name, %{waern})
  insert(:name, %{banshee})
  insert(:name, %{flesh golem})
  insert(:name, %{greater faeroth})
  insert(:name, %{seeker})
  insert(:name, %{snow madrinol})
  insert(:name, %{tomb troll})
  insert(:name, %{wooly mammoth})
  insert(:name, %{ice golem})
  insert(:name, %{lesser ice elemental})
  insert(:name, %{sabre-tooth tiger})
  insert(:name, %{stone sentinel})
  insert(:name, %{animated slush})
  insert(:name, %{ethereal mage apprentice})
  insert(:name, %{skayl})
  insert(:name, %{tomb troll necromancer})
  insert(:name, %{eidolon})
  insert(:name, %{nightmare steed})
  insert(:name, %{stone troll})
  insert(:name, %{decaying Citadel guardsman})
  insert(:name, %{glacial morph})
  insert(:name, %{lava golem})
  insert(:name, %{massive pyrothag})
  insert(:name, %{rotting Citadel arbalester})
  insert(:name, %{stone giant})
  insert(:name, %{black forest viper})
  insert(:name, %{massive black boar})
  insert(:name, %{black forest ogre})
  insert(:name, %{putrefied Citadel herald})
  insert(:name, %{wind wraith})
  insert(:name, %{Illoke mystic})
  insert(:name, %{phantasmal bestial swordsman})
  insert(:name, %{stone mastiff})
  insert(:name, %{Sheruvian harbinger})
  insert(:name, %{massive troll king})
  insert(:name, %{soul golem})
  insert(:name, %{fire sprite})
  insert(:name, %{grifflet})
  insert(:name, %{emaciated hierophant})
  insert(:name, %{red tsark})
  insert(:name, %{Illoke shaman})
  insert(:name, %{muscular supplicant})
  insert(:name, %{yeti})
  insert(:name, %{lesser griffin})
  insert(:name, %{hunch-backed dogmatist})
  insert(:name, %{krag yeti})
  insert(:name, %{fire mage})
  insert(:name, %{krag dweller})
  insert(:name, %{storm griffin})
  insert(:name, %{lesser minotaur})
  insert(:name, %{greater vruul})
  insert(:name, %{moulis})
  insert(:name, %{naisirc})
  insert(:name, %{minotaur warrior})
  insert(:name, %{shrickhen})
  insert(:name, %{farlook})
  insert(:name, %{raving lunatic})
  insert(:name, %{dhu goleras})
  insert(:name, %{minotaur magi})
  insert(:name, %{seraceris})
  insert(:name, %{Vvrael witch})
  insert(:name, %{Csetairi})
  insert(:name, %{caedera})
  insert(:name, %{gnarled being})
  insert(:name, %{bent being})
  insert(:name, %{stooped being})
  insert(:name, %{twisted being})
  insert(:name, %{lesser construct})
  insert(:name, %{Vvrael warlock})
  insert(:name, %{greater krynch})
  insert(:name, %{gremlock})
  insert(:name, %{lich qyn'arj})
  insert(:name, %{Illoke elder})
  insert(:name, %{aivren})
  insert(:name, %{festering taint})
  insert(:name, %{n'ecare})
  insert(:name, %{greater earth elemental})
  insert(:name, %{Illoke jarl})
  insert(:name, %{Ithzir scout})
  insert(:name, %{Ithzir initiate})
  insert(:name, %{lost soul})
  insert(:name, %{Ithzir janissary})
  insert(:name, %{Ithzir herald})
  insert(:name, %{vaespilon})
  insert(:name, %{triton dissembler})
  insert(:name, %{Ithzir adept})
  insert(:name, %{greater construct})
  insert(:name, %{siren})
  insert(:name, %{triton executioner})
  insert(:name, %{fallen crusader})
  insert(:name, %{Ithzir seer})
  insert(:name, %{spectral triton defender})
  insert(:name, %{triton combatant})
  insert(:name, %{glistening cerebralite})
  insert(:name, %{triton radical})
  insert(:name, %{war griffin})
  insert(:name, %{triton magus})
  insert(:name, %{enormous rift crawler})
  insert(:name, %{ethereal triton sentry})
  insert(:name, %{darkly inked fetish master})
  insert(:name, %{greater water elemental})
  insert(:name, %{csetairi})
  insert(:name, %{Vvrael destroyer})
  insert(:name, %{soul siphon})
  insert(:name, %{wizened orc hag})
  insert(:name, %{colossal titan})
  insert(:name, %{ravenous krolvin berserker})
  insert(:name, %{gnoll miner})
  insert(:name, %{vvrael warlock})
  insert(:name, %{monstrous crimson worm})
  insert(:name, %{chieftain})
  insert(:name, %{triton sentry})
  insert(:name, %{triton defender})
  insert(:name, %{minotaur magus})
  insert(:name, %{moulis stalk})
  insert(:name, %{hanging tree viper})
  insert(:name, %{nasty little red gremlin})
  insert(:name, %{nasty little yellow gremlin})
  insert(:name, %{nasty little green gremlin})
  insert(:name, %{nasty little orange gremlin})
  insert(:name, %{nasty little black gremlin})
  insert(:name, %{nasty little blue gremlin})
  insert(:name, %{white centaur})
  insert(:name, %{black centaur})
  insert(:name, %{tan centaur})
  insert(:name, %{roan centaur})
  insert(:name, %{centaur})
  insert(:name, %{fire elemental})
  insert(:name, %{lightning elemental})
  insert(:name, %{lava elemental})
  insert(:name, %{steam elemental})
  insert(:name, %{air elemental})
  insert(:name, %{ice elemental})
  insert(:name, %{water elemental})
  insert(:name, %{earth elemental})
  insert(:name, %{winged viper})
  insert(:name, %{Illvari pixie})
  insert(:name, %{Illvari sprite})
  insert(:name, %{direbear})
  insert(:name, %{monstrous direwolf})
  insert(:name, %{warped tree spirit})
  insert(:name, %{treekin warrior})
  insert(:name, %{treekin druid})
  insert(:name, %{treekin sapling})
  insert(:name, %{bay centaur})
  insert(:name, %{Ithzir champion})
  insert(:name, %{blackened decaying tumbleweed})
  insert(:name, %{dark frosty plant})
  insert(:name, %{large thorned shrub})
  insert(:name, %{shriveled icy creeper})
  insert(:name, %{writhing frost-glazed vine})
  insert(:name, %{writhing icy bush})
  insert(:name, %{Agresh bear})
  insert(:name, %{Agresh troll chieftain})
  insert(:name, %{Agresh troll scout})
  insert(:name, %{Agresh troll warrior})
  insert(:name, %{Arachne acolyte})
  insert(:name, %{Arachne priest})
  insert(:name, %{Arachne priestess})
  insert(:name, %{Arachne servant})
  insert(:name, %{frostborne lich})
  insert(:name, %{Grutik savage})
  insert(:name, %{Grutik shaman})
  insert(:name, %{infernal lich})
  insert(:name, %{murky soul siphon})
  insert(:name, %{Neartofar troll})
  insert(:name, %{necrotic snake})
  insert(:name, %{spectre})
  insert(:name, %{wild dog})
  insert(:name, %{lithe veiled sentinel})
  insert(:name, %{pale scaled shaper})
  insert(:name, %{deathsworn fanatic})
  insert(:name, %{white sidewinder})
  insert(:name, %{shambling lurk})
  insert(:name, %{patchwork flesh monstrosity})

  insert(:exclude, %{ethereal triton sentry})
  insert(:exclude, %{shadowy spectre})
end

migrate :aggressive_npc, :undead do
  insert(:prefix, %{adroit})
  insert(:prefix, %{afflicted})
  insert(:prefix, %{apt})
  insert(:prefix, %{barbed})
  insert(:prefix, %{belligerent})
  insert(:prefix, %{blurry})
  insert(:prefix, %{canny})
  insert(:prefix, %{dazzling})
  insert(:prefix, %{deft})
  insert(:prefix, %{dreary})
  insert(:prefix, %{ethereal})
  insert(:prefix, %{flashy})
  insert(:prefix, %{flickering})
  insert(:prefix, %{flexile})
  insert(:prefix, %{flinty})
  insert(:prefix, %{frenzied})
  insert(:prefix, %{ghastly})
  insert(:prefix, %{ghostly})
  insert(:prefix, %{gleaming})
  insert(:prefix, %{glittering})
  insert(:prefix, %{glorious})
  insert(:prefix, %{glowing})
  insert(:prefix, %{gory})
  insert(:prefix, %{grotesque})
  insert(:prefix, %{hardy})
  insert(:prefix, %{illustrious})
  insert(:prefix, %{indistinct})
  insert(:prefix, %{keen})
  insert(:prefix, %{lanky})
  insert(:prefix, %{lustrous})
  insert(:prefix, %{muculent})
  insert(:prefix, %{nebulous})
  insert(:prefix, %{oozing})
  insert(:prefix, %{pestilent})
  insert(:prefix, %{putrid})
  insert(:prefix, %{radiant})
  insert(:prefix, %{raging})
  insert(:prefix, %{ready})
  insert(:prefix, %{rune-covered})
  insert(:prefix, %{robust})
  insert(:prefix, %{scintillating})
  insert(:prefix, %{shadowy})
  insert(:prefix, %{shielded})
  insert(:prefix, %{shifting})
  insert(:prefix, %{shimmering})
  insert(:prefix, %{shining})
  insert(:prefix, %{sickly green})
  insert(:prefix, %{slime covered})
  insert(:prefix, %{slimy})
  insert(:prefix, %{sparkling})
  insert(:prefix, %{spindly})
  insert(:prefix, %{spiny})
  insert(:prefix, %{stalwart})
  insert(:prefix, %{stately})
  insert(:prefix, %{steadfast})
  insert(:prefix, %{stout})
  insert(:prefix, %{tattooed})
  insert(:prefix, %{tenebrous})
  insert(:prefix, %{tough})
  insert(:prefix, %{twinkling})
  insert(:prefix, %{wavering})
  insert(:prefix, %{wispy})
end
