create_table "manna_bread", keys: [:name]

migrate :manna_bread do
  insert(:name, %{some manna bread},)
  insert(:name, %{round of ground acorn bread})
  insert(:name, %{tiered honey-infused flatbread})
  insert(:name, %{cherry-filled loaf of dark bread})
  insert(:name, %{some baked thyme-dusted flatbread})
  insert(:name, %{dense wheat cracker studded with wheatberries})
  insert(:name, %{black buckwheat cracker})
  insert(:name, %{crispy rye cracker sprinkled with caraway seeds})
  insert(:name, %{flaky salted cracker dotted with tiny holes})
  insert(:name, %{nutty wheat cracker})
  insert(:name, %{some scored peppercorn flatbread})
  insert(:name, %{airy pale-colored teacake})
  insert(:name, %{stack of dark-swirled rye crisps})
  insert(:name, %{disk of black olive-laden bread})
  insert(:name, %{mushroom and potato cake})
  insert(:name, %{loaf of dark crusty ale bread})
  insert(:name, %{thick disk of golden dwarf bread})
  insert(:name, %{thin wafer of crispy elven waybread})
  insert(:name, %{small cake of golden elven waybread})
  insert(:name, %{some golden brown elven waybread})
  insert(:name, %{lemongrass biscuit})
  insert(:name, %{some unleavened rose-infused rice bread})
  insert(:name, %{petal-wrapped oatcake})
  insert(:name, %{garlic-laced sweet corn cake})
  insert(:name, %{toasted squash blossom fritter})
  insert(:name, %{sweet pineapple-glazed pumpkin loaf})
  insert(:name, %{cheese-filled manioc ball})
  insert(:name, %{braid of cracked wheat bread})
  insert(:name, %{sugar-dusted travel biscuit})
  insert(:name, %{filled piece of bread})
  insert(:name, %{thick piece of sea biscuit})
  insert(:name, %{greasy seal meat and oat bread})
  insert(:name, %{greasy willow paste bread})
  insert(:name, %{reddish cream-filled tart})
  insert(:name, %{brownish cream-filled tart})
  insert(:name, %{spinach-paste steamed dumpling})
  insert(:name, %{oblong fried dumpling})
  insert(:name, %{sugared barley and oat cake})
  insert(:name, %{sundried tomato and garlic loaf})
  insert(:name, %{onion and garlic-stuffed bread})
  insert(:name, %{thin crisp of hummus-topped bread})
  insert(:name, %{swirled disk of blue and yellow ground cornmeal})
  insert(:name, %{small wild rice and millet cake laced with maple syrup},%{dark orc})
  insert(:name, %{round of fried dough branded with a charred design})
  insert(:name, %{wafer of candied seeds})
  insert(:name, %{slice of banana walnut bread})
  insert(:name, %{square of tart lemon cake})
  insert(:name, %{wedge of anise and wheat flatbread})
  insert(:name, %{round of garlic-rubbed bread})
  insert(:name, %{pancake of crispy cornbread})
  insert(:name, %{mini loaf of yellow cornbread})
  insert(:name, %{grilled flour flatbread drizzled with chile oil})
  insert(:name, %{flaky salted cracker dotted with tiny holes})
  insert(:name, %{crispy rye cracker sprinkled with caraway seeds})
  insert(:name, %{chewy dark brown hermit bar})
  insert(:name, %{pumpkin spice muffin})
  insert(:name, %{sugar-dusted golden doughnut})
  insert(:name, %{honey-laced golden spongecake})
end
