migrate :aggressive_npc do
  insert(:name, %{battle-scarred hulking krolvin warden})
  insert(:name, %{battle-scarred krolvin triggerman})
  insert(:name, %{battle-scarred krolvin warden})
  insert(:name, %{dwarven pillager})
  insert(:name, %{dwarven pirate})
  insert(:name, %{dwarven raider})
  insert(:name, %{dwarven scout})
  insert(:name, %{elven pillager})
  insert(:name, %{elven pirate})
  insert(:name, %{elven raider})
  insert(:name, %{elven scout})
  insert(:name, %{elven waylayer})
  insert(:name, %{erithian pillager})
  insert(:name, %{erithian pirate})
  insert(:name, %{erithian raider})
  insert(:name, %{erithian waylayer})
  insert(:name, %{giantman pillager})
  insert(:name, %{giantman pirate})
  insert(:name, %{giantman raider})
  insert(:name, %{giantman scout})
  insert(:name, %{giantman waylayer})
  insert(:name, %{gnomish pillager})
  insert(:name, %{gnomish pirate})
  insert(:name, %{gnomish raider})
  insert(:name, %{gnomish scout})
  insert(:name, %{gnomish waylayer})
  insert(:name, %{grizzled hulking krolvin huntmaster})
  insert(:name, %{grizzled hulking krolvin triggerman})
  insert(:name, %{grizzled hulking krolvin warden})
  insert(:name, %{grizzled krolvin huntmaster})
  insert(:name, %{grizzled krolvin warden})
  insert(:name, %{half-elven pillager})
  insert(:name, %{half-elven pirate})
  insert(:name, %{half-elven raider})
  insert(:name, %{half-elven scout})
  insert(:name, %{half-elven waylayer})
  insert(:name, %{half-krolvin pillager})
  insert(:name, %{half-krolvin pirate})
  insert(:name, %{half-krolvin raider})
  insert(:name, %{half-krolvin scout})
  insert(:name, %{half-krolvin waylayer})
  insert(:name, %{halfling pillager})
  insert(:name, %{halfling pirate})
  insert(:name, %{halfling raider})
  insert(:name, %{halfling scout})
  insert(:name, %{halfling waylayer})
  insert(:name, %{hulking krolvin archmage})
  insert(:name, %{hulking krolvin destroyer})
  insert(:name, %{hulking krolvin obliterator})
  insert(:name, %{hulking krolvin paragon})
  insert(:name, %{hulking krolvin scout})
  insert(:name, %{hulking krolvin templar})
  insert(:name, %{hulking krolvin tormentor})
  insert(:name, %{hulking krolvin triggerman})
  insert(:name, %{hulking krolvin warlord})
  insert(:name, %{human pillager})
  insert(:name, %{human pirate})
  insert(:name, %{human raider})
  insert(:name, %{human scout})
  insert(:name, %{human waylayer})
  insert(:name, %{menacing krolvin archmage})
  insert(:name, %{menacing krolvin destroyer})
  insert(:name, %{menacing krolvin obliterator})
  insert(:name, %{menacing krolvin paragon})
  insert(:name, %{menacing krolvin templar})
  insert(:name, %{menacing krolvin tormentor})
  insert(:name, %{menacing krolvin triggerman})
  insert(:name, %{menacing krolvin warlord})
  insert(:name, %{seasoned hulking krolvin warden})
  insert(:name, %{seasoned krolvin destroyer})
  insert(:name, %{seasoned krolvin warden})
  insert(:name, %{The Ethereal Captain})
  insert(:name, %{The Krolvin Captain})
  insert(:name, %{The Pirate Captain})
  insert(:name, %{towering krolvin archmage})
  insert(:name, %{towering krolvin blackguard})
  insert(:name, %{towering krolvin destroyer})
  insert(:name, %{towering krolvin huntmaster})
  insert(:name, %{towering krolvin obliterator})
  insert(:name, %{towering krolvin paragon})
  insert(:name, %{towering krolvin scout})
  insert(:name, %{towering krolvin templar})
  insert(:name, %{towering krolvin tormentor})
  insert(:name, %{towering krolvin triggerman})
  insert(:name, %{towering krolvin warlord})
  insert(:name, %{unworldly brigand})
  insert(:name, %{unworldly pirate})
  insert(:name, %{weathered hulking krolvin archmage})
  insert(:name, %{weathered hulking krolvin destroyer})
  insert(:name, %{weathered hulking krolvin warden})
  insert(:name, %{crazed canine})
  insert(:name, %{ebon swine})
  insert(:name, %{hobgoblin acolyte})
  insert(:name, %{imposing elk})
  insert(:name, %{luminous worm})
  insert(:name, %{muddy hog})
  insert(:name, %{muscular brindlecat})
  insert(:name, %{shelfae assailant})
  insert(:name, %{shelfae guard})
  insert(:name, %{speckled cave lizard})
  insert(:name, %{spectacled bear})
end

migrate :undead, :aggressive_npc do
  insert(:name, %{ethereal brigand})
  insert(:name, %{ethereal pirate})
  insert(:name, %{ghostly giantman pirate})
  insert(:name, %{ghostly giantman raider})
  insert(:name, %{ghostly half-elven pirate})
  insert(:name, %{ghostly half-elven scout})
  insert(:name, %{ghostly half-elven waylayer})
  insert(:name, %{ghostly half-krolvin scout})
  insert(:name, %{ghostly human pillager})
end
