#OSA Mobs
migrate :aggressive_npc do
  insert(:name, %{battle-scarred hulking krolvin champion})
  insert(:name, %{battle-scarred hulking krolvin destroyer})
  insert(:name, %{battle-scarred hulking krolvin huntmistress})
  insert(:name, %{battle-scarred hulking krolvin warden})
  insert(:name, %{battle-scarred hulking krolvin warlord})
  insert(:name, %{battle-scarred krolvin assassin})
  insert(:name, %{battle-scarred krolvin battlemaster})
  insert(:name, %{battle-scarred krolvin blackguard})
  insert(:name, %{battle-scarred krolvin challenger})
  insert(:name, %{battle-scarred krolvin champion})
  insert(:name, %{battle-scarred krolvin defiler})
  insert(:name, %{battle-scarred krolvin huntmaster})
  insert(:name, %{battle-scarred krolvin huntmistress})
  insert(:name, %{battle-scarred krolvin invoker})
  insert(:name, %{battle-scarred krolvin justicar})
  insert(:name, %{battle-scarred krolvin marksman})
  insert(:name, %{battle-scarred krolvin scout})
  insert(:name, %{battle-scarred krolvin triggerman})
  insert(:name, %{battle-scarred krolvin warden})
  insert(:name, %{battle-scarred krolvin warlord})
  insert(:name, %{battle-scarred krolvin warmage})
  insert(:name, %{battle-scarred krolvin watcher})
  insert(:name, %{dwarven pillager})
  insert(:name, %{dwarven pirate})
  insert(:name, %{dwarven raider})
  insert(:name, %{dwarven scout})
  insert(:name, %{dwarven waylayer})
  insert(:name, %{elven pillager})
  insert(:name, %{elven pirate})
  insert(:name, %{elven raider})
  insert(:name, %{elven scout})
  insert(:name, %{elven waylayer})
  insert(:name, %{erithian pillager})
  insert(:name, %{erithian pirate})
  insert(:name, %{erithian raider})
  insert(:name, %{erithian scout})
  insert(:name, %{erithian waylayer})
  insert(:name, %{fierce krolvin assassin})
  insert(:name, %{fierce krolvin battlemaster})
  insert(:name, %{fierce krolvin challenger})
  insert(:name, %{fierce krolvin defiler})
  insert(:name, %{fierce krolvin huntmaster})
  insert(:name, %{fierce krolvin huntmistress})
  insert(:name, %{fierce krolvin invoker})
  insert(:name, %{fierce krolvin justicar})
  insert(:name, %{fierce krolvin marksman})
  insert(:name, %{fierce krolvin scout})
  insert(:name, %{fierce krolvin warmage})
  insert(:name, %{fierce krolvin watcher})
  insert(:name, %{frenzied krolvin assassin})
  insert(:name, %{frenzied krolvin battlemaster})
  insert(:name, %{frenzied krolvin challenger})
  insert(:name, %{frenzied krolvin defiler})
  insert(:name, %{frenzied krolvin huntmaster})
  insert(:name, %{frenzied krolvin huntmistress})
  insert(:name, %{frenzied krolvin invoker})
  insert(:name, %{frenzied krolvin justicar})
  insert(:name, %{frenzied krolvin marksman})
  insert(:name, %{frenzied krolvin scout})
  insert(:name, %{frenzied krolvin warmage})
  insert(:name, %{frenzied krolvin watcher})
  insert(:name, %{giantman pillager})
  insert(:name, %{giantman pirate})
  insert(:name, %{giantman raider})
  insert(:name, %{giantman scout})
  insert(:name, %{giantman waylayer})
  insert(:name, %{gnomish pillager})
  insert(:name, %{gnomish pirate})
  insert(:name, %{gnomish raider})
  insert(:name, %{gnomish scout})
  insert(:name, %{gnomish waylayer})
  insert(:name, %{grizzled hulking krolvin huntmaster})
  insert(:name, %{grizzled hulking krolvin obliterator})
  insert(:name, %{grizzled hulking krolvin triggerman})
  insert(:name, %{grizzled hulking krolvin warden})
  insert(:name, %{grizzled krolvin archmage})
  insert(:name, %{grizzled krolvin assassin})
  insert(:name, %{grizzled krolvin battlemaster})
  insert(:name, %{grizzled krolvin challenger})
  insert(:name, %{grizzled krolvin defiler})
  insert(:name, %{grizzled krolvin huntmaster})
  insert(:name, %{grizzled krolvin huntmistress})
  insert(:name, %{grizzled krolvin invoker})
  insert(:name, %{grizzled krolvin justicar})
  insert(:name, %{grizzled krolvin marksman})
  insert(:name, %{grizzled krolvin obliterator})
  insert(:name, %{grizzled krolvin scout})
  insert(:name, %{grizzled krolvin warden})
  insert(:name, %{grizzled krolvin warmage})
  insert(:name, %{grizzled krolvin watcher})
  insert(:name, %{half-elven pillager})
  insert(:name, %{half-elven pirate})
  insert(:name, %{half-elven raider})
  insert(:name, %{half-elven scout})
  insert(:name, %{half-elven waylayer})
  insert(:name, %{half-krolvin pillager})
  insert(:name, %{half-krolvin pirate})
  insert(:name, %{half-krolvin raider})
  insert(:name, %{half-krolvin scout})
  insert(:name, %{half-krolvin waylayer})
  insert(:name, %{halfling pillager})
  insert(:name, %{halfling pirate})
  insert(:name, %{halfling raider})
  insert(:name, %{halfling scout})
  insert(:name, %{halfling waylayer})
  insert(:name, %{hulking krolvin archmage})
  insert(:name, %{hulking krolvin destroyer})
  insert(:name, %{hulking krolvin obliterator})
  insert(:name, %{hulking krolvin paragon})
  insert(:name, %{hulking krolvin scout})
  insert(:name, %{hulking krolvin templar})
  insert(:name, %{hulking krolvin tormentor})
  insert(:name, %{hulking krolvin triggerman})
  insert(:name, %{hulking krolvin warlord})
  insert(:name, %{human pillager})
  insert(:name, %{human pirate})
  insert(:name, %{human raider})
  insert(:name, %{human scout})
  insert(:name, %{human waylayer})
  insert(:name, %{massive krolvin battlechanter})
  insert(:name, %{massive krolvin harrower})
  insert(:name, %{massive krolvin huntmaster})
  insert(:name, %{massive krolvin huntmistress})
  insert(:name, %{massive krolvin plaguebringer})
  insert(:name, %{massive krolvin precept})
  insert(:name, %{massive krolvin rover})
  insert(:name, %{massive krolvin scout})
  insert(:name, %{massive krolvin sharpshooter})
  insert(:name, %{massive krolvin soldier})
  insert(:name, %{massive krolvin warbringer}) 
  insert(:name, %{menacing krolvin archmage})
  insert(:name, %{menacing krolvin destroyer})
  insert(:name, %{menacing krolvin huntmaster})
  insert(:name, %{menacing krolvin huntmistress})
  insert(:name, %{menacing krolvin obliterator})
  insert(:name, %{menacing krolvin paragon})
  insert(:name, %{menacing krolvin scout})
  insert(:name, %{menacing krolvin templar})
  insert(:name, %{menacing krolvin tormentor})
  insert(:name, %{menacing krolvin triggerman})
  insert(:name, %{menacing krolvin warlord})
  insert(:name, %{raging krolvin battlechanter})
  insert(:name, %{raging krolvin harrower})
  insert(:name, %{raging krolvin huntmaster})
  insert(:name, %{raging krolvin huntmistress})
  insert(:name, %{raging krolvin plaguebringer})
  insert(:name, %{raging krolvin precept})
  insert(:name, %{raging krolvin rover})
  insert(:name, %{raging krolvin scout})
  insert(:name, %{raging krolvin sharpshooter})
  insert(:name, %{raging krolvin soldier})
  insert(:name, %{raging krolvin warbringer})
  insert(:name, %{repulsive krolvin assassin})
  insert(:name, %{repulsive krolvin battlemaster})
  insert(:name, %{repulsive krolvin challenger})
  insert(:name, %{repulsive krolvin defiler})
  insert(:name, %{repulsive krolvin huntmaster})
  insert(:name, %{repulsive krolvin huntmistress})
  insert(:name, %{repulsive krolvin invoker})
  insert(:name, %{repulsive krolvin justicar})
  insert(:name, %{repulsive krolvin marksman})
  insert(:name, %{repulsive krolvin scout})
  insert(:name, %{repulsive krolvin warmage})
  insert(:name, %{repulsive krolvin watcher})
  insert(:name, %{seasoned hulking krolvin triggerman})
  insert(:name, %{seasoned hulking krolvin warden})
  insert(:name, %{seasoned krolvin assassin})
  insert(:name, %{seasoned krolvin battlemaster})
  insert(:name, %{seasoned krolvin challenger})
  insert(:name, %{seasoned krolvin defiler})
  insert(:name, %{seasoned krolvin destroyer})
  insert(:name, %{seasoned krolvin huntmaster})
  insert(:name, %{seasoned krolvin huntmistress})
  insert(:name, %{seasoned krolvin invoker})
  insert(:name, %{seasoned krolvin justicar})
  insert(:name, %{seasoned krolvin marksman})
  insert(:name, %{seasoned krolvin paragon})
  insert(:name, %{seasoned krolvin scout})
  insert(:name, %{seasoned krolvin templar})
  insert(:name, %{seasoned krolvin warden})
  insert(:name, %{seasoned krolvin warmage})
  insert(:name, %{seasoned krolvin watcher})
  insert(:name, %{The Krolvin Captain})
  insert(:name, %{The Pirate Captain})
  insert(:name, %{towering krolvin archmage})
  insert(:name, %{towering krolvin blackguard})
  insert(:name, %{towering krolvin destroyer})
  insert(:name, %{towering krolvin huntmaster})
  insert(:name, %{towering krolvin obliterator})
  insert(:name, %{towering krolvin paragon})
  insert(:name, %{towering krolvin scout})
  insert(:name, %{towering krolvin templar})
  insert(:name, %{towering krolvin tormentor})
  insert(:name, %{towering krolvin triggerman})
  insert(:name, %{towering krolvin warlord})
  insert(:name, %{vile krolvin battlechanter})
  insert(:name, %{vile krolvin harrower})
  insert(:name, %{vile krolvin huntmaster})
  insert(:name, %{vile krolvin huntmistress})
  insert(:name, %{vile krolvin plaguebringer})
  insert(:name, %{vile krolvin precept})
  insert(:name, %{vile krolvin rover})
  insert(:name, %{vile krolvin scout})
  insert(:name, %{vile krolvin sharpshooter})
  insert(:name, %{vile krolvin soldier})
  insert(:name, %{vile krolvin warbringer})
  insert(:name, %{weathered hulking krolvin archmage})
  insert(:name, %{weathered hulking krolvin destroyer})
  insert(:name, %{weathered hulking krolvin huntmistress})
  insert(:name, %{weathered hulking krolvin warden})
  insert(:name, %{weathered krolvin archmage})
  insert(:name, %{weathered krolvin assassin})
  insert(:name, %{weathered krolvin battlemaster})
  insert(:name, %{weathered krolvin challenger})
  insert(:name, %{weathered krolvin defiler})
  insert(:name, %{weathered krolvin huntmaster})
  insert(:name, %{weathered krolvin huntmaster})
  insert(:name, %{weathered krolvin huntmistress})
  insert(:name, %{weathered krolvin invoker})
  insert(:name, %{weathered krolvin justicar})
  insert(:name, %{weathered krolvin marksman})
  insert(:name, %{weathered krolvin scout})
  insert(:name, %{weathered krolvin templar})
  insert(:name, %{weathered krolvin warden})
  insert(:name, %{weathered krolvin warmage})
  insert(:name, %{weathered krolvin watcher})
end

migrate :undead, :aggressive_npc do
  insert(:name, %{ethereal brigand})
  insert(:name, %{ethereal pirate})
  insert(:name, %{ghostly giantman pirate})
  insert(:name, %{ghostly giantman raider})
  insert(:name, %{ghostly half-elven pirate})
  insert(:name, %{ghostly half-elven scout})
  insert(:name, %{ghostly half-elven waylayer})
  insert(:name, %{ghostly half-krolvin scout})
  insert(:name, %{ghostly human pillager})
  insert(:name, %{The Ethereal Captain})
  insert(:name, %{unworldly brigand})
  insert(:name, %{unworldly pirate})
end

#Kraken Falls mobs
migrate :aggressive_npc do
  insert(:name, %{barbed cavern urchin})
  insert(:name, %{crazed canine})
  insert(:name, %{ebon swine})
  insert(:name, %{hobgoblin acolyte})
  insert(:name, %{imposing elk})
  insert(:name, %{luminous worm})
  insert(:name, %{muddy hog})
  insert(:name, %{muscular brindlecat})
  insert(:name, %{shelfae assailant})
  insert(:name, %{shelfae guard})
  insert(:name, %{speckled cave lizard})
  insert(:name, %{spectacled bear})
end
