migrate :herb do
  insert(:name, %{rice paper-wrapped tkaro root})
  insert(:name, %{some syrup-glazed ambrominas leaf})
  insert(:name, %{some spherical pieces of cothinar flower})
  insert(:name, %{tiny emerald glass bottle filled with bur-clover elixir})
  insert(:name, %{cumin-rubbed piece of sovyn clove})
  insert(:name, %{some caramelized piece of calamia fruit})
  insert(:name, %{twine-tied ball of ephlox moss})
  insert(:name, %{some wood-smoked pieces of cactacae spine})
  insert(:name, %{tiny onyx glass bottle filled with wingstem elixir})
  insert(:name, %{some pepper-spiced pothinir grass})
  insert(:name, %{rounded blue glass bottle filled with talneo elixir})
  insert(:name, %{leaf-wrapped ball of basal moss})
  insert(:name, %{tiny clay bottle filled with brostheras elixir})
  insert(:name, %{some anise-infused aloeas stem})
  insert(:name, %{some shredded strands of haphip root})
  insert(:name, %{tiny brown glass bottle filled with rose-marrow elixir})
  insert(:name, %{some cube-shaped pieces of woth flower})
  insert(:name, %{tiny scarlet glass bottle filled with bolmara elixir})
  insert(:name, %{some turmeric-stained torban leaf})
  insert(:name, %{some dense chunks of wolifrew lichen})
  insert(:name, %{some paprika-sprinkled acantha leaf})
end
