create_table "breakables", keys: [:name]

migrate "breakables" do
  insert(:name, %{large clump of barnacles})
  insert(:name, %{slimy thick-shelled carapace})
  insert(:name, %{ashy lump of charcoal})
  insert(:name, %{thick clump of debris})
  insert(:name, %{small pile of old debris})
  insert(:name, %{solid clod of dirt})
  insert(:name, %{vile clump of excrement})
  insert(:name, %{foul pile of excrement})
  insert(:name, %{hunk of rotting flesh})
  insert(:name, %{dusty glass jar})
  insert(:name, %{yellowed glass jar})
  insert(:name, %{putrid pile of muck})
  insert(:name, %{large brittle rock})
  insert(:name, %{large crumbly rock})
  insert(:name, %{hollowed petrified root})
  insert(:name, %{withered black rose})
  insert(:name, %{hardened clump of sand})
  insert(:name, %{large piece of sandstone})
  insert(:name, %{handful of congealed green slime})
  insert(:name, %{handful of congealed slime})
  insert(:name, %{hardened dark chitin})
end
