create_table "familiar", keys: [:name, :exclude]

migrate "familiar" do
  insert(:name, %{small bat})
  insert(:name, %{large bat})
  insert(:name, %{fruit bat})
  insert(:name, %{spotted bat})
  insert(:name, %{pygmy bat})
  insert(:name, %{short-nosed small bat})
  insert(:name, %{short-nosed large bat})
  insert(:name, %{short-nosed fruit bat})
  insert(:name, %{short-nosed spotted bat})
  insert(:name, %{short-nosed pygmy bat})
  insert(:name, %{bare-backed small bat})
  insert(:name, %{bare-backed large bat})
  insert(:name, %{bare-backed fruit bat})
  insert(:name, %{bare-backed spotted bat})
  insert(:name, %{bare-backed pygmy bat})
  insert(:name, %{little-collar small bat})
  insert(:name, %{little-collar large bat})
  insert(:name, %{little-collar fruit bat})
  insert(:name, %{little-collar spotted bat})
  insert(:name, %{little-collar pygmy bat})
  insert(:name, %{long-tailed small bat})
  insert(:name, %{long-tailed large bat})
  insert(:name, %{long-tailed fruit bat})
  insert(:name, %{long-tailed spotted bat})
  insert(:name, %{long-tailed pygmy bat})
  insert(:name, %{long-tongued small bat})
  insert(:name, %{long-tongued large bat})
  insert(:name, %{long-tongued fruit bat})
  insert(:name, %{long-tongued spotted bat})
  insert(:name, %{long-tongued pygmy bat})
  insert(:name, %{charcoal grey bandicoot})
  insert(:name, %{burnished bandicoot})
  insert(:name, %{yellowish brown bandicoot})
  insert(:name, %{light brown bandicoot})
  insert(:name, %{fuzzy grey bandicoot})
  insert(:name, %{dusty brown bandicoot})
  insert(:name, %{fuzzy brown bandicoot})
  insert(:name, %{golden brown bandicoot})
  insert(:name, %{reddish brown bandicoot})
  insert(:name, %{gold bandicoot})
  insert(:name, %{greyish brown bandicoot})
  insert(:name, %{cord-tailed charcoal grey bandicoot})
  insert(:name, %{cord-tailed burnished bandicoot})
  insert(:name, %{cord-tailed yellowish brown bandicoot})
  insert(:name, %{cord-tailed light brown bandicoot})
  insert(:name, %{cord-tailed fuzzy grey bandicoot})
  insert(:name, %{cord-tailed dusty brown bandicoot})
  insert(:name, %{cord-tailed fuzzy brown bandicoot})
  insert(:name, %{cord-tailed golden brown bandicoot})
  insert(:name, %{cord-tailed reddish brown bandicoot})
  insert(:name, %{cord-tailed gold bandicoot})
  insert(:name, %{cord-tailed greyish brown bandicoot})
  insert(:name, %{blunt-eared charcoal grey bandicoot})
  insert(:name, %{blunt-eared burnished bandicoot})
  insert(:name, %{blunt-eared yellowish brown bandicoot})
  insert(:name, %{blunt-eared light brown bandicoot})
  insert(:name, %{blunt-eared fuzzy grey bandicoot})
  insert(:name, %{blunt-eared dusty brown bandicoot})
  insert(:name, %{blunt-eared fuzzy brown bandicoot})
  insert(:name, %{blunt-eared golden brown bandicoot})
  insert(:name, %{blunt-eared reddish brown bandicoot})
  insert(:name, %{blunt-eared gold bandicoot})
  insert(:name, %{blunt-eared greyish brown bandicoot})
  insert(:name, %{bottle-nosed charcoal grey bandicoot})
  insert(:name, %{bottle-nosed burnished bandicoot})
  insert(:name, %{bottle-nosed yellowish brown bandicoot})
  insert(:name, %{bottle-nosed light brown bandicoot})
  insert(:name, %{bottle-nosed fuzzy grey bandicoot})
  insert(:name, %{bottle-nosed dusty brown bandicoot})
  insert(:name, %{bottle-nosed fuzzy brown bandicoot})
  insert(:name, %{bottle-nosed golden brown bandicoot})
  insert(:name, %{bottle-nosed reddish brown bandicoot})
  insert(:name, %{bottle-nosed gold bandicoot})
  insert(:name, %{bottle-nosed greyish brown bandicoot})
  insert(:name, %{stubby-eared charcoal grey bandicoot})
  insert(:name, %{stubby-eared burnished bandicoot})
  insert(:name, %{stubby-eared yellowish brown bandicoot})
  insert(:name, %{stubby-eared light brown bandicoot})
  insert(:name, %{stubby-eared fuzzy grey bandicoot})
  insert(:name, %{stubby-eared dusty brown bandicoot})
  insert(:name, %{stubby-eared fuzzy brown bandicoot})
  insert(:name, %{stubby-eared golden brown bandicoot})
  insert(:name, %{stubby-eared reddish brown bandicoot})
  insert(:name, %{stubby-eared gold bandicoot})
  insert(:name, %{stubby-eared greyish brown bandicoot})
  insert(:name, %{short-nosed charcoal grey bandicoot})
  insert(:name, %{short-nosed burnished bandicoot})
  insert(:name, %{short-nosed yellowish brown bandicoot})
  insert(:name, %{short-nosed light brown bandicoot})
  insert(:name, %{short-nosed fuzzy grey bandicoot})
  insert(:name, %{short-nosed dusty brown bandicoot})
  insert(:name, %{short-nosed fuzzy brown bandicoot})
  insert(:name, %{short-nosed golden brown bandicoot})
  insert(:name, %{short-nosed reddish brown bandicoot})
  insert(:name, %{short-nosed gold bandicoot})
  insert(:name, %{short-nosed greyish brown bandicoot})
  insert(:name, %{ebon-eared charcoal grey bandicoot})
  insert(:name, %{ebon-eared burnished bandicoot})
  insert(:name, %{ebon-eared yellowish brown bandicoot})
  insert(:name, %{ebon-eared light brown bandicoot})
  insert(:name, %{ebon-eared fuzzy grey bandicoot})
  insert(:name, %{ebon-eared dusty brown bandicoot})
  insert(:name, %{ebon-eared fuzzy brown bandicoot})
  insert(:name, %{ebon-eared golden brown bandicoot})
  insert(:name, %{ebon-eared reddish brown bandicoot})
  insert(:name, %{ebon-eared gold bandicoot})
  insert(:name, %{ebon-eared greyish brown bandicoot})
  insert(:name, %{long-nosed charcoal grey bandicoot})
  insert(:name, %{long-nosed burnished bandicoot})
  insert(:name, %{long-nosed yellowish brown bandicoot})
  insert(:name, %{long-nosed light brown bandicoot})
  insert(:name, %{long-nosed fuzzy grey bandicoot})
  insert(:name, %{long-nosed dusty brown bandicoot})
  insert(:name, %{long-nosed fuzzy brown bandicoot})
  insert(:name, %{long-nosed golden brown bandicoot})
  insert(:name, %{long-nosed reddish brown bandicoot})
  insert(:name, %{long-nosed gold bandicoot})
  insert(:name, %{long-nosed greyish brown bandicoot})
  insert(:name, %{pink-eyed charcoal grey bandicoot})
  insert(:name, %{pink-eyed burnished bandicoot})
  insert(:name, %{pink-eyed yellowish brown bandicoot})
  insert(:name, %{pink-eyed light brown bandicoot})
  insert(:name, %{pink-eyed fuzzy grey bandicoot})
  insert(:name, %{pink-eyed dusty brown bandicoot})
  insert(:name, %{pink-eyed fuzzy brown bandicoot})
  insert(:name, %{pink-eyed golden brown bandicoot})
  insert(:name, %{pink-eyed reddish brown bandicoot})
  insert(:name, %{pink-eyed gold bandicoot})
  insert(:name, %{pink-eyed greyish brown bandicoot})
  insert(:name, %{onyx-nosed charcoal grey bandicoot})
  insert(:name, %{onyx-nosed burnished bandicoot})
  insert(:name, %{onyx-nosed yellowish brown bandicoot})
  insert(:name, %{onyx-nosed light brown bandicoot})
  insert(:name, %{onyx-nosed fuzzy grey bandicoot})
  insert(:name, %{onyx-nosed dusty brown bandicoot})
  insert(:name, %{onyx-nosed fuzzy brown bandicoot})
  insert(:name, %{onyx-nosed golden brown bandicoot})
  insert(:name, %{onyx-nosed reddish brown bandicoot})
  insert(:name, %{onyx-nosed gold bandicoot})
  insert(:name, %{onyx-nosed greyish brown bandicoot})
  insert(:name, %{pinch-eyed charcoal grey bandicoot})
  insert(:name, %{pinch-eyed burnished bandicoot})
  insert(:name, %{pinch-eyed yellowish brown bandicoot})
  insert(:name, %{pinch-eyed light brown bandicoot})
  insert(:name, %{pinch-eyed fuzzy grey bandicoot})
  insert(:name, %{pinch-eyed dusty brown bandicoot})
  insert(:name, %{pinch-eyed fuzzy brown bandicoot})
  insert(:name, %{pinch-eyed golden brown bandicoot})
  insert(:name, %{pinch-eyed reddish brown bandicoot})
  insert(:name, %{pinch-eyed gold bandicoot})
  insert(:name, %{pinch-eyed greyish brown bandicoot})
  insert(:name, %{plump charcoal grey bandicoot})
  insert(:name, %{plump burnished bandicoot})
  insert(:name, %{plump yellowish brown bandicoot})
  insert(:name, %{plump light brown bandicoot})
  insert(:name, %{plump fuzzy grey bandicoot})
  insert(:name, %{plump dusty brown bandicoot})
  insert(:name, %{plump fuzzy brown bandicoot})
  insert(:name, %{plump golden brown bandicoot})
  insert(:name, %{plump reddish brown bandicoot})
  insert(:name, %{plump gold bandicoot})
  insert(:name, %{plump greyish brown bandicoot})
  insert(:name, %{black cat})
  insert(:name, %{calico cat})
  insert(:name, %{charcoal cat})
  insert(:name, %{ginger cat})
  insert(:name, %{grey cat})
  insert(:name, %{tabby cat})
  insert(:name, %{white cat})
  insert(:name, %{blue-eyed black cat})
  insert(:name, %{blue-eyed calico cat})
  insert(:name, %{blue-eyed charcoal cat})
  insert(:name, %{blue-eyed ginger cat})
  insert(:name, %{blue-eyed grey cat})
  insert(:name, %{blue-eyed tabby cat})
  insert(:name, %{blue-eyed white cat})
  insert(:name, %{disheveled black cat})
  insert(:name, %{disheveled calico cat})
  insert(:name, %{disheveled charcoal cat})
  insert(:name, %{disheveled ginger cat})
  insert(:name, %{disheveled grey cat})
  insert(:name, %{disheveled tabby cat})
  insert(:name, %{disheveled white cat})
  insert(:name, %{fat black cat})
  insert(:name, %{fat calico cat})
  insert(:name, %{fat charcoal cat})
  insert(:name, %{fat ginger cat})
  insert(:name, %{fat grey cat})
  insert(:name, %{fat tabby cat})
  insert(:name, %{fat white cat})
  insert(:name, %{fluffy black cat})
  insert(:name, %{fluffy calico cat})
  insert(:name, %{fluffy charcoal cat})
  insert(:name, %{fluffy ginger cat})
  insert(:name, %{fluffy grey cat})
  insert(:name, %{fluffy tabby cat})
  insert(:name, %{fluffy white cat})
  insert(:name, %{green-eyed black cat})
  insert(:name, %{green-eyed calico cat})
  insert(:name, %{green-eyed charcoal cat})
  insert(:name, %{green-eyed ginger cat})
  insert(:name, %{green-eyed grey cat})
  insert(:name, %{green-eyed tabby cat})
  insert(:name, %{green-eyed white cat})
  insert(:name, %{long-haired black cat})
  insert(:name, %{long-haired calico cat})
  insert(:name, %{long-haired charcoal cat})
  insert(:name, %{long-haired ginger cat})
  insert(:name, %{long-haired grey cat})
  insert(:name, %{long-haired tabby cat})
  insert(:name, %{long-haired white cat})
  insert(:name, %{orange-eyed black cat})
  insert(:name, %{orange-eyed calico cat})
  insert(:name, %{orange-eyed charcoal cat})
  insert(:name, %{orange-eyed ginger cat})
  insert(:name, %{orange-eyed grey cat})
  insert(:name, %{orange-eyed tabby cat})
  insert(:name, %{orange-eyed white cat})
  insert(:name, %{plump black cat})
  insert(:name, %{plump calico cat})
  insert(:name, %{plump charcoal cat})
  insert(:name, %{plump ginger cat})
  insert(:name, %{plump grey cat})
  insert(:name, %{plump tabby cat})
  insert(:name, %{plump white cat})
  insert(:name, %{shabby black cat})
  insert(:name, %{shabby calico cat})
  insert(:name, %{shabby charcoal cat})
  insert(:name, %{shabby ginger cat})
  insert(:name, %{shabby grey cat})
  insert(:name, %{shabby tabby cat})
  insert(:name, %{shabby white cat})
  insert(:name, %{short-haired black cat})
  insert(:name, %{short-haired calico cat})
  insert(:name, %{short-haired charcoal cat})
  insert(:name, %{short-haired ginger cat})
  insert(:name, %{short-haired grey cat})
  insert(:name, %{short-haired tabby cat})
  insert(:name, %{short-haired white cat})
  insert(:name, %{sleek black cat})
  insert(:name, %{sleek calico cat})
  insert(:name, %{sleek charcoal cat})
  insert(:name, %{sleek ginger cat})
  insert(:name, %{sleek grey cat})
  insert(:name, %{sleek tabby cat})
  insert(:name, %{sleek white cat})
  insert(:name, %{emerald-eyed black cat})
  insert(:name, %{emerald-eyed calico cat})
  insert(:name, %{emerald-eyed charcoal cat})
  insert(:name, %{emerald-eyed ginger cat})
  insert(:name, %{emerald-eyed grey cat})
  insert(:name, %{emerald-eyed tabby cat})
  insert(:name, %{emerald-eyed white cat})
  insert(:name, %{silver-eyed pure white cat})
  insert(:name, %{silver-ruffled charcoal black cat})
  insert(:name, %{black chameleon})
  insert(:name, %{brown chameleon})
  insert(:name, %{dwarf chameleon})
  insert(:name, %{forest chameleon})
  insert(:name, %{green chameleon})
  insert(:name, %{grey chameleon})
  insert(:name, %{leaf chameleon})
  insert(:name, %{mountain chameleon})
  insert(:name, %{ochre chameleon})
  insert(:name, %{spotted chameleon})
  insert(:name, %{veiled chameleon})
  insert(:name, %{large black chameleon})
  insert(:name, %{large brown chameleon})
  insert(:name, %{large dwarf chameleon})
  insert(:name, %{large forest chameleon})
  insert(:name, %{large green chameleon})
  insert(:name, %{large grey chameleon})
  insert(:name, %{large leaf chameleon})
  insert(:name, %{large mountain chameleon})
  insert(:name, %{large ochre chameleon})
  insert(:name, %{large spotted chameleon})
  insert(:name, %{large veiled chameleon})
  insert(:name, %{small black chameleon})
  insert(:name, %{small brown chameleon})
  insert(:name, %{small dwarf chameleon})
  insert(:name, %{small forest chameleon})
  insert(:name, %{small green chameleon})
  insert(:name, %{small grey chameleon})
  insert(:name, %{small leaf chameleon})
  insert(:name, %{small mountain chameleon})
  insert(:name, %{small ochre chameleon})
  insert(:name, %{small spotted chameleon})
  insert(:name, %{small veiled chameleon})
  insert(:name, %{light green cockatiel})
  insert(:name, %{pale yellow cockatiel})
  insert(:name, %{pale green cockatiel})
  insert(:name, %{dusty yellow cockatiel})
  insert(:name, %{dusty grey cockatiel})
  insert(:name, %{bright yellow cockatiel})
  insert(:name, %{saffron yellow cockatiel})
  insert(:name, %{albino cockatiel})
  insert(:name, %{green cockatiel})
  insert(:name, %{grey cockatiel})
  insert(:name, %{yellow cockatiel})
  insert(:name, %{pink-cheeked light green cockatiel})
  insert(:name, %{pink-cheeked pale yellow cockatiel})
  insert(:name, %{pink-cheeked pale green cockatiel})
  insert(:name, %{pink-cheeked dusty yellow cockatiel})
  insert(:name, %{pink-cheeked dusty grey cockatiel})
  insert(:name, %{pink-cheeked bright yellow cockatiel})
  insert(:name, %{pink-cheeked saffron yellow cockatiel})
  insert(:name, %{pink-cheeked albino cockatiel})
  insert(:name, %{pink-cheeked green cockatiel})
  insert(:name, %{pink-cheeked grey cockatiel})
  insert(:name, %{pink-cheeked yellow cockatiel})
  insert(:name, %{white-winged light green cockatiel})
  insert(:name, %{white-winged pale yellow cockatiel})
  insert(:name, %{white-winged pale green cockatiel})
  insert(:name, %{white-winged dusty yellow cockatiel})
  insert(:name, %{white-winged dusty grey cockatiel})
  insert(:name, %{white-winged bright yellow cockatiel})
  insert(:name, %{white-winged saffron yellow cockatiel})
  insert(:name, %{white-winged albino cockatiel})
  insert(:name, %{white-winged green cockatiel})
  insert(:name, %{white-winged grey cockatiel})
  insert(:name, %{white-winged yellow cockatiel})
  insert(:name, %{ruby-cheeked light green cockatiel})
  insert(:name, %{ruby-cheeked pale yellow cockatiel})
  insert(:name, %{ruby-cheeked pale green cockatiel})
  insert(:name, %{ruby-cheeked dusty yellow cockatiel})
  insert(:name, %{ruby-cheeked dusty grey cockatiel})
  insert(:name, %{ruby-cheeked bright yellow cockatiel})
  insert(:name, %{ruby-cheeked saffron yellow cockatiel})
  insert(:name, %{ruby-cheeked albino cockatiel})
  insert(:name, %{ruby-cheeked green cockatiel})
  insert(:name, %{ruby-cheeked grey cockatiel})
  insert(:name, %{ruby-cheeked yellow cockatiel})
  insert(:name, %{white-faced light green cockatiel})
  insert(:name, %{white-faced pale yellow cockatiel})
  insert(:name, %{white-faced pale green cockatiel})
  insert(:name, %{white-faced dusty yellow cockatiel})
  insert(:name, %{white-faced dusty grey cockatiel})
  insert(:name, %{white-faced bright yellow cockatiel})
  insert(:name, %{white-faced saffron yellow cockatiel})
  insert(:name, %{white-faced albino cockatiel})
  insert(:name, %{white-faced green cockatiel})
  insert(:name, %{white-faced grey cockatiel})
  insert(:name, %{white-faced yellow cockatiel})
  insert(:name, %{croak-beaked light green cockatiel})
  insert(:name, %{croak-beaked pale yellow cockatiel})
  insert(:name, %{croak-beaked pale green cockatiel})
  insert(:name, %{croak-beaked dusty yellow cockatiel})
  insert(:name, %{croak-beaked dusty grey cockatiel})
  insert(:name, %{croak-beaked bright yellow cockatiel})
  insert(:name, %{croak-beaked saffron yellow cockatiel})
  insert(:name, %{croak-beaked albino cockatiel})
  insert(:name, %{croak-beaked green cockatiel})
  insert(:name, %{croak-beaked grey cockatiel})
  insert(:name, %{croak-beaked yellow cockatiel})
  insert(:name, %{white-banded light green cockatiel})
  insert(:name, %{white-banded pale yellow cockatiel})
  insert(:name, %{white-banded pale green cockatiel})
  insert(:name, %{white-banded dusty yellow cockatiel})
  insert(:name, %{white-banded dusty grey cockatiel})
  insert(:name, %{white-banded bright yellow cockatiel})
  insert(:name, %{white-banded saffron yellow cockatiel})
  insert(:name, %{white-banded albino cockatiel})
  insert(:name, %{white-banded green cockatiel})
  insert(:name, %{white-banded grey cockatiel})
  insert(:name, %{white-banded yellow cockatiel})
  insert(:name, %{beady-eyed light green cockatiel})
  insert(:name, %{beady-eyed pale yellow cockatiel})
  insert(:name, %{beady-eyed pale green cockatiel})
  insert(:name, %{beady-eyed dusty yellow cockatiel})
  insert(:name, %{beady-eyed dusty grey cockatiel})
  insert(:name, %{beady-eyed bright yellow cockatiel})
  insert(:name, %{beady-eyed saffron yellow cockatiel})
  insert(:name, %{beady-eyed albino cockatiel})
  insert(:name, %{beady-eyed green cockatiel})
  insert(:name, %{beady-eyed grey cockatiel})
  insert(:name, %{beady-eyed yellow cockatiel})
  insert(:name, %{grey-banded light green cockatiel})
  insert(:name, %{grey-banded pale yellow cockatiel})
  insert(:name, %{grey-banded pale green cockatiel})
  insert(:name, %{grey-banded dusty yellow cockatiel})
  insert(:name, %{grey-banded dusty grey cockatiel})
  insert(:name, %{grey-banded bright yellow cockatiel})
  insert(:name, %{grey-banded saffron yellow cockatiel})
  insert(:name, %{grey-banded albino cockatiel})
  insert(:name, %{grey-banded green cockatiel})
  insert(:name, %{grey-banded grey cockatiel})
  insert(:name, %{grey-banded yellow cockatiel})
  insert(:name, %{green-faced light green cockatiel})
  insert(:name, %{green-faced pale yellow cockatiel})
  insert(:name, %{green-faced pale green cockatiel})
  insert(:name, %{green-faced dusty yellow cockatiel})
  insert(:name, %{green-faced dusty grey cockatiel})
  insert(:name, %{green-faced bright yellow cockatiel})
  insert(:name, %{green-faced saffron yellow cockatiel})
  insert(:name, %{green-faced albino cockatiel})
  insert(:name, %{green-faced green cockatiel})
  insert(:name, %{green-faced grey cockatiel})
  insert(:name, %{green-faced yellow cockatiel})
  insert(:name, %{iridescent purple-plumed cormorant})
  insert(:name, %{purple-plumed cormorant})
  insert(:name, %{lithe golden-eyed coyote})
  insert(:name, %{long-winged falcon})
  insert(:name, %{narrow-winged falcon})
  insert(:name, %{red-footed falcon})
  insert(:name, %{red-necked falcon})
  insert(:name, %{large long-winged falcon})
  insert(:name, %{large narrow-winged falcon})
  insert(:name, %{large red-footed falcon})
  insert(:name, %{large red-necked falcon})
  insert(:name, %{ruffled long-winged falcon})
  insert(:name, %{ruffled narrow-winged falcon})
  insert(:name, %{ruffled red-footed falcon})
  insert(:name, %{ruffled red-necked falcon})
  insert(:name, %{sleek long-winged falcon})
  insert(:name, %{sleek narrow-winged falcon})
  insert(:name, %{sleek red-footed falcon})
  insert(:name, %{sleek red-necked falcon})
  insert(:name, %{small long-winged falcon})
  insert(:name, %{small narrow-winged falcon})
  insert(:name, %{small red-footed falcon})
  insert(:name, %{small red-necked falcon})
  insert(:name, %{black-footed plump red fox})
  insert(:name, %{arctic fox})
  insert(:name, %{bat-eared fox})
  insert(:name, %{black fox})
  insert(:name, %{blue fox})
  insert(:name, %{desert fox})
  insert(:name, %{grey fox})
  insert(:name, %{kit fox})
  insert(:name, %{red fox})
  insert(:name, %{swift fox})
  insert(:name, %{disheveled arctic fox})
  insert(:name, %{disheveled bat-eared fox})
  insert(:name, %{disheveled black fox})
  insert(:name, %{disheveled blue fox})
  insert(:name, %{disheveled desert fox})
  insert(:name, %{disheveled grey fox})
  insert(:name, %{disheveled kit fox})
  insert(:name, %{disheveled red fox})
  insert(:name, %{disheveled swift fox})
  insert(:name, %{sleek arctic fox})
  insert(:name, %{sleek bat-eared fox})
  insert(:name, %{sleek black fox})
  insert(:name, %{sleek blue fox})
  insert(:name, %{sleek desert fox})
  insert(:name, %{sleek grey fox})
  insert(:name, %{sleek kit fox})
  insert(:name, %{sleek red fox})
  insert(:name, %{sleek swift fox})
  insert(:name, %{heavy-set bull frog})
  insert(:name, %{brown frog})
  insert(:name, %{bull frog})
  insert(:name, %{green frog})
  insert(:name, %{green tree frog})
  insert(:name, %{horned frog})
  insert(:name, %{tree frog})
  insert(:name, %{large brown frog})
  insert(:name, %{large bull frog})
  insert(:name, %{large green frog})
  insert(:name, %{large green tree frog})
  insert(:name, %{large horned frog})
  insert(:name, %{large tree frog})
  insert(:name, %{plump brown frog})
  insert(:name, %{plump bull frog})
  insert(:name, %{plump green frog})
  insert(:name, %{plump green tree frog})
  insert(:name, %{plump horned frog})
  insert(:name, %{plump tree frog})
  insert(:name, %{slimy brown frog})
  insert(:name, %{slimy bull frog})
  insert(:name, %{slimy green frog})
  insert(:name, %{slimy green tree frog})
  insert(:name, %{slimy horned frog})
  insert(:name, %{slimy tree frog})
  insert(:name, %{small brown frog})
  insert(:name, %{small bull frog})
  insert(:name, %{small green frog})
  insert(:name, %{small green tree frog})
  insert(:name, %{small horned frog})
  insert(:name, %{small tree frog})
  insert(:name, %{speckled brown frog})
  insert(:name, %{speckled bull frog})
  insert(:name, %{speckled green frog})
  insert(:name, %{speckled green tree frog})
  insert(:name, %{speckled horned frog})
  insert(:name, %{speckled tree frog})
  insert(:name, %{gyrfalcon})
  insert(:name, %{black hare})
  insert(:name, %{broom hare})
  insert(:name, %{cape hare})
  insert(:name, %{mountain hare})
  insert(:name, %{red hare})
  insert(:name, %{savanna hare})
  insert(:name, %{scrub hare})
  insert(:name, %{snowshoe hare})
  insert(:name, %{woolly hare})
  insert(:name, %{black-tailed black hare})
  insert(:name, %{black-tailed broom hare})
  insert(:name, %{black-tailed cape hare})
  insert(:name, %{black-tailed mountain hare})
  insert(:name, %{black-tailed red hare})
  insert(:name, %{black-tailed savanna hare})
  insert(:name, %{black-tailed scrub hare})
  insert(:name, %{black-tailed snowshoe hare})
  insert(:name, %{black-tailed woolly hare})
  insert(:name, %{white-tailed black hare})
  insert(:name, %{white-tailed broom hare})
  insert(:name, %{white-tailed cape hare})
  insert(:name, %{white-tailed mountain hare})
  insert(:name, %{white-tailed red hare})
  insert(:name, %{white-tailed savanna hare})
  insert(:name, %{white-tailed scrub hare})
  insert(:name, %{white-tailed snowshoe hare})
  insert(:name, %{white-tailed woolly hare})
  insert(:name, %{dappled broad-winged hawk})
  insert(:name, %{black hawk})
  insert(:name, %{black-mantled hawk})
  insert(:name, %{grey-bellied hawk})
  insert(:name, %{grey-headed hawk})
  insert(:name, %{red-chested hawk})
  insert(:name, %{red-tailed hawk})
  insert(:name, %{spot-tailed hawk})
  insert(:name, %{white-bellied hawk})
  insert(:name, %{large black hawk})
  insert(:name, %{large black-mantled hawk})
  insert(:name, %{large grey-bellied hawk})
  insert(:name, %{large grey-headed hawk})
  insert(:name, %{large red-chested hawk})
  insert(:name, %{large red-tailed hawk})
  insert(:name, %{large spot-tailed hawk})
  insert(:name, %{large white-bellied hawk})
  insert(:name, %{ruffled black hawk})
  insert(:name, %{ruffled black-mantled hawk})
  insert(:name, %{ruffled grey-bellied hawk})
  insert(:name, %{ruffled grey-headed hawk})
  insert(:name, %{ruffled red-chested hawk})
  insert(:name, %{ruffled red-tailed hawk})
  insert(:name, %{ruffled spot-tailed hawk})
  insert(:name, %{ruffled white-bellied hawk})
  insert(:name, %{sleek black hawk})
  insert(:name, %{sleek black-mantled hawk})
  insert(:name, %{sleek grey-bellied hawk})
  insert(:name, %{sleek grey-headed hawk})
  insert(:name, %{sleek red-chested hawk})
  insert(:name, %{sleek red-tailed hawk})
  insert(:name, %{sleek spot-tailed hawk})
  insert(:name, %{sleek white-bellied hawk})
  insert(:name, %{small black hawk})
  insert(:name, %{small black-mantled hawk})
  insert(:name, %{small grey-bellied hawk})
  insert(:name, %{small grey-headed hawk})
  insert(:name, %{small red-chested hawk})
  insert(:name, %{small red-tailed hawk})
  insert(:name, %{small spot-tailed hawk})
  insert(:name, %{small white-bellied hawk})
  insert(:name, %{dusty brown hummingbird})
  insert(:name, %{viridian hummingbird})
  insert(:name, %{burnt umber hummingbird})
  insert(:name, %{jade green hummingbird})
  insert(:name, %{violet hummingbird})
  insert(:name, %{emerald hummingbird})
  insert(:name, %{turquoise hummingbird})
  insert(:name, %{celadon hummingbird})
  insert(:name, %{burnished grey hummingbird})
  insert(:name, %{green-black hummingbird})
  insert(:name, %{white-bellied dusty brown hummingbird})
  insert(:name, %{white-bellied viridian hummingbird})
  insert(:name, %{white-bellied burnt umber hummingbird})
  insert(:name, %{white-bellied jade green hummingbird})
  insert(:name, %{white-bellied violet hummingbird})
  insert(:name, %{white-bellied emerald hummingbird})
  insert(:name, %{white-bellied turquoise hummingbird})
  insert(:name, %{white-bellied celadon hummingbird})
  insert(:name, %{white-bellied burnished grey hummingbird})
  insert(:name, %{white-bellied green-black hummingbird})
  insert(:name, %{white-winged dusty brown hummingbird})
  insert(:name, %{white-winged viridian hummingbird})
  insert(:name, %{white-winged burnt umber hummingbird})
  insert(:name, %{white-winged jade green hummingbird})
  insert(:name, %{white-winged violet hummingbird})
  insert(:name, %{white-winged emerald hummingbird})
  insert(:name, %{white-winged turquoise hummingbird})
  insert(:name, %{white-winged celadon hummingbird})
  insert(:name, %{white-winged burnished grey hummingbird})
  insert(:name, %{white-winged green-black hummingbird})
  insert(:name, %{plum-bellied dusty brown hummingbird})
  insert(:name, %{plum-bellied viridian hummingbird})
  insert(:name, %{plum-bellied burnt umber hummingbird})
  insert(:name, %{plum-bellied jade green hummingbird})
  insert(:name, %{plum-bellied violet hummingbird})
  insert(:name, %{plum-bellied emerald hummingbird})
  insert(:name, %{plum-bellied turquoise hummingbird})
  insert(:name, %{plum-bellied celadon hummingbird})
  insert(:name, %{plum-bellied burnished grey hummingbird})
  insert(:name, %{plum-bellied green-black hummingbird})
  insert(:name, %{yellow-winged dusty brown hummingbird})
  insert(:name, %{yellow-winged viridian hummingbird})
  insert(:name, %{yellow-winged burnt umber hummingbird})
  insert(:name, %{yellow-winged jade green hummingbird})
  insert(:name, %{yellow-winged violet hummingbird})
  insert(:name, %{yellow-winged emerald hummingbird})
  insert(:name, %{yellow-winged turquoise hummingbird})
  insert(:name, %{yellow-winged celadon hummingbird})
  insert(:name, %{yellow-winged burnished grey hummingbird})
  insert(:name, %{yellow-winged green-black hummingbird})
  insert(:name, %{plum-sheened dusty brown hummingbird})
  insert(:name, %{plum-sheened viridian hummingbird})
  insert(:name, %{plum-sheened burnt umber hummingbird})
  insert(:name, %{plum-sheened jade green hummingbird})
  insert(:name, %{plum-sheened violet hummingbird})
  insert(:name, %{plum-sheened emerald hummingbird})
  insert(:name, %{plum-sheened turquoise hummingbird})
  insert(:name, %{plum-sheened celadon hummingbird})
  insert(:name, %{plum-sheened burnished grey hummingbird})
  insert(:name, %{plum-sheened green-black hummingbird})
  insert(:name, %{ruby-throated dusty brown hummingbird})
  insert(:name, %{ruby-throated viridian hummingbird})
  insert(:name, %{ruby-throated burnt umber hummingbird})
  insert(:name, %{ruby-throated jade green hummingbird})
  insert(:name, %{ruby-throated violet hummingbird})
  insert(:name, %{ruby-throated emerald hummingbird})
  insert(:name, %{ruby-throated turquoise hummingbird})
  insert(:name, %{ruby-throated celadon hummingbird})
  insert(:name, %{ruby-throated burnished grey hummingbird})
  insert(:name, %{ruby-throated green-black hummingbird})
  insert(:name, %{plum-crested dusty brown hummingbird})
  insert(:name, %{plum-crested viridian hummingbird})
  insert(:name, %{plum-crested burnt umber hummingbird})
  insert(:name, %{plum-crested jade green hummingbird})
  insert(:name, %{plum-crested violet hummingbird})
  insert(:name, %{plum-crested emerald hummingbird})
  insert(:name, %{plum-crested turquoise hummingbird})
  insert(:name, %{plum-crested celadon hummingbird})
  insert(:name, %{plum-crested burnished grey hummingbird})
  insert(:name, %{plum-crested green-black hummingbird})
  insert(:name, %{delicate dusty brown hummingbird})
  insert(:name, %{delicate viridian hummingbird})
  insert(:name, %{delicate burnt umber hummingbird})
  insert(:name, %{delicate jade green hummingbird})
  insert(:name, %{delicate violet hummingbird})
  insert(:name, %{delicate emerald hummingbird})
  insert(:name, %{delicate turquoise hummingbird})
  insert(:name, %{delicate celadon hummingbird})
  insert(:name, %{delicate burnished grey hummingbird})
  insert(:name, %{delicate green-black hummingbird})
  insert(:name, %{blunt-nosed dusty brown hummingbird})
  insert(:name, %{blunt-nosed viridian hummingbird})
  insert(:name, %{blunt-nosed burnt umber hummingbird})
  insert(:name, %{blunt-nosed jade green hummingbird})
  insert(:name, %{blunt-nosed violet hummingbird})
  insert(:name, %{blunt-nosed emerald hummingbird})
  insert(:name, %{blunt-nosed turquoise hummingbird})
  insert(:name, %{blunt-nosed celadon hummingbird})
  insert(:name, %{blunt-nosed burnished grey hummingbird})
  insert(:name, %{blunt-nosed green-black hummingbird})
  insert(:name, %{needle-nosed dusty brown hummingbird})
  insert(:name, %{needle-nosed viridian hummingbird})
  insert(:name, %{needle-nosed burnt umber hummingbird})
  insert(:name, %{needle-nosed jade green hummingbird})
  insert(:name, %{needle-nosed violet hummingbird})
  insert(:name, %{needle-nosed emerald hummingbird})
  insert(:name, %{needle-nosed turquoise hummingbird})
  insert(:name, %{needle-nosed celadon hummingbird})
  insert(:name, %{needle-nosed burnished grey hummingbird})
  insert(:name, %{needle-nosed green-black hummingbird})
  insert(:name, %{pale green iguana})
  insert(:name, %{light viridian iguana})
  insert(:name, %{leafy green iguana})
  insert(:name, %{jade green iguana})
  insert(:name, %{grass green iguana})
  insert(:name, %{emerald iguana})
  insert(:name, %{russet brown iguana})
  insert(:name, %{deep green iguana})
  insert(:name, %{spike-backed pale green iguana})
  insert(:name, %{spike-backed light viridian iguana})
  insert(:name, %{spike-backed leafy green iguana})
  insert(:name, %{spike-backed jade green iguana})
  insert(:name, %{spike-backed grass green iguana})
  insert(:name, %{spike-backed emerald iguana})
  insert(:name, %{spike-backed russet brown iguana})
  insert(:name, %{spike-backed deep green iguana})
  insert(:name, %{drab pale green iguana})
  insert(:name, %{drab light viridian iguana})
  insert(:name, %{drab leafy green iguana})
  insert(:name, %{drab jade green iguana})
  insert(:name, %{drab grass green iguana})
  insert(:name, %{drab emerald iguana})
  insert(:name, %{drab russet brown iguana})
  insert(:name, %{drab deep green iguana})
  insert(:name, %{short-snouted pale green iguana})
  insert(:name, %{short-snouted light viridian iguana})
  insert(:name, %{short-snouted leafy green iguana})
  insert(:name, %{short-snouted jade green iguana})
  insert(:name, %{short-snouted grass green iguana})
  insert(:name, %{short-snouted emerald iguana})
  insert(:name, %{short-snouted russet brown iguana})
  insert(:name, %{short-snouted deep green iguana})
  insert(:name, %{aged pale green iguana})
  insert(:name, %{aged light viridian iguana})
  insert(:name, %{aged leafy green iguana})
  insert(:name, %{aged jade green iguana})
  insert(:name, %{aged grass green iguana})
  insert(:name, %{aged emerald iguana})
  insert(:name, %{aged russet brown iguana})
  insert(:name, %{aged deep green iguana})
  insert(:name, %{long-snouted pale green iguana})
  insert(:name, %{long-snouted light viridian iguana})
  insert(:name, %{long-snouted leafy green iguana})
  insert(:name, %{long-snouted jade green iguana})
  insert(:name, %{long-snouted grass green iguana})
  insert(:name, %{long-snouted emerald iguana})
  insert(:name, %{long-snouted russet brown iguana})
  insert(:name, %{long-snouted deep green iguana})
  insert(:name, %{scaly pale green iguana})
  insert(:name, %{scaly light viridian iguana})
  insert(:name, %{scaly leafy green iguana})
  insert(:name, %{scaly jade green iguana})
  insert(:name, %{scaly grass green iguana})
  insert(:name, %{scaly emerald iguana})
  insert(:name, %{scaly russet brown iguana})
  insert(:name, %{scaly deep green iguana})
  insert(:name, %{three-toed pale green iguana})
  insert(:name, %{three-toed light viridian iguana})
  insert(:name, %{three-toed leafy green iguana})
  insert(:name, %{three-toed jade green iguana})
  insert(:name, %{three-toed grass green iguana})
  insert(:name, %{three-toed emerald iguana})
  insert(:name, %{three-toed russet brown iguana})
  insert(:name, %{three-toed deep green iguana})
  insert(:name, %{split-tailed pale green iguana})
  insert(:name, %{split-tailed light viridian iguana})
  insert(:name, %{split-tailed leafy green iguana})
  insert(:name, %{split-tailed jade green iguana})
  insert(:name, %{split-tailed grass green iguana})
  insert(:name, %{split-tailed emerald iguana})
  insert(:name, %{split-tailed russet brown iguana})
  insert(:name, %{split-tailed deep green iguana})
  insert(:name, %{rangy dappled grey jackal})
  insert(:name, %{bamboo lemur})
  insert(:name, %{black lemur})
  insert(:name, %{brown lemur})
  insert(:name, %{crowned lemur})
  insert(:name, %{dwarf lemur})
  insert(:name, %{fork-crowned lemur})
  insert(:name, %{golden lemur})
  insert(:name, %{fork-marked lemur})
  insert(:name, %{grey lemur})
  insert(:name, %{grey-headed lemur})
  insert(:name, %{mouse lemur})
  insert(:name, %{red-bellied lemur})
  insert(:name, %{ring-tailed lemur})
  insert(:name, %{red-collared lemur})
  insert(:name, %{ruffled lemur})
  insert(:name, %{white-collared lemur})
  insert(:name, %{greater bamboo lemur})
  insert(:name, %{greater black lemur})
  insert(:name, %{greater brown lemur})
  insert(:name, %{greater crowned lemur})
  insert(:name, %{greater dwarf lemur})
  insert(:name, %{greater fork-crowned lemur})
  insert(:name, %{greater golden lemur})
  insert(:name, %{greater fork-marked lemur})
  insert(:name, %{greater grey lemur})
  insert(:name, %{greater grey-headed lemur})
  insert(:name, %{greater mouse lemur})
  insert(:name, %{greater red-bellied lemur})
  insert(:name, %{greater ring-tailed lemur})
  insert(:name, %{greater red-collared lemur})
  insert(:name, %{greater ruffled lemur})
  insert(:name, %{greater white-collared lemur})
  insert(:name, %{lesser bamboo lemur})
  insert(:name, %{lesser black lemur})
  insert(:name, %{lesser brown lemur})
  insert(:name, %{lesser crowned lemur})
  insert(:name, %{lesser dwarf lemur})
  insert(:name, %{lesser fork-crowned lemur})
  insert(:name, %{lesser golden lemur})
  insert(:name, %{lesser fork-marked lemur})
  insert(:name, %{lesser grey lemur})
  insert(:name, %{lesser grey-headed lemur})
  insert(:name, %{lesser mouse lemur})
  insert(:name, %{lesser red-bellied lemur})
  insert(:name, %{lesser ring-tailed lemur})
  insert(:name, %{lesser red-collared lemur})
  insert(:name, %{lesser ruffled lemur})
  insert(:name, %{lesser white-collared lemur})
  insert(:name, %{sleek bamboo lemur})
  insert(:name, %{sleek black lemur})
  insert(:name, %{sleek brown lemur})
  insert(:name, %{sleek crowned lemur})
  insert(:name, %{sleek dwarf lemur})
  insert(:name, %{sleek fork-crowned lemur})
  insert(:name, %{sleek golden lemur})
  insert(:name, %{sleek fork-marked lemur})
  insert(:name, %{sleek grey lemur})
  insert(:name, %{sleek grey-headed lemur})
  insert(:name, %{sleek mouse lemur})
  insert(:name, %{sleek red-bellied lemur})
  insert(:name, %{sleek ring-tailed lemur})
  insert(:name, %{sleek red-collared lemur})
  insert(:name, %{sleek ruffled lemur})
  insert(:name, %{sleek white-collared lemur})
  insert(:name, %{small bamboo lemur})
  insert(:name, %{small black lemur})
  insert(:name, %{small brown lemur})
  insert(:name, %{small crowned lemur})
  insert(:name, %{small dwarf lemur})
  insert(:name, %{small fork-crowned lemur})
  insert(:name, %{small golden lemur})
  insert(:name, %{small fork-marked lemur})
  insert(:name, %{small grey lemur})
  insert(:name, %{small grey-headed lemur})
  insert(:name, %{small mouse lemur})
  insert(:name, %{small red-bellied lemur})
  insert(:name, %{small ring-tailed lemur})
  insert(:name, %{small red-collared lemur})
  insert(:name, %{small ruffled lemur})
  insert(:name, %{small white-collared lemur})
  insert(:name, %{dark brown marmoset})
  insert(:name, %{dark grey marmoset})
  insert(:name, %{chocolate brown marmoset})
  insert(:name, %{light grey marmoset})
  insert(:name, %{burnt umber marmoset})
  insert(:name, %{inky black marmoset})
  insert(:name, %{russet marmoset})
  insert(:name, %{albino marmoset})
  insert(:name, %{auburn marmoset})
  insert(:name, %{petite dark brown marmoset})
  insert(:name, %{petite dark grey marmoset})
  insert(:name, %{petite chocolate brown marmoset})
  insert(:name, %{petite light grey marmoset})
  insert(:name, %{petite burnt umber marmoset})
  insert(:name, %{petite inky black marmoset})
  insert(:name, %{petite russet marmoset})
  insert(:name, %{petite albino marmoset})
  insert(:name, %{petite auburn marmoset})
  insert(:name, %{blunt-faced dark brown marmoset})
  insert(:name, %{blunt-faced dark grey marmoset})
  insert(:name, %{blunt-faced chocolate brown marmoset})
  insert(:name, %{blunt-faced light grey marmoset})
  insert(:name, %{blunt-faced burnt umber marmoset})
  insert(:name, %{blunt-faced inky black marmoset})
  insert(:name, %{blunt-faced russet marmoset})
  insert(:name, %{blunt-faced albino marmoset})
  insert(:name, %{blunt-faced auburn marmoset})
  insert(:name, %{fuzzy dark brown marmoset})
  insert(:name, %{fuzzy dark grey marmoset})
  insert(:name, %{fuzzy chocolate brown marmoset})
  insert(:name, %{fuzzy light grey marmoset})
  insert(:name, %{fuzzy burnt umber marmoset})
  insert(:name, %{fuzzy inky black marmoset})
  insert(:name, %{fuzzy russet marmoset})
  insert(:name, %{fuzzy albino marmoset})
  insert(:name, %{fuzzy auburn marmoset})
  insert(:name, %{lion-faced dark brown marmoset})
  insert(:name, %{lion-faced dark grey marmoset})
  insert(:name, %{lion-faced chocolate brown marmoset})
  insert(:name, %{lion-faced light grey marmoset})
  insert(:name, %{lion-faced burnt umber marmoset})
  insert(:name, %{lion-faced inky black marmoset})
  insert(:name, %{lion-faced russet marmoset})
  insert(:name, %{lion-faced albino marmoset})
  insert(:name, %{lion-faced auburn marmoset})
  insert(:name, %{ebon-bellied dark brown marmoset})
  insert(:name, %{ebon-bellied dark grey marmoset})
  insert(:name, %{ebon-bellied chocolate brown marmoset})
  insert(:name, %{ebon-bellied light grey marmoset})
  insert(:name, %{ebon-bellied burnt umber marmoset})
  insert(:name, %{ebon-bellied inky black marmoset})
  insert(:name, %{ebon-bellied russet marmoset})
  insert(:name, %{ebon-bellied albino marmoset})
  insert(:name, %{ebon-bellied auburn marmoset})
  insert(:name, %{white-bellied dark brown marmoset})
  insert(:name, %{white-bellied dark grey marmoset})
  insert(:name, %{white-bellied chocolate brown marmoset})
  insert(:name, %{white-bellied light grey marmoset})
  insert(:name, %{white-bellied burnt umber marmoset})
  insert(:name, %{white-bellied inky black marmoset})
  insert(:name, %{white-bellied russet marmoset})
  insert(:name, %{white-bellied albino marmoset})
  insert(:name, %{white-bellied auburn marmoset})
  insert(:name, %{strip-headed dark brown marmoset})
  insert(:name, %{strip-headed dark grey marmoset})
  insert(:name, %{strip-headed chocolate brown marmoset})
  insert(:name, %{strip-headed light grey marmoset})
  insert(:name, %{strip-headed burnt umber marmoset})
  insert(:name, %{strip-headed inky black marmoset})
  insert(:name, %{strip-headed russet marmoset})
  insert(:name, %{strip-headed albino marmoset})
  insert(:name, %{strip-headed auburn marmoset})
  insert(:name, %{pink-handed dark brown marmoset})
  insert(:name, %{pink-handed dark grey marmoset})
  insert(:name, %{pink-handed chocolate brown marmoset})
  insert(:name, %{pink-handed light grey marmoset})
  insert(:name, %{pink-handed burnt umber marmoset})
  insert(:name, %{pink-handed inky black marmoset})
  insert(:name, %{pink-handed russet marmoset})
  insert(:name, %{pink-handed albino marmoset})
  insert(:name, %{pink-handed auburn marmoset})
  insert(:name, %{dark brown melomys})
  insert(:name, %{dark grey melomys})
  insert(:name, %{chocolate brown melomys})
  insert(:name, %{inky black melomys})
  insert(:name, %{burnt umber melomys})
  insert(:name, %{auburn melomys})
  insert(:name, %{albino melomys})
  insert(:name, %{russet melomys})
  insert(:name, %{dusty brown melomys})
  insert(:name, %{light brown melomys})
  insert(:name, %{brown melomys})
  insert(:name, %{plump dark brown melomys})
  insert(:name, %{plump dark grey melomys})
  insert(:name, %{plump chocolate brown melomys})
  insert(:name, %{plump inky black melomys})
  insert(:name, %{plump burnt umber melomys})
  insert(:name, %{plump auburn melomys})
  insert(:name, %{plump albino melomys})
  insert(:name, %{plump russet melomys})
  insert(:name, %{plump dusty brown melomys})
  insert(:name, %{plump light brown melomys})
  insert(:name, %{plump brown melomys})
  insert(:name, %{blunt-nosed dark brown melomys})
  insert(:name, %{blunt-nosed dark grey melomys})
  insert(:name, %{blunt-nosed chocolate brown melomys})
  insert(:name, %{blunt-nosed inky black melomys})
  insert(:name, %{blunt-nosed burnt umber melomys})
  insert(:name, %{blunt-nosed auburn melomys})
  insert(:name, %{blunt-nosed albino melomys})
  insert(:name, %{blunt-nosed russet melomys})
  insert(:name, %{blunt-nosed dusty brown melomys})
  insert(:name, %{blunt-nosed light brown melomys})
  insert(:name, %{blunt-nosed brown melomys})
  insert(:name, %{fluffy dark brown melomys})
  insert(:name, %{fluffy dark grey melomys})
  insert(:name, %{fluffy chocolate brown melomys})
  insert(:name, %{fluffy inky black melomys})
  insert(:name, %{fluffy burnt umber melomys})
  insert(:name, %{fluffy auburn melomys})
  insert(:name, %{fluffy albino melomys})
  insert(:name, %{fluffy russet melomys})
  insert(:name, %{fluffy dusty brown melomys})
  insert(:name, %{fluffy light brown melomys})
  insert(:name, %{fluffy brown melomys})
  insert(:name, %{pointy-faced dark brown melomys})
  insert(:name, %{pointy-faced dark grey melomys})
  insert(:name, %{pointy-faced chocolate brown melomys})
  insert(:name, %{pointy-faced inky black melomys})
  insert(:name, %{pointy-faced burnt umber melomys})
  insert(:name, %{pointy-faced auburn melomys})
  insert(:name, %{pointy-faced albino melomys})
  insert(:name, %{pointy-faced russet melomys})
  insert(:name, %{pointy-faced dusty brown melomys})
  insert(:name, %{pointy-faced light brown melomys})
  insert(:name, %{pointy-faced brown melomys})
  insert(:name, %{beady-eyed dark brown melomys})
  insert(:name, %{beady-eyed dark grey melomys})
  insert(:name, %{beady-eyed chocolate brown melomys})
  insert(:name, %{beady-eyed inky black melomys})
  insert(:name, %{beady-eyed burnt umber melomys})
  insert(:name, %{beady-eyed auburn melomys})
  insert(:name, %{beady-eyed albino melomys})
  insert(:name, %{beady-eyed russet melomys})
  insert(:name, %{beady-eyed dusty brown melomys})
  insert(:name, %{beady-eyed light brown melomys})
  insert(:name, %{beady-eyed brown melomys})
  insert(:name, %{fuzzy-faced dark brown melomys})
  insert(:name, %{fuzzy-faced dark grey melomys})
  insert(:name, %{fuzzy-faced chocolate brown melomys})
  insert(:name, %{fuzzy-faced inky black melomys})
  insert(:name, %{fuzzy-faced burnt umber melomys})
  insert(:name, %{fuzzy-faced auburn melomys})
  insert(:name, %{fuzzy-faced albino melomys})
  insert(:name, %{fuzzy-faced russet melomys})
  insert(:name, %{fuzzy-faced dusty brown melomys})
  insert(:name, %{fuzzy-faced light brown melomys})
  insert(:name, %{fuzzy-faced brown melomys})
  insert(:name, %{pink-eyed dark brown melomys})
  insert(:name, %{pink-eyed dark grey melomys})
  insert(:name, %{pink-eyed chocolate brown melomys})
  insert(:name, %{pink-eyed inky black melomys})
  insert(:name, %{pink-eyed burnt umber melomys})
  insert(:name, %{pink-eyed auburn melomys})
  insert(:name, %{pink-eyed albino melomys})
  insert(:name, %{pink-eyed russet melomys})
  insert(:name, %{pink-eyed dusty brown melomys})
  insert(:name, %{pink-eyed light brown melomys})
  insert(:name, %{pink-eyed brown melomys})
  insert(:name, %{ebon-eyed dark brown melomys})
  insert(:name, %{ebon-eyed dark grey melomys})
  insert(:name, %{ebon-eyed chocolate brown melomys})
  insert(:name, %{ebon-eyed inky black melomys})
  insert(:name, %{ebon-eyed burnt umber melomys})
  insert(:name, %{ebon-eyed auburn melomys})
  insert(:name, %{ebon-eyed albino melomys})
  insert(:name, %{ebon-eyed russet melomys})
  insert(:name, %{ebon-eyed dusty brown melomys})
  insert(:name, %{ebon-eyed light brown melomys})
  insert(:name, %{ebon-eyed brown melomys})
  insert(:name, %{long-tailed dark brown melomys})
  insert(:name, %{long-tailed dark grey melomys})
  insert(:name, %{long-tailed chocolate brown melomys})
  insert(:name, %{long-tailed inky black melomys})
  insert(:name, %{long-tailed burnt umber melomys})
  insert(:name, %{long-tailed auburn melomys})
  insert(:name, %{long-tailed albino melomys})
  insert(:name, %{long-tailed russet melomys})
  insert(:name, %{long-tailed dusty brown melomys})
  insert(:name, %{long-tailed light brown melomys})
  insert(:name, %{long-tailed brown melomys})
  insert(:name, %{slim dove grey merlin})
  insert(:name, %{mouse})
  insert(:name, %{black mouse})
  insert(:name, %{brown mouse})
  insert(:name, %{field mouse})
  insert(:name, %{forest mouse})
  insert(:name, %{furry mouse})
  insert(:name, %{pocket mouse})
  insert(:name, %{grey mouse})
  insert(:name, %{white mouse})
  insert(:name, %{fat mouse})
  insert(:name, %{fat black mouse})
  insert(:name, %{fat brown mouse})
  insert(:name, %{fat field mouse})
  insert(:name, %{fat forest mouse})
  insert(:name, %{fat furry mouse})
  insert(:name, %{fat pocket mouse})
  insert(:name, %{fat grey mouse})
  insert(:name, %{fat white mouse})
  insert(:name, %{plump mouse})
  insert(:name, %{plump black mouse})
  insert(:name, %{plump brown mouse})
  insert(:name, %{plump field mouse})
  insert(:name, %{plump forest mouse})
  insert(:name, %{plump furry mouse})
  insert(:name, %{plump pocket mouse})
  insert(:name, %{plump grey mouse})
  insert(:name, %{plump white mouse})
  insert(:name, %{sleek mouse})
  insert(:name, %{sleek black mouse})
  insert(:name, %{sleek brown mouse})
  insert(:name, %{sleek field mouse})
  insert(:name, %{sleek forest mouse})
  insert(:name, %{sleek furry mouse})
  insert(:name, %{sleek pocket mouse})
  insert(:name, %{sleek grey mouse})
  insert(:name, %{sleek white mouse})
  insert(:name, %{tiny mouse})
  insert(:name, %{tiny black mouse})
  insert(:name, %{tiny brown mouse})
  insert(:name, %{tiny field mouse})
  insert(:name, %{tiny forest mouse})
  insert(:name, %{tiny furry mouse})
  insert(:name, %{tiny pocket mouse})
  insert(:name, %{tiny grey mouse})
  insert(:name, %{tiny white mouse})
  insert(:name, %{barn owl})
  insert(:name, %{pygmy owl})
  insert(:name, %{barred owl})
  insert(:name, %{screech owl})
  insert(:name, %{bay owl})
  insert(:name, %{snowy owl})
  insert(:name, %{crested owl})
  insert(:name, %{sooty owl})
  insert(:name, %{eagle owl})
  insert(:name, %{speckled owl})
  insert(:name, %{elf owl})
  insert(:name, %{spectacled owl})
  insert(:name, %{grass owl})
  insert(:name, %{spotted owl})
  insert(:name, %{great white owl})
  insert(:name, %{striped owl})
  insert(:name, %{grey owl})
  insert(:name, %{tawny owl})
  insert(:name, %{hawk owl})
  insert(:name, %{white owl})
  insert(:name, %{horned owl})
  insert(:name, %{white-faced owl})
  insert(:name, %{maned owl})
  insert(:name, %{wood owl})
  insert(:name, %{masked owl})
  insert(:name, %{greater barn owl})
  insert(:name, %{greater pygmy owl})
  insert(:name, %{greater barred owl})
  insert(:name, %{greater screech owl})
  insert(:name, %{greater bay owl})
  insert(:name, %{greater snowy owl})
  insert(:name, %{greater crested owl})
  insert(:name, %{greater sooty owl})
  insert(:name, %{greater eagle owl})
  insert(:name, %{greater speckled owl})
  insert(:name, %{greater elf owl})
  insert(:name, %{greater spectacled owl})
  insert(:name, %{greater grass owl})
  insert(:name, %{greater spotted owl})
  insert(:name, %{greater great white owl})
  insert(:name, %{greater striped owl})
  insert(:name, %{greater grey owl})
  insert(:name, %{greater tawny owl})
  insert(:name, %{greater hawk owl})
  insert(:name, %{greater white owl})
  insert(:name, %{greater horned owl})
  insert(:name, %{greater white-faced owl})
  insert(:name, %{greater maned owl})
  insert(:name, %{greater wood owl})
  insert(:name, %{greater masked owl})
  insert(:name, %{lesser barn owl})
  insert(:name, %{lesser pygmy owl})
  insert(:name, %{lesser barred owl})
  insert(:name, %{lesser screech owl})
  insert(:name, %{lesser bay owl})
  insert(:name, %{lesser snowy owl})
  insert(:name, %{lesser crested owl})
  insert(:name, %{lesser sooty owl})
  insert(:name, %{lesser eagle owl})
  insert(:name, %{lesser speckled owl})
  insert(:name, %{lesser elf owl})
  insert(:name, %{lesser spectacled owl})
  insert(:name, %{lesser grass owl})
  insert(:name, %{lesser spotted owl})
  insert(:name, %{lesser great white owl})
  insert(:name, %{lesser striped owl})
  insert(:name, %{lesser grey owl})
  insert(:name, %{lesser tawny owl})
  insert(:name, %{lesser hawk owl})
  insert(:name, %{lesser white owl})
  insert(:name, %{lesser horned owl})
  insert(:name, %{lesser white-faced owl})
  insert(:name, %{lesser maned owl})
  insert(:name, %{lesser wood owl})
  insert(:name, %{lesser masked owl})
  insert(:name, %{ruffled barn owl})
  insert(:name, %{ruffled pygmy owl})
  insert(:name, %{ruffled barred owl})
  insert(:name, %{ruffled screech owl})
  insert(:name, %{ruffled bay owl})
  insert(:name, %{ruffled snowy owl})
  insert(:name, %{ruffled crested owl})
  insert(:name, %{ruffled sooty owl})
  insert(:name, %{ruffled eagle owl})
  insert(:name, %{ruffled speckled owl})
  insert(:name, %{ruffled elf owl})
  insert(:name, %{ruffled spectacled owl})
  insert(:name, %{ruffled grass owl})
  insert(:name, %{ruffled spotted owl})
  insert(:name, %{ruffled great white owl})
  insert(:name, %{ruffled striped owl})
  insert(:name, %{ruffled grey owl})
  insert(:name, %{ruffled tawny owl})
  insert(:name, %{ruffled hawk owl})
  insert(:name, %{ruffled white owl})
  insert(:name, %{ruffled horned owl})
  insert(:name, %{ruffled white-faced owl})
  insert(:name, %{ruffled maned owl})
  insert(:name, %{ruffled wood owl})
  insert(:name, %{ruffled masked owl})
  insert(:name, %{sleek barn owl})
  insert(:name, %{sleek pygmy owl})
  insert(:name, %{sleek barred owl})
  insert(:name, %{sleek screech owl})
  insert(:name, %{sleek bay owl})
  insert(:name, %{sleek snowy owl})
  insert(:name, %{sleek crested owl})
  insert(:name, %{sleek sooty owl})
  insert(:name, %{sleek eagle owl})
  insert(:name, %{sleek speckled owl})
  insert(:name, %{sleek elf owl})
  insert(:name, %{sleek spectacled owl})
  insert(:name, %{sleek grass owl})
  insert(:name, %{sleek spotted owl})
  insert(:name, %{sleek great white owl})
  insert(:name, %{sleek striped owl})
  insert(:name, %{sleek grey owl})
  insert(:name, %{sleek tawny owl})
  insert(:name, %{sleek hawk owl})
  insert(:name, %{sleek white owl})
  insert(:name, %{sleek horned owl})
  insert(:name, %{sleek white-faced owl})
  insert(:name, %{sleek maned owl})
  insert(:name, %{sleek wood owl})
  insert(:name, %{sleek masked owl})
  insert(:name, %{pale-faced barn owl})
  insert(:name, %{pale-faced pygmy owl})
  insert(:name, %{pale-faced barred owl})
  insert(:name, %{pale-faced screech owl})
  insert(:name, %{pale-faced bay owl})
  insert(:name, %{pale-faced snowy owl})
  insert(:name, %{pale-faced crested owl})
  insert(:name, %{pale-faced sooty owl})
  insert(:name, %{pale-faced eagle owl})
  insert(:name, %{pale-faced speckled owl})
  insert(:name, %{pale-faced elf owl})
  insert(:name, %{pale-faced spectacled owl})
  insert(:name, %{pale-faced grass owl})
  insert(:name, %{pale-faced spotted owl})
  insert(:name, %{pale-faced great white owl})
  insert(:name, %{pale-faced striped owl})
  insert(:name, %{pale-faced grey owl})
  insert(:name, %{pale-faced tawny owl})
  insert(:name, %{pale-faced hawk owl})
  insert(:name, %{pale-faced white owl})
  insert(:name, %{pale-faced horned owl})
  insert(:name, %{pale-faced white-faced owl})
  insert(:name, %{pale-faced maned owl})
  insert(:name, %{pale-faced wood owl})
  insert(:name, %{pale-faced masked owl})
  insert(:name, %{dark-eyed grey barred owl})
  insert(:name, %{deep green parakeet})
  insert(:name, %{grass green parakeet})
  insert(:name, %{jade green parakeet})
  insert(:name, %{soft white parakeet})
  insert(:name, %{sky blue parakeet})
  insert(:name, %{dusky rose parakeet})
  insert(:name, %{dusky grey parakeet})
  insert(:name, %{brown-banded deep green parakeet})
  insert(:name, %{brown-banded grass green parakeet})
  insert(:name, %{brown-banded jade green parakeet})
  insert(:name, %{brown-banded soft white parakeet})
  insert(:name, %{brown-banded sky blue parakeet})
  insert(:name, %{brown-banded dusky rose parakeet})
  insert(:name, %{brown-banded dusky grey parakeet})
  insert(:name, %{yellow-necked deep green parakeet})
  insert(:name, %{yellow-necked grass green parakeet})
  insert(:name, %{yellow-necked jade green parakeet})
  insert(:name, %{yellow-necked soft white parakeet})
  insert(:name, %{yellow-necked sky blue parakeet})
  insert(:name, %{yellow-necked dusky rose parakeet})
  insert(:name, %{yellow-necked dusky grey parakeet})
  insert(:name, %{grey-winged deep green parakeet})
  insert(:name, %{grey-winged grass green parakeet})
  insert(:name, %{grey-winged jade green parakeet})
  insert(:name, %{grey-winged soft white parakeet})
  insert(:name, %{grey-winged sky blue parakeet})
  insert(:name, %{grey-winged dusky rose parakeet})
  insert(:name, %{grey-winged dusky grey parakeet})
  insert(:name, %{yellow-headed deep green parakeet})
  insert(:name, %{yellow-headed grass green parakeet})
  insert(:name, %{yellow-headed jade green parakeet})
  insert(:name, %{yellow-headed soft white parakeet})
  insert(:name, %{yellow-headed sky blue parakeet})
  insert(:name, %{yellow-headed dusky rose parakeet})
  insert(:name, %{yellow-headed dusky grey parakeet})
  insert(:name, %{plum-headed deep green parakeet})
  insert(:name, %{plum-headed grass green parakeet})
  insert(:name, %{plum-headed jade green parakeet})
  insert(:name, %{plum-headed soft white parakeet})
  insert(:name, %{plum-headed sky blue parakeet})
  insert(:name, %{plum-headed dusky rose parakeet})
  insert(:name, %{plum-headed dusky grey parakeet})
  insert(:name, %{celadon deep green parakeet})
  insert(:name, %{celadon grass green parakeet})
  insert(:name, %{celadon jade green parakeet})
  insert(:name, %{celadon soft white parakeet})
  insert(:name, %{celadon sky blue parakeet})
  insert(:name, %{celadon dusky rose parakeet})
  insert(:name, %{celadon dusky grey parakeet})
  insert(:name, %{brown pelican})
  insert(:name, %{pink-backed pelican})
  insert(:name, %{white pelican})
  insert(:name, %{spot-billed pelican})
  insert(:name, %{large brown pelican})
  insert(:name, %{large pink-backed pelican})
  insert(:name, %{large white pelican})
  insert(:name, %{large spot-billed pelican})
  insert(:name, %{ruffled brown pelican})
  insert(:name, %{ruffled pink-backed pelican})
  insert(:name, %{ruffled white pelican})
  insert(:name, %{ruffled spot-billed pelican})
  insert(:name, %{small brown pelican})
  insert(:name, %{small pink-backed pelican})
  insert(:name, %{small white pelican})
  insert(:name, %{small spot-billed pelican})
  insert(:name, %{sleek brown pelican})
  insert(:name, %{sleek pink-backed pelican})
  insert(:name, %{sleek white pelican})
  insert(:name, %{sleek spot-billed pelican})
  insert(:name, %{crested penguin})
  insert(:name, %{emperor penguin})
  insert(:name, %{king penguin})
  insert(:name, %{royal penguin})
  insert(:name, %{yellow-eyed penguin})
  insert(:name, %{little blue penguin})
  insert(:name, %{rusty pitohui})
  insert(:name, %{hooded pitohui})
  insert(:name, %{red-brown pitohui})
  insert(:name, %{black pitohui})
  insert(:name, %{brown pitohui})
  insert(:name, %{crested pitohui})
  insert(:name, %{rock ptarmigan})
  insert(:name, %{peacock blue pygmy-parrot})
  insert(:name, %{bright yellow pygmy-parrot})
  insert(:name, %{deep green pygmy-parrot})
  insert(:name, %{celadon pygmy-parrot})
  insert(:name, %{emerald pygmy-parrot})
  insert(:name, %{indigo pygmy-parrot})
  insert(:name, %{pale green pygmy-parrot})
  insert(:name, %{viridian pygmy-parrot})
  insert(:name, %{blunt-faced peacock blue pygmy-parrot})
  insert(:name, %{blunt-faced bright yellow pygmy-parrot})
  insert(:name, %{blunt-faced deep green pygmy-parrot})
  insert(:name, %{blunt-faced celadon pygmy-parrot})
  insert(:name, %{blunt-faced emerald pygmy-parrot})
  insert(:name, %{blunt-faced indigo pygmy-parrot})
  insert(:name, %{blunt-faced pale green pygmy-parrot})
  insert(:name, %{blunt-faced viridian pygmy-parrot})
  insert(:name, %{yellow-capped peacock blue pygmy-parrot})
  insert(:name, %{yellow-capped bright yellow pygmy-parrot})
  insert(:name, %{yellow-capped deep green pygmy-parrot})
  insert(:name, %{yellow-capped celadon pygmy-parrot})
  insert(:name, %{yellow-capped emerald pygmy-parrot})
  insert(:name, %{yellow-capped indigo pygmy-parrot})
  insert(:name, %{yellow-capped pale green pygmy-parrot})
  insert(:name, %{yellow-capped viridian pygmy-parrot})
  insert(:name, %{puff-faced peacock blue pygmy-parrot})
  insert(:name, %{puff-faced bright yellow pygmy-parrot})
  insert(:name, %{puff-faced deep green pygmy-parrot})
  insert(:name, %{puff-faced celadon pygmy-parrot})
  insert(:name, %{puff-faced emerald pygmy-parrot})
  insert(:name, %{puff-faced indigo pygmy-parrot})
  insert(:name, %{puff-faced pale green pygmy-parrot})
  insert(:name, %{puff-faced viridian pygmy-parrot})
  insert(:name, %{croak-beaked peacock blue pygmy-parrot})
  insert(:name, %{croak-beaked bright yellow pygmy-parrot})
  insert(:name, %{croak-beaked deep green pygmy-parrot})
  insert(:name, %{croak-beaked celadon pygmy-parrot})
  insert(:name, %{croak-beaked emerald pygmy-parrot})
  insert(:name, %{croak-beaked indigo pygmy-parrot})
  insert(:name, %{croak-beaked pale green pygmy-parrot})
  insert(:name, %{croak-beaked viridian pygmy-parrot})
  insert(:name, %{brown-faced peacock blue pygmy-parrot})
  insert(:name, %{brown-faced bright yellow pygmy-parrot})
  insert(:name, %{brown-faced deep green pygmy-parrot})
  insert(:name, %{brown-faced celadon pygmy-parrot})
  insert(:name, %{brown-faced emerald pygmy-parrot})
  insert(:name, %{brown-faced indigo pygmy-parrot})
  insert(:name, %{brown-faced pale green pygmy-parrot})
  insert(:name, %{brown-faced viridian pygmy-parrot})
  insert(:name, %{ruby-bellied peacock blue pygmy-parrot})
  insert(:name, %{ruby-bellied bright yellow pygmy-parrot})
  insert(:name, %{ruby-bellied deep green pygmy-parrot})
  insert(:name, %{ruby-bellied celadon pygmy-parrot})
  insert(:name, %{ruby-bellied emerald pygmy-parrot})
  insert(:name, %{ruby-bellied indigo pygmy-parrot})
  insert(:name, %{ruby-bellied pale green pygmy-parrot})
  insert(:name, %{ruby-bellied viridian pygmy-parrot})
  insert(:name, %{umber-faced peacock blue pygmy-parrot})
  insert(:name, %{umber-faced bright yellow pygmy-parrot})
  insert(:name, %{umber-faced deep green pygmy-parrot})
  insert(:name, %{umber-faced celadon pygmy-parrot})
  insert(:name, %{umber-faced emerald pygmy-parrot})
  insert(:name, %{umber-faced indigo pygmy-parrot})
  insert(:name, %{umber-faced pale green pygmy-parrot})
  insert(:name, %{umber-faced viridian pygmy-parrot})
  insert(:name, %{white-bellied peacock blue pygmy-parrot})
  insert(:name, %{white-bellied bright yellow pygmy-parrot})
  insert(:name, %{white-bellied deep green pygmy-parrot})
  insert(:name, %{white-bellied celadon pygmy-parrot})
  insert(:name, %{white-bellied emerald pygmy-parrot})
  insert(:name, %{white-bellied indigo pygmy-parrot})
  insert(:name, %{white-bellied pale green pygmy-parrot})
  insert(:name, %{white-bellied viridian pygmy-parrot})
  insert(:name, %{ebon-faced peacock blue pygmy-parrot})
  insert(:name, %{ebon-faced bright yellow pygmy-parrot})
  insert(:name, %{ebon-faced deep green pygmy-parrot})
  insert(:name, %{ebon-faced celadon pygmy-parrot})
  insert(:name, %{ebon-faced emerald pygmy-parrot})
  insert(:name, %{ebon-faced indigo pygmy-parrot})
  insert(:name, %{ebon-faced pale green pygmy-parrot})
  insert(:name, %{ebon-faced viridian pygmy-parrot})
  insert(:name, %{raven})
  insert(:name, %{large raven})
  insert(:name, %{ruffled raven})
  insert(:name, %{small raven})
  insert(:name, %{sleek raven})
  insert(:name, %{glossy coal black raven})
  insert(:name, %{squat pebble-backed toad})
  insert(:name, %{jade green serpent})
  insert(:name, %{dark brown serpent})
  insert(:name, %{emerald serpent})
  insert(:name, %{pale grey serpent})
  insert(:name, %{leaf green serpent})
  insert(:name, %{dark grey serpent})
  insert(:name, %{dusty green serpent})
  insert(:name, %{diamond-scaled serpent})
  insert(:name, %{grass green serpent})
  insert(:name, %{teardrop-scaled serpent})
  insert(:name, %{ruby serpent})
  insert(:name, %{white-banded serpent})
  insert(:name, %{coral-banded serpent})
  insert(:name, %{sinuous jade green serpent})
  insert(:name, %{sinuous dark brown serpent})
  insert(:name, %{sinuous emerald serpent})
  insert(:name, %{sinuous pale grey serpent})
  insert(:name, %{sinuous leaf green serpent})
  insert(:name, %{sinuous dark grey serpent})
  insert(:name, %{sinuous dusty green serpent})
  insert(:name, %{sinuous diamond-scaled serpent})
  insert(:name, %{sinuous grass green serpent})
  insert(:name, %{sinuous teardrop-scaled serpent})
  insert(:name, %{sinuous ruby serpent})
  insert(:name, %{sinuous white-banded serpent})
  insert(:name, %{sinuous coral-banded serpent})
  insert(:name, %{white-bellied jade green serpent})
  insert(:name, %{white-bellied dark brown serpent})
  insert(:name, %{white-bellied emerald serpent})
  insert(:name, %{white-bellied pale grey serpent})
  insert(:name, %{white-bellied leaf green serpent})
  insert(:name, %{white-bellied dark grey serpent})
  insert(:name, %{white-bellied dusty green serpent})
  insert(:name, %{white-bellied diamond-scaled serpent})
  insert(:name, %{white-bellied grass green serpent})
  insert(:name, %{white-bellied teardrop-scaled serpent})
  insert(:name, %{white-bellied ruby serpent})
  insert(:name, %{white-bellied white-banded serpent})
  insert(:name, %{white-bellied coral-banded serpent})
  insert(:name, %{slender jade green serpent})
  insert(:name, %{slender dark brown serpent})
  insert(:name, %{slender emerald serpent})
  insert(:name, %{slender pale grey serpent})
  insert(:name, %{slender leaf green serpent})
  insert(:name, %{slender dark grey serpent})
  insert(:name, %{slender dusty green serpent})
  insert(:name, %{slender diamond-scaled serpent})
  insert(:name, %{slender grass green serpent})
  insert(:name, %{slender teardrop-scaled serpent})
  insert(:name, %{slender ruby serpent})
  insert(:name, %{slender white-banded serpent})
  insert(:name, %{slender coral-banded serpent})
  insert(:name, %{wide-bodied jade green serpent})
  insert(:name, %{wide-bodied dark brown serpent})
  insert(:name, %{wide-bodied emerald serpent})
  insert(:name, %{wide-bodied pale grey serpent})
  insert(:name, %{wide-bodied leaf green serpent})
  insert(:name, %{wide-bodied dark grey serpent})
  insert(:name, %{wide-bodied dusty green serpent})
  insert(:name, %{wide-bodied diamond-scaled serpent})
  insert(:name, %{wide-bodied grass green serpent})
  insert(:name, %{wide-bodied teardrop-scaled serpent})
  insert(:name, %{wide-bodied ruby serpent})
  insert(:name, %{wide-bodied white-banded serpent})
  insert(:name, %{wide-bodied coral-banded serpent})
  insert(:name, %{tiny jade green serpent})
  insert(:name, %{tiny dark brown serpent})
  insert(:name, %{tiny emerald serpent})
  insert(:name, %{tiny pale grey serpent})
  insert(:name, %{tiny leaf green serpent})
  insert(:name, %{tiny dark grey serpent})
  insert(:name, %{tiny dusty green serpent})
  insert(:name, %{tiny diamond-scaled serpent})
  insert(:name, %{tiny grass green serpent})
  insert(:name, %{tiny teardrop-scaled serpent})
  insert(:name, %{tiny ruby serpent})
  insert(:name, %{tiny white-banded serpent})
  insert(:name, %{tiny coral-banded serpent})
  insert(:name, %{onyx-bellied jade green serpent})
  insert(:name, %{onyx-bellied dark brown serpent})
  insert(:name, %{onyx-bellied emerald serpent})
  insert(:name, %{onyx-bellied pale grey serpent})
  insert(:name, %{onyx-bellied leaf green serpent})
  insert(:name, %{onyx-bellied dark grey serpent})
  insert(:name, %{onyx-bellied dusty green serpent})
  insert(:name, %{onyx-bellied diamond-scaled serpent})
  insert(:name, %{onyx-bellied grass green serpent})
  insert(:name, %{onyx-bellied teardrop-scaled serpent})
  insert(:name, %{onyx-bellied ruby serpent})
  insert(:name, %{onyx-bellied white-banded serpent})
  insert(:name, %{onyx-bellied coral-banded serpent})
  insert(:name, %{spotted jade green serpent})
  insert(:name, %{spotted dark brown serpent})
  insert(:name, %{spotted emerald serpent})
  insert(:name, %{spotted pale grey serpent})
  insert(:name, %{spotted leaf green serpent})
  insert(:name, %{spotted dark grey serpent})
  insert(:name, %{spotted dusty green serpent})
  insert(:name, %{spotted diamond-scaled serpent})
  insert(:name, %{spotted grass green serpent})
  insert(:name, %{spotted teardrop-scaled serpent})
  insert(:name, %{spotted ruby serpent})
  insert(:name, %{spotted white-banded serpent})
  insert(:name, %{spotted coral-banded serpent})
  insert(:name, %{wide-headed jade green serpent})
  insert(:name, %{wide-headed dark brown serpent})
  insert(:name, %{wide-headed emerald serpent})
  insert(:name, %{wide-headed pale grey serpent})
  insert(:name, %{wide-headed leaf green serpent})
  insert(:name, %{wide-headed dark grey serpent})
  insert(:name, %{wide-headed dusty green serpent})
  insert(:name, %{wide-headed diamond-scaled serpent})
  insert(:name, %{wide-headed grass green serpent})
  insert(:name, %{wide-headed teardrop-scaled serpent})
  insert(:name, %{wide-headed ruby serpent})
  insert(:name, %{wide-headed white-banded serpent})
  insert(:name, %{wide-headed coral-banded serpent})
  insert(:name, %{plain jade green serpent})
  insert(:name, %{plain dark brown serpent})
  insert(:name, %{plain emerald serpent})
  insert(:name, %{plain pale grey serpent})
  insert(:name, %{plain leaf green serpent})
  insert(:name, %{plain dark grey serpent})
  insert(:name, %{plain dusty green serpent})
  insert(:name, %{plain diamond-scaled serpent})
  insert(:name, %{plain grass green serpent})
  insert(:name, %{plain teardrop-scaled serpent})
  insert(:name, %{plain ruby serpent})
  insert(:name, %{plain white-banded serpent})
  insert(:name, %{plain coral-banded serpent})
  insert(:name, %{flat-headed jade green serpent})
  insert(:name, %{flat-headed dark brown serpent})
  insert(:name, %{flat-headed emerald serpent})
  insert(:name, %{flat-headed pale grey serpent})
  insert(:name, %{flat-headed leaf green serpent})
  insert(:name, %{flat-headed dark grey serpent})
  insert(:name, %{flat-headed dusty green serpent})
  insert(:name, %{flat-headed diamond-scaled serpent})
  insert(:name, %{flat-headed grass green serpent})
  insert(:name, %{flat-headed teardrop-scaled serpent})
  insert(:name, %{flat-headed ruby serpent})
  insert(:name, %{flat-headed white-banded serpent})
  insert(:name, %{flat-headed coral-banded serpent})
  insert(:name, %{blunt-nosed jade green serpent})
  insert(:name, %{blunt-nosed dark brown serpent})
  insert(:name, %{blunt-nosed emerald serpent})
  insert(:name, %{blunt-nosed pale grey serpent})
  insert(:name, %{blunt-nosed leaf green serpent})
  insert(:name, %{blunt-nosed dark grey serpent})
  insert(:name, %{blunt-nosed dusty green serpent})
  insert(:name, %{blunt-nosed diamond-scaled serpent})
  insert(:name, %{blunt-nosed grass green serpent})
  insert(:name, %{blunt-nosed teardrop-scaled serpent})
  insert(:name, %{blunt-nosed ruby serpent})
  insert(:name, %{blunt-nosed white-banded serpent})
  insert(:name, %{blunt-nosed coral-banded serpent})
  insert(:name, %{slit-eyed jade green serpent})
  insert(:name, %{slit-eyed dark brown serpent})
  insert(:name, %{slit-eyed emerald serpent})
  insert(:name, %{slit-eyed pale grey serpent})
  insert(:name, %{slit-eyed leaf green serpent})
  insert(:name, %{slit-eyed dark grey serpent})
  insert(:name, %{slit-eyed dusty green serpent})
  insert(:name, %{slit-eyed diamond-scaled serpent})
  insert(:name, %{slit-eyed grass green serpent})
  insert(:name, %{slit-eyed teardrop-scaled serpent})
  insert(:name, %{slit-eyed ruby serpent})
  insert(:name, %{slit-eyed white-banded serpent})
  insert(:name, %{slit-eyed coral-banded serpent})
  insert(:name, %{fork-tongued jade green serpent})
  insert(:name, %{fork-tongued dark brown serpent})
  insert(:name, %{fork-tongued emerald serpent})
  insert(:name, %{fork-tongued pale grey serpent})
  insert(:name, %{fork-tongued leaf green serpent})
  insert(:name, %{fork-tongued dark grey serpent})
  insert(:name, %{fork-tongued dusty green serpent})
  insert(:name, %{fork-tongued diamond-scaled serpent})
  insert(:name, %{fork-tongued grass green serpent})
  insert(:name, %{fork-tongued teardrop-scaled serpent})
  insert(:name, %{fork-tongued ruby serpent})
  insert(:name, %{fork-tongued white-banded serpent})
  insert(:name, %{fork-tongued coral-banded serpent})
  insert(:name, %{dusky grey sugar-glider})
  insert(:name, %{straw yellow sugar-glider})
  insert(:name, %{albino white sugar-glider})
  insert(:name, %{pale brown sugar-glider})
  insert(:name, %{dusty brown sugar-glider})
  insert(:name, %{sandy brown sugar-glider})
  insert(:name, %{fuzzy brown sugar-glider})
  insert(:name, %{white-bellied sugar-glider})
  insert(:name, %{dusty yellow sugar-glider})
  insert(:name, %{fuzzy dusky grey sugar-glider})
  insert(:name, %{fuzzy straw yellow sugar-glider})
  insert(:name, %{fuzzy albino white sugar-glider})
  insert(:name, %{fuzzy pale brown sugar-glider})
  insert(:name, %{fuzzy dusty brown sugar-glider})
  insert(:name, %{fuzzy sandy brown sugar-glider})
  insert(:name, %{fuzzy fuzzy brown sugar-glider})
  insert(:name, %{fuzzy white-bellied sugar-glider})
  insert(:name, %{fuzzy dusty yellow sugar-glider})
  insert(:name, %{pink-eared dusky grey sugar-glider})
  insert(:name, %{pink-eared straw yellow sugar-glider})
  insert(:name, %{pink-eared albino white sugar-glider})
  insert(:name, %{pink-eared pale brown sugar-glider})
  insert(:name, %{pink-eared dusty brown sugar-glider})
  insert(:name, %{pink-eared sandy brown sugar-glider})
  insert(:name, %{pink-eared fuzzy brown sugar-glider})
  insert(:name, %{pink-eared white-bellied sugar-glider})
  insert(:name, %{pink-eared dusty yellow sugar-glider})
  insert(:name, %{whiskered dusky grey sugar-glider})
  insert(:name, %{whiskered straw yellow sugar-glider})
  insert(:name, %{whiskered albino white sugar-glider})
  insert(:name, %{whiskered pale brown sugar-glider})
  insert(:name, %{whiskered dusty brown sugar-glider})
  insert(:name, %{whiskered sandy brown sugar-glider})
  insert(:name, %{whiskered fuzzy brown sugar-glider})
  insert(:name, %{whiskered white-bellied sugar-glider})
  insert(:name, %{whiskered dusty yellow sugar-glider})
  insert(:name, %{plump-cheeked dusky grey sugar-glider})
  insert(:name, %{plump-cheeked straw yellow sugar-glider})
  insert(:name, %{plump-cheeked albino white sugar-glider})
  insert(:name, %{plump-cheeked pale brown sugar-glider})
  insert(:name, %{plump-cheeked dusty brown sugar-glider})
  insert(:name, %{plump-cheeked sandy brown sugar-glider})
  insert(:name, %{plump-cheeked fuzzy brown sugar-glider})
  insert(:name, %{plump-cheeked white-bellied sugar-glider})
  insert(:name, %{plump-cheeked dusty yellow sugar-glider})
  insert(:name, %{bug-eyed dusky grey sugar-glider})
  insert(:name, %{bug-eyed straw yellow sugar-glider})
  insert(:name, %{bug-eyed albino white sugar-glider})
  insert(:name, %{bug-eyed pale brown sugar-glider})
  insert(:name, %{bug-eyed dusty brown sugar-glider})
  insert(:name, %{bug-eyed sandy brown sugar-glider})
  insert(:name, %{bug-eyed fuzzy brown sugar-glider})
  insert(:name, %{bug-eyed white-bellied sugar-glider})
  insert(:name, %{bug-eyed dusty yellow sugar-glider})
  insert(:name, %{pot-bellied dusky grey sugar-glider})
  insert(:name, %{pot-bellied straw yellow sugar-glider})
  insert(:name, %{pot-bellied albino white sugar-glider})
  insert(:name, %{pot-bellied pale brown sugar-glider})
  insert(:name, %{pot-bellied dusty brown sugar-glider})
  insert(:name, %{pot-bellied sandy brown sugar-glider})
  insert(:name, %{pot-bellied fuzzy brown sugar-glider})
  insert(:name, %{pot-bellied white-bellied sugar-glider})
  insert(:name, %{pot-bellied dusty yellow sugar-glider})
  insert(:name, %{pink-faced dusky grey sugar-glider})
  insert(:name, %{pink-faced straw yellow sugar-glider})
  insert(:name, %{pink-faced albino white sugar-glider})
  insert(:name, %{pink-faced pale brown sugar-glider})
  insert(:name, %{pink-faced dusty brown sugar-glider})
  insert(:name, %{pink-faced sandy brown sugar-glider})
  insert(:name, %{pink-faced fuzzy brown sugar-glider})
  insert(:name, %{pink-faced white-bellied sugar-glider})
  insert(:name, %{pink-faced dusty yellow sugar-glider})
  insert(:name, %{dusky brown tamarin})
  insert(:name, %{dark grey tamarin})
  insert(:name, %{fuzzy brown tamarin})
  insert(:name, %{fuzzy grey tamarin})
  insert(:name, %{light brown tamarin})
  insert(:name, %{burnished grey tamarin})
  insert(:name, %{dusty brown tamarin})
  insert(:name, %{burnished red tamarin})
  insert(:name, %{golden red tamarin})
  insert(:name, %{white-maned dusky brown tamarin})
  insert(:name, %{white-maned dark grey tamarin})
  insert(:name, %{white-maned fuzzy brown tamarin})
  insert(:name, %{white-maned fuzzy grey tamarin})
  insert(:name, %{white-maned light brown tamarin})
  insert(:name, %{white-maned burnished grey tamarin})
  insert(:name, %{white-maned dusty brown tamarin})
  insert(:name, %{white-maned burnished red tamarin})
  insert(:name, %{white-maned golden red tamarin})
  insert(:name, %{pink-cheeked dusky brown tamarin})
  insert(:name, %{pink-cheeked dark grey tamarin})
  insert(:name, %{pink-cheeked fuzzy brown tamarin})
  insert(:name, %{pink-cheeked fuzzy grey tamarin})
  insert(:name, %{pink-cheeked light brown tamarin})
  insert(:name, %{pink-cheeked burnished grey tamarin})
  insert(:name, %{pink-cheeked dusty brown tamarin})
  insert(:name, %{pink-cheeked burnished red tamarin})
  insert(:name, %{pink-cheeked golden red tamarin})
  insert(:name, %{brown-maned dusky brown tamarin})
  insert(:name, %{brown-maned dark grey tamarin})
  insert(:name, %{brown-maned fuzzy brown tamarin})
  insert(:name, %{brown-maned fuzzy grey tamarin})
  insert(:name, %{brown-maned light brown tamarin})
  insert(:name, %{brown-maned burnished grey tamarin})
  insert(:name, %{brown-maned dusty brown tamarin})
  insert(:name, %{brown-maned burnished red tamarin})
  insert(:name, %{brown-maned golden red tamarin})
  insert(:name, %{mustachioed dusky brown tamarin})
  insert(:name, %{mustachioed dark grey tamarin})
  insert(:name, %{mustachioed fuzzy brown tamarin})
  insert(:name, %{mustachioed fuzzy grey tamarin})
  insert(:name, %{mustachioed light brown tamarin})
  insert(:name, %{mustachioed burnished grey tamarin})
  insert(:name, %{mustachioed dusty brown tamarin})
  insert(:name, %{mustachioed burnished red tamarin})
  insert(:name, %{mustachioed golden red tamarin})
  insert(:name, %{red-maned dusky brown tamarin})
  insert(:name, %{red-maned dark grey tamarin})
  insert(:name, %{red-maned fuzzy brown tamarin})
  insert(:name, %{red-maned fuzzy grey tamarin})
  insert(:name, %{red-maned light brown tamarin})
  insert(:name, %{red-maned burnished grey tamarin})
  insert(:name, %{red-maned dusty brown tamarin})
  insert(:name, %{red-maned burnished red tamarin})
  insert(:name, %{red-maned golden red tamarin})
  insert(:name, %{pinch-faced dusky brown tamarin})
  insert(:name, %{pinch-faced dark grey tamarin})
  insert(:name, %{pinch-faced fuzzy brown tamarin})
  insert(:name, %{pinch-faced fuzzy grey tamarin})
  insert(:name, %{pinch-faced light brown tamarin})
  insert(:name, %{pinch-faced burnished grey tamarin})
  insert(:name, %{pinch-faced dusty brown tamarin})
  insert(:name, %{pinch-faced burnished red tamarin})
  insert(:name, %{pinch-faced golden red tamarin})
  insert(:name, %{brown-crested dusky brown tamarin})
  insert(:name, %{brown-crested dark grey tamarin})
  insert(:name, %{brown-crested fuzzy brown tamarin})
  insert(:name, %{brown-crested fuzzy grey tamarin})
  insert(:name, %{brown-crested light brown tamarin})
  insert(:name, %{brown-crested burnished grey tamarin})
  insert(:name, %{brown-crested dusty brown tamarin})
  insert(:name, %{brown-crested burnished red tamarin})
  insert(:name, %{brown-crested golden red tamarin})
  insert(:name, %{blunt-faced dusky brown tamarin})
  insert(:name, %{blunt-faced dark grey tamarin})
  insert(:name, %{blunt-faced fuzzy brown tamarin})
  insert(:name, %{blunt-faced fuzzy grey tamarin})
  insert(:name, %{blunt-faced light brown tamarin})
  insert(:name, %{blunt-faced burnished grey tamarin})
  insert(:name, %{blunt-faced dusty brown tamarin})
  insert(:name, %{blunt-faced burnished red tamarin})
  insert(:name, %{blunt-faced golden red tamarin})
  insert(:name, %{red-crested dusky brown tamarin})
  insert(:name, %{red-crested dark grey tamarin})
  insert(:name, %{red-crested fuzzy brown tamarin})
  insert(:name, %{red-crested fuzzy grey tamarin})
  insert(:name, %{red-crested light brown tamarin})
  insert(:name, %{red-crested burnished grey tamarin})
  insert(:name, %{red-crested dusty brown tamarin})
  insert(:name, %{red-crested burnished red tamarin})
  insert(:name, %{red-crested golden red tamarin})
  insert(:name, %{peach-hued tarsier})
  insert(:name, %{light grey tarsier})
  insert(:name, %{light brown tarsier})
  insert(:name, %{speckled grey tarsier})
  insert(:name, %{dirty brown tarsier})
  insert(:name, %{dark grey tarsier})
  insert(:name, %{deep brown tarsier})
  insert(:name, %{russet tarsier})
  insert(:name, %{pale brown tarsier})
  insert(:name, %{dusty brown tarsier})
  insert(:name, %{flop-eared peach-hued tarsier})
  insert(:name, %{flop-eared light grey tarsier})
  insert(:name, %{flop-eared light brown tarsier})
  insert(:name, %{flop-eared speckled grey tarsier})
  insert(:name, %{flop-eared dirty brown tarsier})
  insert(:name, %{flop-eared dark grey tarsier})
  insert(:name, %{flop-eared deep brown tarsier})
  insert(:name, %{flop-eared russet tarsier})
  insert(:name, %{flop-eared pale brown tarsier})
  insert(:name, %{flop-eared dusty brown tarsier})
  insert(:name, %{brown-faced peach-hued tarsier})
  insert(:name, %{brown-faced light grey tarsier})
  insert(:name, %{brown-faced light brown tarsier})
  insert(:name, %{brown-faced speckled grey tarsier})
  insert(:name, %{brown-faced dirty brown tarsier})
  insert(:name, %{brown-faced dark grey tarsier})
  insert(:name, %{brown-faced deep brown tarsier})
  insert(:name, %{brown-faced russet tarsier})
  insert(:name, %{brown-faced pale brown tarsier})
  insert(:name, %{brown-faced dusty brown tarsier})
  insert(:name, %{large-eared peach-hued tarsier})
  insert(:name, %{large-eared light grey tarsier})
  insert(:name, %{large-eared light brown tarsier})
  insert(:name, %{large-eared speckled grey tarsier})
  insert(:name, %{large-eared dirty brown tarsier})
  insert(:name, %{large-eared dark grey tarsier})
  insert(:name, %{large-eared deep brown tarsier})
  insert(:name, %{large-eared russet tarsier})
  insert(:name, %{large-eared pale brown tarsier})
  insert(:name, %{large-eared dusty brown tarsier})
  insert(:name, %{fuzzy-faced peach-hued tarsier})
  insert(:name, %{fuzzy-faced light grey tarsier})
  insert(:name, %{fuzzy-faced light brown tarsier})
  insert(:name, %{fuzzy-faced speckled grey tarsier})
  insert(:name, %{fuzzy-faced dirty brown tarsier})
  insert(:name, %{fuzzy-faced dark grey tarsier})
  insert(:name, %{fuzzy-faced deep brown tarsier})
  insert(:name, %{fuzzy-faced russet tarsier})
  insert(:name, %{fuzzy-faced pale brown tarsier})
  insert(:name, %{fuzzy-faced dusty brown tarsier})
  insert(:name, %{pink-eared peach-hued tarsier})
  insert(:name, %{pink-eared light grey tarsier})
  insert(:name, %{pink-eared light brown tarsier})
  insert(:name, %{pink-eared speckled grey tarsier})
  insert(:name, %{pink-eared dirty brown tarsier})
  insert(:name, %{pink-eared dark grey tarsier})
  insert(:name, %{pink-eared deep brown tarsier})
  insert(:name, %{pink-eared russet tarsier})
  insert(:name, %{pink-eared pale brown tarsier})
  insert(:name, %{pink-eared dusty brown tarsier})
  insert(:name, %{blunt-faced peach-hued tarsier})
  insert(:name, %{blunt-faced light grey tarsier})
  insert(:name, %{blunt-faced light brown tarsier})
  insert(:name, %{blunt-faced speckled grey tarsier})
  insert(:name, %{blunt-faced dirty brown tarsier})
  insert(:name, %{blunt-faced dark grey tarsier})
  insert(:name, %{blunt-faced deep brown tarsier})
  insert(:name, %{blunt-faced russet tarsier})
  insert(:name, %{blunt-faced pale brown tarsier})
  insert(:name, %{blunt-faced dusty brown tarsier})
  insert(:name, %{wrinkled peach-hued tarsier})
  insert(:name, %{wrinkled light grey tarsier})
  insert(:name, %{wrinkled light brown tarsier})
  insert(:name, %{wrinkled speckled grey tarsier})
  insert(:name, %{wrinkled dirty brown tarsier})
  insert(:name, %{wrinkled dark grey tarsier})
  insert(:name, %{wrinkled deep brown tarsier})
  insert(:name, %{wrinkled russet tarsier})
  insert(:name, %{wrinkled pale brown tarsier})
  insert(:name, %{wrinkled dusty brown tarsier})
  insert(:name, %{wide-eyed peach-hued tarsier})
  insert(:name, %{wide-eyed light grey tarsier})
  insert(:name, %{wide-eyed light brown tarsier})
  insert(:name, %{wide-eyed speckled grey tarsier})
  insert(:name, %{wide-eyed dirty brown tarsier})
  insert(:name, %{wide-eyed dark grey tarsier})
  insert(:name, %{wide-eyed deep brown tarsier})
  insert(:name, %{wide-eyed russet tarsier})
  insert(:name, %{wide-eyed pale brown tarsier})
  insert(:name, %{wide-eyed dusty brown tarsier})
  insert(:name, %{blunt-tailed peach-hued tarsier})
  insert(:name, %{blunt-tailed light grey tarsier})
  insert(:name, %{blunt-tailed light brown tarsier})
  insert(:name, %{blunt-tailed speckled grey tarsier})
  insert(:name, %{blunt-tailed dirty brown tarsier})
  insert(:name, %{blunt-tailed dark grey tarsier})
  insert(:name, %{blunt-tailed deep brown tarsier})
  insert(:name, %{blunt-tailed russet tarsier})
  insert(:name, %{blunt-tailed pale brown tarsier})
  insert(:name, %{blunt-tailed dusty brown tarsier})
  insert(:name, %{bug-eyed peach-hued tarsier})
  insert(:name, %{bug-eyed light grey tarsier})
  insert(:name, %{bug-eyed light brown tarsier})
  insert(:name, %{bug-eyed speckled grey tarsier})
  insert(:name, %{bug-eyed dirty brown tarsier})
  insert(:name, %{bug-eyed dark grey tarsier})
  insert(:name, %{bug-eyed deep brown tarsier})
  insert(:name, %{bug-eyed russet tarsier})
  insert(:name, %{bug-eyed pale brown tarsier})
  insert(:name, %{bug-eyed dusty brown tarsier})
  insert(:name, %{drowsy peach-hued tarsier})
  insert(:name, %{drowsy light grey tarsier})
  insert(:name, %{drowsy light brown tarsier})
  insert(:name, %{drowsy speckled grey tarsier})
  insert(:name, %{drowsy dirty brown tarsier})
  insert(:name, %{drowsy dark grey tarsier})
  insert(:name, %{drowsy deep brown tarsier})
  insert(:name, %{drowsy russet tarsier})
  insert(:name, %{drowsy pale brown tarsier})
  insert(:name, %{drowsy dusty brown tarsier})
  insert(:name, %{toucan})
  insert(:name, %{blue toucan})
  insert(:name, %{bright blue toucan})
  insert(:name, %{collared toucan})
  insert(:name, %{emerald toucan})
  insert(:name, %{green toucan})
  insert(:name, %{hooded toucan})
  insert(:name, %{speckled toucan})
  insert(:name, %{black-banded toucan})
  insert(:name, %{black-banded blue toucan})
  insert(:name, %{black-banded bright blue toucan})
  insert(:name, %{black-banded collared toucan})
  insert(:name, %{black-banded emerald toucan})
  insert(:name, %{black-banded green toucan})
  insert(:name, %{black-banded hooded toucan})
  insert(:name, %{black-banded speckled toucan})
  insert(:name, %{ivory-billed toucan})
  insert(:name, %{ivory-billed blue toucan})
  insert(:name, %{ivory-billed bright blue toucan})
  insert(:name, %{ivory-billed collared toucan})
  insert(:name, %{ivory-billed emerald toucan})
  insert(:name, %{ivory-billed green toucan})
  insert(:name, %{ivory-billed hooded toucan})
  insert(:name, %{ivory-billed speckled toucan})
  insert(:name, %{black-billed toucan})
  insert(:name, %{black-billed blue toucan})
  insert(:name, %{black-billed bright blue toucan})
  insert(:name, %{black-billed collared toucan})
  insert(:name, %{black-billed emerald toucan})
  insert(:name, %{black-billed green toucan})
  insert(:name, %{black-billed hooded toucan})
  insert(:name, %{black-billed speckled toucan})
  insert(:name, %{red-billed toucan})
  insert(:name, %{red-billed blue toucan})
  insert(:name, %{red-billed bright blue toucan})
  insert(:name, %{red-billed collared toucan})
  insert(:name, %{red-billed emerald toucan})
  insert(:name, %{red-billed green toucan})
  insert(:name, %{red-billed hooded toucan})
  insert(:name, %{red-billed speckled toucan})
  insert(:name, %{black-necked toucan})
  insert(:name, %{black-necked blue toucan})
  insert(:name, %{black-necked bright blue toucan})
  insert(:name, %{black-necked collared toucan})
  insert(:name, %{black-necked emerald toucan})
  insert(:name, %{black-necked green toucan})
  insert(:name, %{black-necked hooded toucan})
  insert(:name, %{black-necked speckled toucan})
  insert(:name, %{red-necked toucan})
  insert(:name, %{red-necked blue toucan})
  insert(:name, %{red-necked bright blue toucan})
  insert(:name, %{red-necked collared toucan})
  insert(:name, %{red-necked emerald toucan})
  insert(:name, %{red-necked green toucan})
  insert(:name, %{red-necked hooded toucan})
  insert(:name, %{red-necked speckled toucan})
  insert(:name, %{blue-banded toucan})
  insert(:name, %{blue-banded blue toucan})
  insert(:name, %{blue-banded bright blue toucan})
  insert(:name, %{blue-banded collared toucan})
  insert(:name, %{blue-banded emerald toucan})
  insert(:name, %{blue-banded green toucan})
  insert(:name, %{blue-banded hooded toucan})
  insert(:name, %{blue-banded speckled toucan})
  insert(:name, %{spot-billed toucan})
  insert(:name, %{spot-billed blue toucan})
  insert(:name, %{spot-billed bright blue toucan})
  insert(:name, %{spot-billed collared toucan})
  insert(:name, %{spot-billed emerald toucan})
  insert(:name, %{spot-billed green toucan})
  insert(:name, %{spot-billed hooded toucan})
  insert(:name, %{spot-billed speckled toucan})
  insert(:name, %{curl-crested toucan})
  insert(:name, %{curl-crested blue toucan})
  insert(:name, %{curl-crested bright blue toucan})
  insert(:name, %{curl-crested collared toucan})
  insert(:name, %{curl-crested emerald toucan})
  insert(:name, %{curl-crested green toucan})
  insert(:name, %{curl-crested hooded toucan})
  insert(:name, %{curl-crested speckled toucan})
  insert(:name, %{stripe-billed toucan})
  insert(:name, %{stripe-billed blue toucan})
  insert(:name, %{stripe-billed bright blue toucan})
  insert(:name, %{stripe-billed collared toucan})
  insert(:name, %{stripe-billed emerald toucan})
  insert(:name, %{stripe-billed green toucan})
  insert(:name, %{stripe-billed hooded toucan})
  insert(:name, %{stripe-billed speckled toucan})
  insert(:name, %{fiery-billed toucan})
  insert(:name, %{fiery-billed blue toucan})
  insert(:name, %{fiery-billed bright blue toucan})
  insert(:name, %{fiery-billed collared toucan})
  insert(:name, %{fiery-billed emerald toucan})
  insert(:name, %{fiery-billed green toucan})
  insert(:name, %{fiery-billed hooded toucan})
  insert(:name, %{fiery-billed speckled toucan})
  insert(:name, %{yellow-browed toucan})
  insert(:name, %{yellow-browed blue toucan})
  insert(:name, %{yellow-browed bright blue toucan})
  insert(:name, %{yellow-browed collared toucan})
  insert(:name, %{yellow-browed emerald toucan})
  insert(:name, %{yellow-browed green toucan})
  insert(:name, %{yellow-browed hooded toucan})
  insert(:name, %{yellow-browed speckled toucan})
  insert(:name, %{grey-breasted toucan})
  insert(:name, %{grey-breasted blue toucan})
  insert(:name, %{grey-breasted bright blue toucan})
  insert(:name, %{grey-breasted collared toucan})
  insert(:name, %{grey-breasted emerald toucan})
  insert(:name, %{grey-breasted green toucan})
  insert(:name, %{grey-breasted hooded toucan})
  insert(:name, %{grey-breasted speckled toucan})
  insert(:name, %{yellow-ridged toucan})
  insert(:name, %{yellow-ridged blue toucan})
  insert(:name, %{yellow-ridged bright blue toucan})
  insert(:name, %{yellow-ridged collared toucan})
  insert(:name, %{yellow-ridged emerald toucan})
  insert(:name, %{yellow-ridged green toucan})
  insert(:name, %{yellow-ridged hooded toucan})
  insert(:name, %{yellow-ridged speckled toucan})
  insert(:name, %{groove-billed toucan})
  insert(:name, %{groove-billed blue toucan})
  insert(:name, %{groove-billed bright blue toucan})
  insert(:name, %{groove-billed collared toucan})
  insert(:name, %{groove-billed emerald toucan})
  insert(:name, %{groove-billed green toucan})
  insert(:name, %{groove-billed hooded toucan})
  insert(:name, %{groove-billed speckled toucan})
  insert(:name, %{arctic wolf})
  insert(:name, %{blue wolf})
  insert(:name, %{great white wolf})
  insert(:name, %{grey wolf})
  insert(:name, %{amber-eyed grizzled timber wolf})
  insert(:name, %{air wyrdling})
  insert(:name, %{cloudy-eyed air wyrdling})
  insert(:name, %{long-eared air wyrdling})
  insert(:name, %{ethereal air wyrdling})
  insert(:name, %{long-nosed air wyrdling})
  insert(:name, %{foggy-eyed air wyrdling})
  insert(:name, %{soft-featured air wyrdling})
  insert(:name, %{lithe air wyrdling})
  insert(:name, %{white-eyed air wyrdling})
  insert(:name, %{earth wyrdling})
  insert(:name, %{amber-eyed earth wyrdling})
  insert(:name, %{large-nosed earth wyrdling})
  insert(:name, %{crumbling earth wyrdling})
  insert(:name, %{rough earth wyrdling})
  insert(:name, %{crystal-eyed earth wyrdling})
  insert(:name, %{round-eared earth wyrdling})
  insert(:name, %{dusty earth wyrdling})
  insert(:name, %{squat earth wyrdling})
  insert(:name, %{dusty-eyed earth wyrdling})
  insert(:name, %{stout earth wyrdling})
  insert(:name, %{fire wyrdling})
  insert(:name, %{angular fire wyrdling})
  insert(:name, %{sharp-eared fire wyrdling})
  insert(:name, %{ember-eyed fire wyrdling})
  insert(:name, %{sharp-nosed fire wyrdling})
  insert(:name, %{lanky fire wyrdling})
  insert(:name, %{smoky fire wyrdling})
  insert(:name, %{red-eyed fire wyrdling})
  insert(:name, %{smoky-eyed fire wyrdling})
  insert(:name, %{scaled fire wyrdling})
  insert(:name, %{smoldering fire wyrdling})
  insert(:name, %{lightning wyrdling})
  insert(:name, %{angular lightning wyrdling})
  insert(:name, %{nebulous lightning wyrdling})
  insert(:name, %{hook-nosed lightning wyrdling})
  insert(:name, %{scaled lightning wyrdling})
  insert(:name, %{jagged-eared lightning wyrdling})
  insert(:name, %{silver-eyed lightning wyrdling})
  insert(:name, %{lanky lightning wyrdling})
  insert(:name, %{spark-eyed lightning wyrdling})
  insert(:name, %{water wyrdling})
  insert(:name, %{blue-eyed water wyrdling})
  insert(:name, %{misty-eyed water wyrdling})
  insert(:name, %{frothy-eyed water wyrdling})
  insert(:name, %{sleek water wyrdling})
  insert(:name, %{lithe water wyrdling})
  insert(:name, %{small-nosed water wyrdling})
  insert(:name, %{long-eared water wyrdling})
  insert(:name, %{smooth water wyrdling})
  insert(:name, %{misty water wyrdling})
end
