migrate :aggressive_npc do
  insert(:name, %{behemothic gorefrost golem})
  insert(:name, %{bloody halfling cannibal})
  insert(:name, %{brawny gigas shield-maiden})
  insert(:name, %{colossal boreal undansormr})
  insert(:name, %{flayed gigas disciple})
  insert(:name, %{grim gigas skald})
  insert(:name, %{heavily armored battle mastodon})
  insert(:name, %{immense gold-bristled hinterboar})
  insert(:name, %{niveous giant warg})
  insert(:name, %{quivering sanguine ooze})
  insert(:name, %{savvage fork-tongued wendigo})
  insert(:name, %{squamous reptilian mutant})
  insert(:name, %{stunted halfling bloodspeaker})
  insert(:name, %{tattooed gigas berserker})
end

migrate :undead, :aggressive_npc do
  insert(:name, %{eyeless black valravn})
  insert(:name, %{shining winged disir})
  insert(:name, %{withered shadow-cloaked draugr})
end

migrate :undead, :aggressive_npc, :noncorporeal do
  insert(:name, %{roiling crimson angargeist})
end

migrate :gem, :gemshop do
  insert(:name, %{piece of blood amber})
  insert(:name, %{frosted pale violet amethyst})
  insert(:name, %{dark ivory aranthium-bloom})
  insert(:name, %{cylindrical red beryl})
  insert(:name, %{twilight blue azurite crystal})
  insert(:name, %{isty grey deathstone})
  insert(:name, %{teal chrome diopside})
  insert(:name, %{deep voilet duskjewel})
  insert(:name, %{fossilized undansormr egg})
  insert(:name, %{gold-green aurorl emerald})
  insert(:name, %{petrified warg fang})
  insert(:name, %{lustrous vermilion firedrop})
  insert(:name, %{deep red-violet garnet})
  insert(:name, %{vibrant titian heliodor})
  insert(:name, %{mottled green jasper})
  insert(:name, %{blue-violet chunk of kornerupine})
  insert(:name, %{chunk of pale marble})
  insert(:name, %{dull griseous mournstone})
  insert(:name, %{inky black nightstone})
  insert(:name, %{silver-hite palladium nugget})
  insert(:name, %{piece of clear oligoclase})
  insert(:name, %{gold-banded onyx})
  insert(:name, %{silvery nimbus opal})
  insert(:name, %{pastel-hued winterbite pearl})
  insert(:name, %{lambent gold warg's eye quartz})
  insert(:name, %{bluish black razern-bloom})
  insert(:name, %{vinous gigasblood ruby})
  insert(:name, %{faceted wyrm's-heart sapphire})
  insert(:name, %{piece of dusky blue sapphire})
  insert(:name, %{nival everfrost shard})
  insert(:name, %{rainbowed ammolite shard})
  insert(:name, %{virescent nephrite shard})
  insert(:name, %{stark white snowstone})
  insert(:name, %{shard of streaked blue spectrolite})
  insert(:name, %{vivid cobalt blue spinel})
  insert(:name, %{grey-streaked malachite stone})
  insert(:name, %{saffron-hued danburite stone})
  insert(:name, %{carved basalt teardrop})
  insert(:name, %{piece of coppery titanite})
  insert(:name, %{royal blue boreal topaz})
  insert(:name, %{rutilated twilight tourmaline})
  insert(:name, %{green and pink zoisite})
end
