migrate :skin, :furrier do
  create_key(:exclude)
  insert(:name, %{gold-flecked claw})
  insert(:name, %{red firebird feather})
  insert(:name, %{triton spine})
  insert(:name, %{triton hide})
  insert(:exclude, %{gold-flecked claw})
  insert(:exclude, %{red firebird feather})
  insert(:exclude, %{triton spine})
  insert(:exclude, %{triton hide})
  insert(:exclude, %{bundle of curved gold-flecked claws})
  insert(:exclude, %{bundle of soft red firebird feathers})
  insert(:exclude, %{bundle of elongated triton spines})
  insert(:exclude, %{bundle of iridescent triton hides})
end
