create_table "event:ebongate", keys: [:name]
create_table "customization:death", keys: [:name]
create_table "customization:misc", keys: [:name]
create_table "customization:spellprep", keys: [:name]
  
migrate "event:ebongate", "customization:death" do
  insert(:name, %{bright orange circular tombstone})
  insert(:name, %{broken clover\-shaped tombstone})
  insert(:name, %{broken terracotta pot})
  insert(:name, %{carved green c crypt miniature})
  insert(:name, %{cast brass fist})
  insert(:name, %{cracked glass tombstone})
  insert(:name, %{cracked jadeite egg})
  insert(:name, %{crazed white\-glazed amulet})
  insert(:name, %{crossed\-out red circle sign})
  insert(:name, %{cup of coffee carving})
  insert(:name, %{dried chicken foot})
  insert(:name, %{faceted pyrite horseshoe})
  insert(:name, %{flat black plate})
  insert(:name, %{foggy glass tombstone})
  insert(:name, %{fractured glass candleholder})
  insert(:name, %{ghostly white marble effigy})
  insert(:name, %{gold\-set citrine medallion})
  insert(:name, %{green glass lilypad})
  insert(:name, %{handful of weathered stones})
  insert(:name, %{jasper and silver\-caged locket})
  insert(:name, %{knotted blue cloth ragdoll})
  insert(:name, %{lacquered red bamboo bookmark})
  insert(:name, %{miniature brown frigate})
  insert(:name, %{miniature fjord model})
  insert(:name, %{miniature slate tombstone})
  insert(:name, %{moldering green silk cravat})
  insert(:name, %{nacreous pearl bangle})
  insert(:name, %{padded leather glove})
  insert(:name, %{point\-toed cast bronze foot})
  insert(:name, %{reticulated quartz nodule})
  insert(:name, %{rusty bloodstained scimitar})
  insert(:name, %{shadowy dragon\'s tail sculpture})
  insert(:name, %{shiny golden key})
  insert(:name, %{slender jade green needle})
  insert(:name, %{small lump of coprolite})
end

migrate "event:ebongate", "customization:misc" do
  insert(:name, %{apparitions illusion style carving})
end

migrate "event:ebongate", "customization:spellprep" do
  insert(:name, %{amorphous blob token})
  insert(:name, %{ashen hand-shaped vellum})
  insert(:name, %{azure cuckoo bee})
  insert(:name, %{bile green spectre charm})
  insert(:name, %{bloodshot eye\-drawn vellum})
  insert(:name, %{bronze whistle\-drawn vellum})
  insert(:name, %{bubble\-swirled vellum})
  insert(:name, %{chartreuse acid token})
  insert(:name, %{cinereous steam token})
  insert(:name, %{copper and silver leaf})
  insert(:name, %{crackling flame token})
  insert(:name, %{dirge button})
  insert(:name, %{dried zombie hand})
  insert(:name, %{fabric cherry blossom})
  insert(:name, %{flame\-edged cinderous token})
  insert(:name, %{folded dark ecru vellum})
  insert(:name, %{frayed and fading postcard})
  insert(:name, %{frayed drab grey vellum})
  insert(:name, %{ghostly white mask\-drawn vellum})
  insert(:name, %{glittering silver and blue orb})
  insert(:name, %{golden crown symbol})
  insert(:name, %{gradient ebon and blue vellum})
  insert(:name, %{hovering spectre pin})
  insert(:name, %{inky black\-colored vellum})
  insert(:name, %{lotus seed bun})
  insert(:name, %{metallic blue scarab})
  insert(:name, %{muted grey vellum})
  insert(:name, %{night blue star\-covered vellum})
  insert(:name, %{petrified cracker sandwich})
  insert(:name, %{petrified egg\-shaped tart})
  insert(:name, %{petrified rice ball})
  insert(:name, %{petrified tea leaf\-shaped pastry})
  insert(:name, %{polychromatic lotus blossom})
  insert(:name, %{rivulet\-inked vellum})
  insert(:name, %{rough iron grey vellum})
  insert(:name, %{scarlet toy serpent})
  insert(:name, %{shadow\-inked vellum})
  insert(:name, %{shadow\-swept glowing orb})
  insert(:name, %{shimmering mandala\-inked vellum})
  insert(:name, %{silver\-eyed peacock feather})
  insert(:name, %{sinuous rubbery grey tentacle})
  insert(:name, %{slender off\-white vellum})
  insert(:name, %{small cloud token})
  insert(:name, %{small dark kelyn eye symbol})
  insert(:name, %{small jet black eye symbol})
  insert(:name, %{solid white marble})
  insert(:name, %{sparkling ebon gate})
  insert(:name, %{subtle gold vellum})
  insert(:name, %{textured stone grey vellum})
  insert(:name, %{tiny absinthe green button})
  insert(:name, %{tiny bolt\-etched disk})
  insert(:name, %{tiny cloud\-covered disk})
  insert(:name, %{tiny enruned disk})
  insert(:name, %{tiny enruned brass disk})
  insert(:name, %{tiny glaesine disk})
  insert(:name, %{tiny granite disk})
  insert(:name, %{tiny ice\-covered disk})
  insert(:name, %{tiny malachite disk})
  insert(:name, %{tiny marble tongue})
  insert(:name, %{tiny mouse\-inked vellum})
  insert(:name, %{tiny obsidian disk})
  insert(:name, %{tiny pine snowflake symbol})
  insert(:name, %{tiny repousse copper disk})
  insert(:name, %{tiny waterspout token})
  insert(:name, %{wave\-stamped green orb})
  insert(:name, %{white and icy blue vellum})
  insert(:name, %{wisp\-inked vellum})
end

migrate :ebongate, :valuable do
  insert(:name, %{argent crystal\-studded scoria})
  insert(:name, %{asymmetrical ink black crowstone})
  insert(:name, %{blush\-hearted violet dusk opal})
  insert(:name, %{chunk of abyssal onyx})
  insert(:name, %{cobalt\-laced deep magenta everine})
  insert(:name, %{columnar coral\-tinged auroraline})
  insert(:name, %{crimson\-hazed silvery green everine})
  insert(:name, %{crystal\-edged twilight blue everine})
  insert(:name, %{crystal\-rife pitch black scoria})
  insert(:name, %{crystallized dark grape amethyst})
  insert(:name, %{ebon\-clouded crimson phantom sapphire})
  insert(:name, %{ether\-warped lavender soulstone})
  insert(:name, %{ether\-warped virid soulstone})
  insert(:name, %{fiery\-veined cobalt fox agate})
  insert(:name, %{full\-petaled azurite rosette})
  insert(:name, %{hyacinth violet opal arcrose})
  insert(:name, %{indigo\-cored ultramarine fluorite})
  insert(:name, %{iridescent geode druzy stone})
  insert(:name, %{iridescent peacock blue crowstone})
  insert(:name, %{misshapen sunset crater agate})
  insert(:name, %{oval of black lightning opal})
  insert(:name, %{pale zephyr\-inked vellum})
  insert(:name, %{particolored astral sapphire})
  insert(:name, %{piece of pitted grey scoria})
  insert(:name, %{pillar of honeycomb jasper})
  insert(:name, %{pink\-cored cerulean opal arcrose})
  insert(:name, %{red\-blossomed tangerine everine})
  insert(:name, %{ruby crystal\-strewn scoria})
  insert(:name, %{rutilated rainbow crystal})
  insert(:name, %{shard of dark pink\-on\-violet alexandrite})
  insert(:name, %{shard of gold\-webbed red obsidian})
  insert(:name, %{slice of golden requiem sunstone})
  insert(:name, %{slice of grey requiem dreamstone})
  insert(:name, %{small azure\-banded auroraline})
  insert(:name, %{spectral dark silver soulstone})
  insert(:name, %{spectral ultramarine soulstone})
  insert(:name, %{spherical fuchsia\-tinted auroraline})
  insert(:name, %{spray of lustrous white scolecite})
  insert(:name, %{sunrise\-hued white opal arcrose})
  insert(:name, %{tumbled lilac\-striated auroraline})
  insert(:name, %{umber\-orbed ebony fox agate})
  insert(:name, %{virid\-webbed dark teal everine})
  insert(:name, %{watery cyan\-hued opal arcrose})
  insert(:name, %{wedge of polychromatic crowstone})
  insert(:name, %{wing\-shaped piece of silver crowstone})
end
  
migrate "junk" do
  insert(:name, %{bits of blue yarn})
  insert(:name, %{broken algae-stained wand})
  insert(:name, %{carved wooden tadpole lure})
  insert(:name, %{(?:auburn|coarse black|dusty blonde|golden blonde|silky titian|silver) braided hair brooch})
  insert(:name, %{coil of braided (?:brown|silver) hair})
  insert(:name, %{clump of muddy lemongrass})
  insert(:name, %{cracked glass bead lure})
  insert(:name, %{fistful of peat moss and loam})
  insert(:name, %{fistful of scraggly grey moss})
  insert(:name, %{fuzzy moss\-covered ear})
  insert(:name, %{glossy inky black nightcrawler})
  insert(:name, %{glowing blue snail shell})
  insert(:name, %{glowing green snail shell})
  insert(:name, %{moldy wooden toothpick})
  insert(:name, %{pitted iron fishing hook})
  insert(:name, %{rubbery large bloodworm})
  insert(:name, %{shaggy yellow\-white straw})
  insert(:name, %{smattering of curling wood shavings})
  insert(:name, %{some moldy wooden dice})
  insert(:name, %{sparkly fake silver fish})
  insert(:name, %{spike of twisted black iron})
  insert(:name, %{tiny half\-eaten grasshopper})
  insert(:name, %{warped deathstone})
  insert(:name, %{warped soulstone})
  insert(:name, %{wiggly fake squid})
  insert(:name, %{wire\-fringed lilac and white lure})
  insert(:name, %{withered moldy slice of apple})
end
