migrate :aggressive_npc, :undead do
  insert(:name, %[ethereal barbarian])
  insert(:name, %[ethereal knight])
  insert(:name, %[ethereal pillager])
  insert(:name, %[ethereal raider])
  insert(:name, %[ethereal scout])
  insert(:name, %[ethereal soldier])
  insert(:name, %[ethereal waylayer])
  insert(:name, %[ethereal zealot])
  insert(:name, %[ethereal guard])
  insert(:name, %[ethereal guardsman])
  insert(:name, %[ethereal guardswoman])
  insert(:name, %[ethereal inmate])
  insert(:name, %[ethereal lunatic])
  insert(:name, %[ethereal madman])
  insert(:name, %[ethereal madwoman])
  insert(:name, %[ethereal prisoner])
  insert(:name, %[ethereal squire])
  insert(:name, %[ethereal swordsman])
  insert(:name, %[ethereal swordswoman])
  insert(:name, %[ghostly bandit])
  insert(:name, %[ghostly highwayman])
  insert(:name, %[ghostly highwaywoman])
  insert(:name, %[ghostly marauder])
  insert(:name, %[ghostly waylayer])
  insert(:name, %[unworldly barbarian])
  insert(:name, %[unworldly knight])
  insert(:name, %[unworldly pillager])
  insert(:name, %[unworldly raider])
  insert(:name, %[unworldly scout])
  insert(:name, %[unworldly soldier])
  insert(:name, %[unworldly waylayer])
  insert(:name, %[unworldly zealot])
  insert(:name, %[unworldly guest])
  insert(:name, %[unworldly maid])
  insert(:name, %[unworldly noble])
  insert(:name, %[unworldly royal guard])
  insert(:name, %[unworldly royal knight])
  insert(:name, %[unworldly servant])
  insert(:name, %[unworldly slave])
  insert(:name, %[unworldly steward])
  insert(:name, %[unworldly visitor])
  insert(:name, %[celestial dancer])
  insert(:name, %[celestial juggler])
  insert(:name, %[celestial nomad])
  insert(:name, %[celestial traveller])
  insert(:name, %[Butler])
  insert(:name, %[Cook])
  insert(:name, %[Knight Captain])
  insert(:name, %[Foreign Dignitary])
  insert(:name, %[Royal Prince])
  insert(:name, %[Royal Princess])
  insert(:name, %[Royal Jester])
  insert(:name, %[Royal Emperor])
  insert(:name, %[Royal Empress])
  insert(:name, %[Sapper Lord])
  insert(:name, %[Sapper Lady])
  insert(:name, %[Raid Leader])
  insert(:name, %[Dark Knight])
  insert(:name, %[Massive Butcher])
  insert(:name, %[Slender Mercenary])
  insert(:name, %[Darkly Hooded Figure])
  insert(:name, %[Crimson Count])
  insert(:name, %[Kennel Master])
  insert(:name, %[Royal Inquisitor])
  insert(:name, %[Towering Crusader])
  insert(:name, %[Hulking Berserker])
  insert(:name, %[Jester Ser Rets])
  insert(:name, %[Dame Venti])
  insert(:name, %[Corrupted Knight Owrym])
  insert(:name, %[Arch Priest Dlitse])
  insert(:name, %[Dame Elle Zo])
  insert(:name, %[Thane Wedge])
  insert(:name, %[Dark Astrologer Scionae])
  insert(:name, %[speedy sapper])
end

migrate :gem, :gemshop do
  insert(:name, %[round of milky amber])
  insert(:name, %[smoky amethyst])
  insert(:name, %[hexagonal cobalt blue beryl])
  insert(:name, %[chunk of bronzite])
  insert(:name, %[marbled green chrysoprase])
  insert(:name, %[cluster of sky blue crystal])
  insert(:name, %[ice blue diamond])
  insert(:name, %[nebulous emerald])
  insert(:name, %[lustrous black garnet])
  insert(:name, %[ethereal blue gem])
  insert(:name, %[teardrop of dark green heliotrope])
  insert(:name, %[spear of lavender-grey iolite])
  insert(:name, %[piece of jet-flecked ivory])
  insert(:name, %[piece of black jade])
  insert(:name, %[piece of blue jade])
  insert(:name, %[pebble of orbicular jasper])
  insert(:name, %[cone of mahogany obsidian])
  insert(:name, %[heart of blue onyx])
  insert(:name, %[cloud opal])
  insert(:name, %[iridescent wood opal])
  insert(:name, %[jelly opal])
  insert(:name, %[shard of pink petalite])
  insert(:name, %[luminous prehnite])
  insert(:name, %[snow quartz])
  insert(:name, %[haloed Reim ruby])
  insert(:name, %[pallid sapphire])
  insert(:name, %[chunk of pale blue ice stone])
  insert(:name, %[chunk of pearly grey ice stone])
  insert(:name, %[chunk of snowy white ice stone])
  insert(:name, %[slice of ribbon stone])
  insert(:name, %[dark blue tempest stone])
  insert(:name, %[faint gold tempest stone])
  insert(:name, %[pale grey tempest stone])
  insert(:name, %[ebon-cored vortex stone])
  insert(:name, %[silver-cored vortex stone])
  insert(:name, %[sliver of bright green viridine])
end

migrate :uncommon do
  insert(:exclude, %[cone of mahogany obsidian])
end

migrate :magic, :pawnshop do
  insert(:exclude, %[cluster of sky blue crystal])
end
