require 'lich/gameobj'
require 'spec/factories'

describe GameObj do
  describe "collectibles" do
    [
      %{miniature warrior figurine},
      %{miniature rogue figurine},
      %{miniature wizard figurine},
      %{miniature cleric figurine},
      %{miniature empath figurine},
      %{miniature sorcerer figurine},
      %{miniature ranger figurine},
      %{miniature bard figurine},
      %{miniature monk figurine},
      %{miniature paladin figurine},
      %{polished stone},
      %{oblong smooth stone},
      %{glossy smooth stone},
      %{shiny smooth stone},
      %{slick smooth stone},
      %{rounded smooth stone},
      %{cubic smooth stone},
      %{flat smooth stone},
      %{ovoid smooth stone},
      %{heavy smooth stone},
      %{mottled smooth stone},
      %{sliver of rough moonstone},
      %{piece of cloudy glass},
      %{shard of cloudy soulstone},
      %{handful of silver flakes},
      %{handful of gold flakes},
      %{handful of icy blue flakes},
      %{handful of iron flakes},
      %{handful of coral flakes},
      %{golden piece of eight},
      %{ruby shard},
      %{threaded pink pearl},
      %{threaded grey pearl},
      %{threaded white pearl},
      %{threaded black pearl},
      %{threaded green pearl},
      %{luminescent sandstone chunk},
      %{blue cotton swathe},
      %{yellow cotton swathe},
      %{red cotton swathe},
      %{black cotton swathe},
      %{whisper of divine essence},
      %{antique lockpick},
      %{fossilized shell},
      %{meteorite chipping},
      %{ornate Charl statuette},
      %{ornate Cholen statuette},
      %{ornate Eonak statuette},
      %{ornate Imaera statuette},
      %{ornate Jastev statuette},
      %{ornate Kai statuette},
      %{ornate Koar statuette},
      %{ornate Lorminstra statuette},
      %{ornate Lumnis statuette},
      %{ornate Oleani statuette},
      %{ornate Phoen statuette},
      %{ornate Ronan statuette},
      %{ornate Tonis statuette},
      %{ornate Andelas statuette},
      %{ornate Eorgina statuette},
      %{ornate Fash'lo'nae statuette},
      %{ornate Ivas statuette},
      %{ornate Luukos statuette},
      %{ornate Marlu statuette},
      %{ornate Mularos statuette},
      %{ornate Sheru statuette},
      %{ornate V'tull statuette},
      %{ornate Gosaena statuette},
      %{ornate Zelia statuette},
      %{ornate Huntress statuette},
      %{ornate Leya statuette},
      %{ornate Onar statuette},
      %{ornate Voln statuette},
      %{ornate Aeia statuette},
      %{ornate Jaston statuette},
      %{ornate Kuon statuette},
      %{ornate Khaarne statuette},
      %{ornate Meyno statuette},
      %{ornate Niima statuette},
      %{ornate Illoke statuette},
      %{ornate Amasalen statuette},
      %{ornate Arachne statuette},
      %{ornate Laethe statuette},
      %{ornate Tilamaire statuette},
      %{ornate Voaris statuette},
      %{ornate Voln statuette},
      %{small blue clay mortar},
      %{marbled blue marble pestle},
      %{some grey-colored powder},
      %{thin-lipped clear glass bottle},
      %{blood-stained bandana},
      %{Elanthian Guilds Council token},
      %{ethereal chain},
      %{ethereal pendant},
      %{tiny ethereal orb},
    ].each do |collectible_name|
      it "recognizes #{collectible_name} as collectible" do
        collectible = GameObjFactory.item_from_name(collectible_name)
        expect(collectible.type).to eq "collectible"
        expect(collectible.sellable).to be nil
      end
    end
  end
end
