#!/usr/bin/env ruby
##
## lookup from root of project
##
def root_glob(*parts)
  Dir[File.join(__dir__, "..", *parts)]
end
##
## autoload all migration assets
##
root_glob("lib", "migration", "**", "*.rb").each do |file| require file end
##
## do eeet
##
Migration::run(
  migrations: root_glob("migrations", "**", "*.rb"),
  tables:     root_glob("tables", "**", "*.yaml"))