name: Publish gameobj-data
on:
#  workflow_dispatch:
  push:
    branches: [ 'master' ]
    paths:
#      - 'lib/**'
#      - 'spec/gameobj-data/**'
      - 'type_data/**'
      - 'scripts/spell-list.xml'
      
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish gameobj-data
    steps:
      - name: Checkout EO-Scripts
        uses: actions/checkout@v2
        with:
          fetch-depth: '20'
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          
      - name: Setup bundler cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Update apt repo sources
        run: sudo apt-get update -y        
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
        
      - name: Install ruby gem dependencies with bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Run type data migrations to create gameobj-data.xml
        run: |
          bin/migrate
          mkdir /home/runner/work/scripts/lich5
          cp dist/gameobj-data.xml /home/runner/work/scripts/lich5
          cp scripts/spell-list.xml /home/runner/work/scripts/lich5

      - name: Checkout EO-Lich5
        uses: actions/checkout@v2
        with:
          repository: elanthia-online/lich-5
          token: ${{secrets.PAT_FOR_JINX_PUSH}}

      - name: Pushes GameObj-data.xml file
        run: |
          cp /home/runner/work/scripts/lich5/gameobj-data.xml /home/runner/work/scripts/scripts/data/
          cp /home/runner/work/scripts/lich5/spell-list.xml /home/runner/work/scripts/scripts/data/
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
          git add data
          git commit -m "Automatic publish from github.com/elanthia-online/scripts"
          git push
