name: RSpec Tests
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7']
    name: Run tests on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup bundler cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Update apt repo sources
        run: sudo apt-get update -y
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      - name: Install ruby gem dependencies with bundler
        run: |
          gem install bundler -v 2.4.22
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run type data migrations to create gameobj-data.xml
        run: bin/migrate
      - name: Run RSpec tests
        run: bundle exec rspec
