name: Rubocop
on:
  push:
    branches:
      - master
    paths:
      - 'scripts/**'
      - 'type_data/migrations/**'
  pull_request:
    paths:
      - 'scripts/**'
      - 'type_data/migrations/**'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    name: Run Rubocop on Ruby
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@2e07db73e5ccdb319b9a6c7766bd46d39d304bad # v47.0.5
        with:
          files: |
            **/*.lic
            **/*.rb
        
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          bundler-cache: true

      - name: Rubocop
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            bundle exec rubocop $file
          done
