name: Rubocop
on:
  push:
    branches:
      - master
    paths:
      - 'scripts/**'
      - 'type_data/migrations/**'
  pull_request:
    paths:
      - 'scripts/**'
      - 'type_data/migrations/**'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    name: Run Rubocop on Ruby
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@2e07db73e5ccdb319b9a6c7766bd46d39d304bad # v47.0.5
        with:
          files: |
            **/*.lic
            **/*.rb
        
      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          bundler-cache: true

      - name: Rubocop
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            bundle exec rubocop $file
          done
