name: Smoke Tests
on:
  schedule:
    - cron: '*/37 * * * *'

jobs:
  jinx:
    name: Jinx Smoke Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
        with:
          ruby-version: '2.6'
      - name: Setup bundler cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install ruby gem dependencies with bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Jinx spec against live servers
        run: bundle exec rspec spec/jinx/jinx_spec.rb
        env:

          ENABLE_EXTERNAL_NETWORKING: true
